### ISSUE TITLE
SaluSpa Honolulu - Model S100104

### ISSUE THREAD

**Issue by simracingstudio** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#118]
Hello guys,

Just finished to solder pcb and uploaded the code.
![image](https://user-images.githubusercontent.com/47185130/133901601-b95882ec-c748-4843-83aa-ae38424d72de.png)

I cannot control the spa via web interface, neither display.

If I have the PCB connected when I plug the unit to the wall the Display does not beeps.
It shows red on the C and that's all, none of the buttons work.

I have tried Dev and Stable branches, also tried to use the 160 Frequency and no luck.

I think the issue is the communication of the ESP32 with the mainboard, because all status commands return 0 in the debug.html
![image](https://user-images.githubusercontent.com/47185130/133900422-fc979b58-93bb-4cc1-af37-e3736fb8881a.png)

This is the display
![image](https://user-images.githubusercontent.com/47185130/133902714-d8e997e2-e157-4b3b-b74c-e05496c042b3.png)

Model
![image](https://user-images.githubusercontent.com/47185130/133902905-7091ecdd-2f30-47e8-b5fa-0bde44dfacdb.png)

I believe the next step is to try the resistor, but I'm not sure where to solder and each one. If someone can provide a light, I will really appreciate.

**Comment by visualapproach** [comment]
Forgot to solder the LLC pins?

**Comment by simracingstudio** [comment]
You are right I was going to turn off everything and spotted that.

Any concern if I use the dev branch?

Don’t close it yet let me do more tests, just finished to solder

--

**Comment by visualapproach** [comment]
Dev branch should be stable also at the moment but with a few updates.
Good luck

**Comment by simracingstudio** [comment]
It works!!! The only thing missing are the beeps.

--

**Comment by visualapproach** [comment]
Great 👍 
Some newer models appear to have lower volume when using this device. I don't know why that is. Probably a different circuit. Can't do anything until someone figure out what the problem is. (I have an older pump)
