### ISSUE TITLE
Mains control

### ISSUE THREAD

**Issue by gabrielke** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#119]
As I understand this project it implies the spa is basically turned on (so power is green).
This doesn't change the behavior after a power outage (whole thing remains turned off as factory default, right?)

Or it can "press" the power button too somehow?

**Comment by gabrielke** [comment]
changed to a question in discussions instead

**Comment by visualapproach** [comment]
@gabrielke This only applies to the 6 pin version. 
As far as I can tell, the pump is always "on", even when you press POWER OFF on the original pump. It only dims the display and nothing else is running. Mains is never turned off unless you pull the plug or hit the protection breaker. The device can turn OFF or ON the display as you would when pressing the button yourself. What happens after power outage is more or less configurable from the web interface - restore states or everything is off.
