### ISSUE TITLE
Our cozy places

### ISSUE THREAD

**Issue by visualapproach** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#13]
You are welcome to post pictures of your SPA here for us to be inspired of. Here is my place:

![spa-2](https://user-images.githubusercontent.com/22987250/91754834-63e38e00-ebca-11ea-8861-c1cc5149666c.jpg)

**Comment by 877dev** [comment]
Very nice! My spa is down the garden while we have house renovations. I will post when it’s back in place.

**Comment by eddcaton** [comment]
![116293465_10163852282380297_9046193191604121337_o](https://user-images.githubusercontent.com/42009843/95364948-602de000-08c9-11eb-9144-e94d320c79ab.jpg)
![116221602_10163852282595297_5998162829358902489_o](https://user-images.githubusercontent.com/42009843/95364957-6328d080-08c9-11eb-9a08-fb005eb90839.jpg)

**Comment by visualapproach** [comment]
Awesome! Me like the star heaven! Thanks for showing it to us!

**Comment by eddcaton** [comment]
Thanks :) I have to say drilling almost 1000 holes by hand with a 2mm drill bit was not the highlight of my week!
