### ISSUE TITLE
I think there is something wrong with the cost calculation.

### ISSUE THREAD

**Issue by AlbertDijksma** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#132]
Hi,

I think there is something wrong with the cost calculation.
It will go wrong if there are no hydrojets present.

	_cost = _price*(
                  (_heatingtime+_heatingtime_ms/1000)*1900+
                  (_pumptime+_pumptime_ms/1000)*40+
                  (_airtime+_airtime_ms/1000)*800+
                  (_uptime+_uptime_ms/1000)*2+
                  (_jettime+_jettime_ms/1000)*400
                  )/3600000.0;

My config:
//uncomment your model and comment out the rest
//#define PRE2021			//the older one, no hydrojets
#define MIAMI2021		//no hydrojets
//#define MALDIVES2021	//hydrojets

The jettime has a strange value that it uses in the calculation{
    "CONTENT": "TIMES",
    "TIME": 1634290989,
    "CLTIME": 1634062564,
    "FTIME": 1634062566,
    "UPTIME": 183486,
    "PUMPTIME": 128,
    "HEATINGTIME": 14,
    "AIRTIME": 23,
    "JETTIME": 1986285,
    "COST": 44.16284,
    "FINT": 30,
    "CLINT": 7
}

**Comment by AlbertDijksma** [comment]
I haven't tested the new code yet, but have you also thought of the HJT bit?
This should be set to 0 in my situation.

{
    "CONTENT": "STATES",
    "LCK": 1,
    "PWR": 1,
    "UNT": 1,
    "AIR": 0,
    "GRN": 0,
    "RED": 0,
    "FLT": 1,
    "TGT": 38,
    "TMP": 16,
    "CH1": 32,
    "CH2": 49,
    "CH3": 54,
    "HJT": 1
}

**Comment by AlbertDijksma** [comment]
New software version is up and running.
Problem solved.
Case may be closed.
Thank you.

**Comment by visualapproach** [comment]
Nice! The 'strange' value was due to missing initialization of that variable. And some other. Hope it works now.
