### ISSUE TITLE
Failed to get time from server, retry

### ISSUE THREAD

**Issue by 877dev** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#14]
Am I the only one getting this error a lot of the time? Sometimes it connects first time, other times it takes forever.

Or I could just imagine I am back in 1st Jan 1970 in the Hot Tub Time Machine :)

![92101716-6e25a800-edd5-11ea-9700-7cc03c5817b7](https://user-images.githubusercontent.com/46575282/92108187-dc229d00-edde-11ea-8deb-c888d97344e5.png)

**Comment by 877dev** [comment]
Update, this may be a fix:
https://github.com/mcxiaoke/ESPDateTime/issues/7#issuecomment-686408433

`void setupDateTime() {
  // setup this after wifi connected
  // you can use custom timeZone,server and timeout
  // DateTime.setTimeZone(-4);
  //   DateTime.setServer("asia.pool.ntp.org");
  //   DateTime.begin(15 * 1000);
 
  DateTime.setServer("pool.ntp.org"); // ***add this line***
  
  DateTime.setTimeZone(TZ);            
  DateTime.begin();
  if (!DateTime.isTimeValid()) {
    Serial.println("Failed to get time from server.");
  }
}`

**Comment by visualapproach** [comment]
Good to know!

**Comment by engbryan** [comment]
The issue persists for me, even using the cloudflare ntp. Does anyone have a light on it?
