### ISSUE TITLE
PCB URL down

### ISSUE THREAD

**Issue by simontims** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#142]
oshwlab,com seems to be down! Are there alternative links to your PCB files, please?

**Comment by visualapproach** [comment]
Oh, I'll try to solve that tomorrow. Thx

**Comment by visualapproach** [comment]
Now there is another link that should work.

**Comment by simontims** [comment]
Great, thanks. Yes it does, boards ordered!
