### ISSUE TITLE
teaser next version

### ISSUE THREAD

**Issue by visualapproach** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#16]
Just wanted you to know that I'm working on a new version. Still lots of work to get it running. Here is some screenshots:
![idx](https://user-images.githubusercontent.com/22987250/92268623-03fb2900-eee3-11ea-9fd8-22299e5afaca.png)
![cfg](https://user-images.githubusercontent.com/22987250/92268320-70c1f380-eee2-11ea-802a-d093b7673d57.png)

**Comment by 877dev** [comment]
Nice, but I miss Frankenstein :)

**Comment by visualapproach** [comment]
V1.27 is up. Closing
