### ISSUE TITLE
Custom UI Implementation 

### ISSUE THREAD

**Issue by Jack06WS** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#17]
Hello. I've made a custom UI for the Lay Z Spa and I wan't to put it on my arduino device. I'm having trouble getting the buttons to actually work. Could the owner of this project DM me on discord? I think we can work something out. Jack06WS#1182.

Jack.

**Comment by visualapproach** [comment]
Hello @Jack06WS 
Is there a reason we can't discuss it here?

Cheers

**Comment by Jack06WS** [comment]
I’d like to share some of my code and I’d rather it be private.

Jack

**Comment by visualapproach** [comment]
You can reach me on info at visualapproach .  se

**Comment by Jack06WS** [comment]
Ok, I will do. Thanks!
