### ISSUE TITLE
v1.27 LittleFS info - Failed to open config file (load)

### ISSUE THREAD

**Issue by 877dev** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#19]
Morning,

Had a quick try of this, but getting an error. I flashed sketch then uploaded sketch data. Maybe something I am doing?

![image](https://user-images.githubusercontent.com/46575282/92461093-b58aaa80-f1c0-11ea-8861-08f7e75bb217.png)

**Comment by visualapproach** [comment]
Nothing wrong. You have to save config first. Then restart and you shouldn’t get that error. Appdata will be saved after 24h

**Comment by 877dev** [comment]
I'm getting 404 File not found error on web page too.

**Comment by visualapproach** [comment]
Webpage should work anyway I think.

**Comment by faboaic** [comment]
Maybe the transition from SPIFFS to LittleFS killed all files and you did not upload the files to LittleFS after the update?

**Comment by 877dev** [comment]
I used this to upload, same a SPIFFs. Maybe wrong?
![image](https://user-images.githubusercontent.com/46575282/92463421-b40eb180-f1c3-11ea-94f9-0321f6babd43.png)

**Comment by 877dev** [comment]
Yup I needed to install this:
https://github.com/earlephilhower/arduino-esp8266littlefs-plugin#:~:text=Go%20to%20sketch%20directory%20(choose,in%20the%20file%20system%20there.&text=Select%20Tools%20%3E%20ESP8266%20LittleFS%20Data,into%20ESP8266%20flash%20file%20system.

Working now thank you :)

**Comment by visualapproach** [comment]
Yes that’s your problem. You need to download littlefs tool. Then you will have a new option “upload littlefs data” or similar. Sorry, I think I wrote about it on readme but I could’ve been clearer.

**Comment by 877dev** [comment]
Readme's are for wimps! :)

**Comment by visualapproach** [comment]
Ok great 🎉

**Comment by visualapproach** [comment]
patch 1 uploaded. Hope it's more stable. Had a couple of reboots, probably caused by calling yield() from other functions than loop()
