### ISSUE TITLE
Access Point Password?

### ISSUE THREAD

**Issue by theandydove** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#198]
Hello,
Firstly thanks for all the effort thats gone into this project.

I have uploaded to the node mcu, but when i search wifi I only access point I get is Lay-z-spa module, which requires a password. Google and search bar has failed me on this one!

Oh its a 4 wire version if that makes a difference.

**Comment by visualapproach** [comment]
Hi! Take a look in the "config.h" file for the answer ;)

**Comment by theandydove** [comment]
Thank you very much.
