### ISSUE TITLE
6 wire Palm Springs 

### ISSUE THREAD

**Issue by Chamberlainpac** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#209]
Thanks for this amazing site . I’m a complete noob but still  managed to build my first ever wifi unit thanks to your amazing installation instructions. And learnt how to code and set up the AP. My issue is I have a 6 wire palm spring unit. I’ve plug it in and no response - won’t even power on. I suspect it’s the wiring.  How do I figure out which of the 6 wires is which ?  Which one is 5+ , ground ? Etc ?  Any Help much appreciate. 

![62E3AA3C-8ED1-4D98-A594-46ACC21CDF27](https://user-images.githubusercontent.com/87044780/152607892-697f9835-1f83-4f22-8c27-2d732ccb974f.jpeg)
![4C2C7D85-73C9-402A-8FA3-459186FD9C82](https://user-images.githubusercontent.com/87044780/152607904-670f022e-f5cb-48a8-a91b-1846a5b275c3.jpeg)
![CAE8296A-C0E1-4C8D-9606-DB12C22CFD1C](https://user-images.githubusercontent.com/87044780/152607922-2720e4dd-a1d1-43f6-a250-9943382c3268.jpeg)
![922E8213-A702-4E24-8D05-30235838FFF0](https://user-images.githubusercontent.com/87044780/152607865-14e5feb5-bcb7-4d5a-a9d0-108e5456b7be.jpeg)

**Comment by visualapproach** [comment]
Thank you @Chamberlainpac  for your kind words!
What's your model number? It's on the sticker on the egg.

**Comment by Chamberlainpac** [comment]
Hi vis. It’s the #54129 
![Uploading 874FE5DA-68A1-4704-A464-4C5579E73AC0.jpeg…]()

**Comment by Chamberlainpac** [comment]
![D973C0E2-7D97-4899-B96A-DBC302971F56](https://user-images.githubusercontent.com/87044780/152642472-6b3f4762-363b-4463-8a1b-4d13aa13c2e8.jpeg)

**Comment by Chamberlainpac** [comment]
![C22FEF14-53C5-40C5-86E7-F44F0AB37B38](https://user-images.githubusercontent.com/87044780/152642515-756af812-235d-4ac6-b1a1-b22b5c5d5d67.jpeg)

**Comment by Chamberlainpac** [comment]
![image](https://user-images.githubusercontent.com/87044780/152642564-c1fdd704-bde5-4050-9964-c604e1d82ff6.jpg)

**Comment by visualapproach** [comment]
Great, look's alright to me. To check which pin is which, you need a multimeter but you can only see +5V and GND with those. The other pins will switch rapidly between 0 and 5 V and will show something in between on a dmm.
But if the blue LED turns on or blinks you at least have the power pins right. Do you get to the esp WiFi web page?

**Comment by Chamberlainpac** [comment]
No power . No web page. I checked the volts. It’s wired backwards . The awg is ground .. the - - - - is 5v .  I’ll re solder the connections and give it a try.

**Comment by Chamberlainpac** [comment]
Ok we now have Power on the esp. we have blinking blue light and I can see the esp webpage . But no display on the egg. I can hear the display clicking ?

**Comment by visualapproach** [comment]
did you also rewire the cable to display?

**Comment by visualapproach** [comment]
If you rewired the ESP to CIO by rotating it 180 degrees. I mean from 123456 to 654321 you should do the same on the display cable. Otherwise you feed 5V into the speaker which I guess is what you hear.

**Comment by Chamberlainpac** [comment]
Ok… I’ve reversed wires on output side too . Have flashing blue light . Melody plays and I can see the esp page . Display on the egg is still off and unresponsive.  
![image](https://user-images.githubusercontent.com/87044780/152691241-50fd8513-1ae3-4fbd-b49c-f1074b480620.jpg).

**Comment by visualapproach** [comment]
Okay, maybe you have one of those pumps that needs resistors on the data outputs. On the DSP Clk, data and cs lines try putting a 500-ish Ohms resistor in series. 
LLC-R1----wire to dsp
LLC-R2----wire to dsp
LLC-R3----wire to dsp

**Comment by Chamberlainpac** [comment]
Ok.. I’ll order some and let you know.

**Comment by Chamberlainpac** [comment]
Hi vis, unfortunately that didn’t work.   Still nothing on the display. 
![Uploading E6145A8F-DACB-4207-819C-03A5CBBD1634.jpeg…]()

**Comment by visualapproach** [comment]
Hi, are you able to control the pump from web gui? Like turning on the bubbles.

**Comment by Chamberlainpac** [comment]
Yes, the blue light flashes, music is played.  The gui is fully working . Correct temp, bubbles work. Just no display at all ? 
![49AA2A08-8111-464A-9180-9B63DA58DD22](https://user-images.githubusercontent.com/87044780/153770650-7ccdff4f-7542-46ea-82d8-971e6a0128d2.jpeg)
![00D218A9-F8D6-4186-956E-FD5AFB227A62](https://user-images.githubusercontent.com/87044780/153770653-02a9f9c6-1112-46a8-a0ce-fd995a144fda.jpeg)

**Comment by Chamberlainpac** [comment]
I changed the LLC plus added the 10k resistor just to be surely  Still no display and now I’m not seeing the temp on the web page or able to control the pump.    Still got blue light and music and webpage opens.   Before changing the llc I checked all solders and wires and all ok.

**Comment by visualapproach** [comment]
I'm busy a while but will call you back. Isn't it strange that the webpage temp stopped working just because you switched LLC?

**Comment by Chamberlainpac** [comment]
It wasn’t easy to unsolder and take out  the llc so may have damaged or dislodge something else in the process?  I will check continuity to be sure. I’m happy to test it using the multimeter to let you know what it’s doing when live ?  

Regards 
Paul

**Comment by Chamberlainpac** [comment]
I decided to build a new one.. and it’s now working perfectly. Thanks again for all your help , code and time.  I will now close this thread.
