### ISSUE TITLE
Newer non-egg shaped controllers?

### ISSUE THREAD

**Issue by eried** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#216]
Hi, I just ordered a laz-y spa and I intend to built this project but I see the controller does not look the same. Does anyone knows if is the same internally?

![image](https://user-images.githubusercontent.com/1091420/156597735-65496b0e-e697-4392-8417-04ea4975151c.png)

**Comment by chunkysteveo** [comment]
Think you need to follow the 2021 model guidelines...

**Comment by eried** [comment]
cool! I will check when the unit arrives :) and report back
