### ISSUE TITLE
v1.27: uptime does not show uptime but time since last FW flash or storage clean

### ISSUE THREAD

**Issue by faboaic** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#22]
After rebooting the ESP8266 the uptime does not get reset.
Might be helpful to see how long it is up, especially if unexpected reboot happened.

**Comment by visualapproach** [comment]
Actually that’s the intended behavior. Misused term “uptime” perhaps. I saw it from the pump perspective to be compared with heating time etc. maybe “accumulated uptime” would be better word. If you want to see last reboot time go to up/tmp.txt
It says appdata log but I’ll change that.

**Comment by visualapproach** [comment]
changed text on webpage. Open new issue if not satisfied
