### ISSUE TITLE
54183 show ip-adress - fail at startup

### ISSUE THREAD

**Issue by dietmar-1** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#223]
At my 54183 the display of the ip address during the startup is wrong. Incomplete numbers are displayed. The status LEDs light up uncoordinated. I found out that it must be due to missing information in the payload. I have adjusted the lines from 284 in the BWC_8266.cpp. everything works now. ! I don't know exactly where the information is lost, but it works :man_shrugging:. 

```c#

270 void DSP::updateDSP(uint8_t brightness) {
.
.
.
284      //payload
285
286      // fill payload (refer to bwc_docs.xlsx)
287      payload[0] = 0xC0;
288      payload[2] = 0xFE;
289      payload[4] = 0xFE;
290      payload[6] = 0xFE;
291      payload[8] = 0xFE;
292      payload[10] = 0xFF;
.
.
.

```

**Comment by visualapproach** [comment]
That was a previous bug. Should be fixed in dev branch...
