### ISSUE TITLE
upload errors for 3.1.1 in VS

### ISSUE THREAD

**Issue by chunkysteveo** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#227]
Hey all,
Just downloaded the latest release and went to upload OTA the new version and VS is kicking up a bunch of errors about serial:

Here's the terminal output when I go to upload via OTA:

> Executing task: C:\Users\stephen\.platformio\penv\Scripts\platformio.exe run --target upload <

Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (2.6.3) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.20704.0 (2.7.4)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - tool-mklittlefs 1.203.210628 (2.3)
 - tool-mkspiffs 1.200.0 (2.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 36 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.18.5
|-- <ESPDateTime> 0.2.1
|-- <WebSockets> 2.3.6
|   |-- <ESP8266WiFi> 1.0
|   |-- <Ethernet(esp8266)> 1.0.4
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|-- <PubSubClient> 2.8.0
|-- <WiFiManager> 0.16.0
|   |-- <DNSServer> 1.1.1
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <EspSoftwareSerial> 6.15.2
|-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <BWC4W>
|   |-- <ArduinoJson> 6.18.5
|   |-- <ESPDateTime> 0.2.1
|   |-- <LittleFS(esp8266)> 0.1.0
|   |-- <EspSoftwareSerial> 6.15.2
|   |-- <Ticker> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <LittleFS(esp8266)> 0.1.0
|-- <Ticker> 1.0
Building in release mode
Compiling .pio\build\nodemcuv2\src\main.cpp.o
Compiling .pio\build\nodemcuv2\lib066\EspSoftwareSerial\SoftwareSerial.cpp.o
Compiling .pio\build\nodemcuv2\lib44d\BWC4W\BWC_8266_4w.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\MD5Builder.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Print.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\Schedule.cpp.o
Compiling .pio\build\nodemcuv2\FrameworkArduino\StackThunk.cpp.o
In file included from .pio\libdeps\nodemcuv2\EspSoftwareSerial\src\SoftwareSerial.cpp:23:0:
.pio\libdeps\nodemcuv2\EspSoftwareSerial\src\SoftwareSerial.h:134:9: error: 'int SoftwareSerial::availableForWrite()' marked override, but does not override
     int availableForWrite() override {
         ^
.pio\libdeps\nodemcuv2\EspSoftwareSerial\src\SoftwareSerial.h:161:9: error: 'int SoftwareSerial::read(uint8_t*, size_t)' marked override, but does not override
     int read(uint8_t* buffer, size_t size)
         ^
*** [.pio\build\nodemcuv2\lib066\EspSoftwareSerial\SoftwareSerial.cpp.o] Error 1
In file included from lib\BWC4W/BWC_8266_4w.h:20:0,
                 from src\main.h:3,
                 from src\main.cpp:1:
.pio\libdeps\nodemcuv2\EspSoftwareSerial\src/SoftwareSerial.h:134:9: error: 'int SoftwareSerial::availableForWrite()' marked override, but does not override
     int availableForWrite() override {
         ^
.pio\libdeps\nodemcuv2\EspSoftwareSerial\src/SoftwareSerial.h:161:9: error: 'int SoftwareSerial::read(uint8_t*, size_t)' marked override, but does not override
     int read(uint8_t* buffer, size_t size)
         ^
In file included from lib\BWC4W\BWC_8266_4w.h:20:0,
                 from lib\BWC4W\BWC_8266_4w.cpp:1:
.pio\libdeps\nodemcuv2\EspSoftwareSerial\src/SoftwareSerial.h:134:9: error: 'int SoftwareSerial::availableForWrite()' marked override, but does not override
     int availableForWrite() override {
         ^
.pio\libdeps\nodemcuv2\EspSoftwareSerial\src/SoftwareSerial.h:161:9: error: 'int SoftwareSerial::read(uint8_t*, size_t)' marked override, but does not override
     int read(uint8_t* buffer, size_t size)
         ^
*** [.pio\build\nodemcuv2\src\main.cpp.o] Error 1
*** [.pio\build\nodemcuv2\lib44d\BWC4W\BWC_8266_4w.cpp.o] Error 1
==================================================== [FAILED] Took 7.26 seconds ====================================================
The terminal process "C:\Users\stephen\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

Any ideas on what has caused this?

**Comment by visualapproach** [comment]
Try cleaning build
