### ISSUE TITLE
MQTT command doesn't work

### ISSUE THREAD

**Issue by e-i-k-e** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#235]
Hi there,
Unfortunately I can't manage to send MQTT commands to the .. or the device doesn't receive anything.

MQTT runs in my ioBroker (without access data) I also receive data.
![image](https://user-images.githubusercontent.com/83473829/159787751-6bb12dc5-da62-4781-b87b-00bc87f96f08.png)

However, the orders do not arrive or go out.
What can i do?

Command: {"CMD":"4","VALUE":"true","XTIME":"0","INTERVAL":"0" or {"CMD":"4","VALUE":"1","XTIME":"0","INTERVAL":"0"

![image](https://user-images.githubusercontent.com/83473829/159787826-1a56e0b4-6068-4ebc-a610-1dbd85407d2a.png)
![image](https://user-images.githubusercontent.com/83473829/159787859-d61ef342-f2e1-48d9-9bf9-0ba2128ab7bb.png)
![image](https://user-images.githubusercontent.com/83473829/159787912-f9e1bb7f-1b08-4466-beda-af3d176696df.png)
![image](https://user-images.githubusercontent.com/83473829/159787966-b9fa175d-5a44-4f99-b271-1e9c86a154b5.png)

**Comment by visualapproach** [comment]
Do you miss the closing curly bracket?
{"CMD":"4","VALUE":"true","XTIME":"0","INTERVAL":"0"
should be
{"CMD":"4","VALUE":"true","XTIME":"0","INTERVAL":"0"}

**Comment by e-i-k-e** [comment]
> Do you miss the closing curly bracket? {"CMD":"4","VALUE":"true","XTIME":"0","INTERVAL":"0" should be {"CMD":"4","VALUE":"true","XTIME":"0","INTERVAL":"0"}

Excuse me. This was now a copy error. The bracket is of course otherwise present.

**Comment by visualapproach** [comment]
try without citationmarks around the values:
{"CMD":12,"VALUE":3,"XTIME":1648149567,"INTERVAL":0}

**Comment by e-i-k-e** [comment]
> try without citationmarks around the values: {"CMD":12,"VALUE":3,"XTIME":1648149567,"INTERVAL":0}

Unfortunately it doesn't work either. :/

**Comment by visualapproach** [comment]
In your first picture the connect count says 105. It should ideally only read 1. Check serial output from the ESP in a monitor and you'll probably see it has to reconnect all the time. The MQTT code is working, so it must be something in your setup.
What's the RSSI?

**Comment by e-i-k-e** [comment]
I deleted the data points in ioBroker, installed a WiFi repeater nearby and reestablished the connection.
Now it works. Thanks!
