### ISSUE TITLE
Web interface via Nginx Proxy - mixed protocols

### ISSUE THREAD

**Issue by jgibbarduk** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#239]
Description: 
When running the web interface behind an nginx-proxy using SSL, the web interface displays, but is not able to show any data or settings. This is due to the data being read using web-scokets that do not get redirected over secure web-sockets.

Branch: master

Steps to reproduce:
1. Install and get the Spa Controller interface working over HTTP (everything works great)
2. Use a nginx-proxy to add SSL security for the web interface.
3. Nginx proxy redirects traffic to the HTTP server successfully
4. Open HTTPS address using Google Chrome

Expected Outcome:
The web interface works as normal when being accessed over HTTPS.

Actual Outcome:
The web interface loads, but shows no data or spa controls (just the HTML) [see screenshot].
<img width="961" alt="Screenshot 2022-03-26 at 13 23 33" src="https://user-images.githubusercontent.com/6859664/160241637-babd50f8-dbf9-4fae-93c0-5a907ed4fff0.png">

Error Log (from Chrome):

> WebSocket.js:41 Mixed Content: The page at 'https://abc.xyz.net/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://abc.xyz.net:81/'. This request has been blocked; this endpoint must be available over WSS.
> connect @ WebSocket.js:41

> WebSocket.js:41 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
>     at connect (https://abc.xyz.net/WebSocket.js:41:15)
>     at https://abc.xyz.net/WebSocket.js:37:1

**Comment by visualapproach** [comment]
I don't know if there is a solution to that, other than switching to secure websockets on the poor ESP8266 or changing strategy. From what I've read, secure transfers is rather demanding for this MCU. What's the use case here? If you have a smart hub, maybe you can use the MQTT instead. Or connect to your local network through a VPN. I appreciate your effort in a clear problem description!

**Comment by jdierkse** [comment]
This can be done in your NGINX configuration, but it requires gunzip, as the firmware sends all data using gzip.
Check out the following configuration snippets for a lead:

    server {
        listen 8080;
        server_name gunzip.jacuzzi.example.com;

        location / {
            gunzip on;

            set $backend "http://layzspa.local";
            proxy_pass $backend;
        }
    }

    server {
        listen 443 ssl;
        listen [::]:443 ssl;

        server_name jacuzzi.example.com;

        location / {
            proxy_set_header Accept-Encoding "";
            proxy_pass http://127.0.0.1:8080;

            sub_filter_types application/javascript;
            sub_filter "ws:" "wss:";
            sub_filter ":81/" "/websocket";
            sub_filter_once off;
        }

        location /websocket {
            set $backend "http://layzspa.local:81";
            proxy_pass $backend;
        }
    }

This forces a gunzip by asking NGINX itself for the page with an empty "Accept-Encoding" directive.
Afterwards, the content of the javascript file can be modified such that the websocket is served over https (wss) as well.
This should more or less work (the config is not complete, but this should point you in the right direction)
