### ISSUE TITLE
PCB?

### ISSUE THREAD

**Issue by Naesstrom** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#24]
I was working on a pcb mount for this but I'm not sure about one thing. Shouldn't Pin6 on the CIO be connected to something to?

You can see the PCB here: https://easyeda.com/Naesstrom/lay-z-spa_remote
![image](https://user-images.githubusercontent.com/6575206/92893139-b8cca300-f419-11ea-840a-0746f4c58bbd.png)

**Comment by visualapproach** [comment]
Hi @Naesstrom , Pin 6 is just outgoing sound. Which is not presently used in code. We are making our own sound.

**Comment by Naesstrom** [comment]
Sweet thanks, then I'll order some PCB's
Or are there any changes coming up before I get them etched? I saw some discussion about adding extra pins for various things

**Comment by visualapproach** [comment]
No immediate changes in progress regarding extra pins, but why not make a couple of traces from D0, D8 and GND to through holes somewhere on the PCB.

**Comment by Naesstrom** [comment]
Great idea!
![image](https://user-images.githubusercontent.com/6575206/92908087-33032480-f426-11ea-9963-94d033ca4dd7.png)

**Comment by carverhaines** [comment]
Make sure the dsp and cio have enough room around them to plug in, the plastic around the plugs takes a bit of room.

**Comment by carverhaines** [comment]
Sorry, just realized you may be planning on using a cable, I am using these currently soldered into my pcb so I can plug in directly.

![Screenshot_20200911-071258__01](https://user-images.githubusercontent.com/5835343/92924419-895c6d00-f3fe-11ea-93d0-697d3665155f.jpg)

**Comment by Naesstrom** [comment]
> Sorry, just realized you may be planning on using a cable, I am using these currently soldered into my pcb so I can plug in directly.
> 
> ![Screenshot_20200911-071258__01](https://user-images.githubusercontent.com/5835343/92924419-895c6d00-f3fe-11ea-93d0-697d3665155f.jpg)

Ohh, do they fit straight into the JST connectors?

I bought a [set of male/female connectors](https://thepihut.com/products/6-pin-jst-sm-plug-receptacle-cable-set) with cables this time since I couldn't find JST-SM connectors as PCB mounted?
http://www.jst-mfg.com/product/pdf/eng/eSM.pdf

**Comment by carverhaines** [comment]
Yes, it does, that's how I have it setup

**Comment by Naesstrom** [comment]
Oh thats nice, I moved them over a bit now, do you think your kind of connectors would fit the design now?
![image](https://user-images.githubusercontent.com/6575206/92935800-95215100-f449-11ea-8884-f353932eeaf9.png)

**Comment by carverhaines** [comment]
It won't lock into place like the connectors, but is a tight enough fit I'm not worried

**Comment by carverhaines** [comment]
Should work. Any chance you can make a second design that uses two 4 I/O LVCs for those of us that can't get ahold of that specific LVC (just needs 2 3v inputs, 2 HV inputs, and 4 gnd) 
![IMG_20200820_183908](https://user-images.githubusercontent.com/5835343/92936657-f9bfba00-f40f-11ea-87c7-b8b6a071f7dc.jpg)

**Comment by Naesstrom** [comment]
Absolutely, does this look right?
![image](https://user-images.githubusercontent.com/6575206/92943866-95bee500-f453-11ea-8656-0e74cd6365f8.png)

You can check the schematics at https://easyeda.com/Naesstrom/lay-z-spa_remote to, and edit and download gerbers for production!

**Comment by 877dev** [comment]
Very nice @Naesstrom , thanks for sharing. I might adapt them for Wemos D1 mini.

One thing, the resistors are showing as 10K where they should be around 0.5-1K according to readme.

**Comment by carverhaines** [comment]
@Naesstrom , that looks perfect! I can't wait to print one.
@visualapproach , these 2 schematics should be included in the repo for anyone wanting to print their PCBs

**Comment by carverhaines** [comment]
Just put in my order to PCBway!

**Comment by Naesstrom** [comment]
> Very nice @Naesstrom , thanks for sharing. I might adapt them for Wemos D1 mini.
> 
> One thing, the resistors are showing as 10K where they should be around 0.5-1K according to readme.

I started doing it for a d1 actually but became unsure if I could feed it with 12V as I guess the VIN/HV side is getting here!
Bloody hell, my bad with the resistors. Changing them now 👍 

> Just put in my order to PCBway!
Nice, I'll order mine this weekend to!

**Comment by visualapproach** [comment]
I put the link in readme, thank you.
