### ISSUE TITLE
Compiling and upload problems

### ISSUE THREAD

**Issue by NitramH** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#242]
I have some warnings with the d1_mini as follows, even if it states "successful".
Can I ingnore the following (pls see below)?

________________________________________________________________________________________________________________________________________
Compiling .pio\build\d1_mini\lib241\WiFiManager\WiFiManager.cpp.o
.pio\libdeps\d1_mini\WebSockets\src\WebSocketsServer.cpp: In member function 'WSclient_t* WebSocketsServerCore::handleNewClient(WiFiClient*)':
.pio\libdeps\d1_mini\WebSockets\src\WebSocketsServer.cpp:634:12: warning: function may return address of local variable [-Wreturn-local-addr]
  634 |     return client;
      |            ^~~~~~
.pio\libdeps\d1_mini\WebSockets\src\WebSocketsServer.cpp:626:20: note: declared here
  626 |         WSclient_t dummy = WSclient_t();
      |                    ^~~~~
Archiving .pio\build\d1_mini\libebb\libWebSockets.a
Compiling .pio\build\d1_mini\lib4d5\LittleFS\LittleFS.cpp.o
.pio\libdeps\d1_mini\PubSubClient\src\PubSubClient.cpp: In member function 'boolean PubSubClient::publish_P(const char*, const uint8_t*, unsigned int, boolean)':
.pio\libdeps\d1_mini\PubSubClient\src\PubSubClient.cpp:523:16: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  523 |     return (rc == expectedLength);
      |             ~~~^~~~~~~~~~~~~~~~~
________________________________________________________________________________________________________________________________________

**Comment by visualapproach** [comment]
Hi,
It's just warnings so I think it can be ignored. The first two was introduced in those libraries recently. Didn't get them before.
/Visualapproach
