### ISSUE TITLE
Temperature Control goes crazy (3.2.0, using Homeassistant)

### ISSUE THREAD

**Issue by NitramH** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#243]
Hi,

if I change the setpoint for the climate object in homeassistant to a new value it is normally updating it correctly.
For that purpase I use the slider in the homeassistant view.

But recently I did not matched my preferred value, so I need to adjust it 2-3 times a little bit.
During adjustment several "intermediate" setpoints were taken over as new setpoints
while the layzspa control still was in updating process to the first setpoint.
Finally the control goes crazy by moving around the new setpoint near to the last selected one.
And it did not stabilzed after a while. Can someone please propose a solution for an update lock inside HA
until the setpoint was successfully taken over?

Cheers,
Martin

**Comment by visualapproach** [comment]
Hi, that can happen if you, as you described, set a new target before the first target has "settled". It should preferably be solved in the ESP, but until that happens you can usually set the target again and it should stabilise.
