### ISSUE TITLE
Compiling/Running on a Wemos D1 mini

### ISSUE THREAD

**Issue by creativtransfer** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#244]
For whom it may concern:
I am not able to make the last release v3.2.0 (configured miami2021) work on a Wemos D1 mini. 
It compiles and uploads but there is no AP.
The previous release v3.1.1 works just fine.

**Comment by visualapproach** [comment]
Dev or master branch? Try dev if you haven't

**Comment by creativtransfer** [comment]
I used the (master) release from the right sidebar. 
I just downloaded and compiled the development Branch and it works fine.
Thank you!
PS: Can you add the Version information to the homepage - maybe at the bottom below or above the mqtt status?

**Comment by visualapproach** [comment]
Good. Actually the master is also working but it needs to be connected to the pump.
Ps I hear you

**Comment by creativtransfer** [comment]
Ok, thank you!
