### ISSUE TITLE
Few suggestions and discussion about features

### ISSUE THREAD

**Issue by eried** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#260]
Hey! me again, as I said before, thanks for the firmware, it is fantastic to use the spa with home assistant! specially with the scheduler component. I have some few questions and suggestions. I havent understood fully the code but I want to try to implement improvements (and as I said, eventually try to make things run in a esp32):

- [x] brightness set/get should be exposed via mqtt (i.e. depending on the hour, change how annoying is the screen)
- [x] temperature should be exposed in 2 channels (one for F and C), unit change can mess the graphs
- [x] the system should implement a virtual temperature, with a linear decay (i.e. setting for decreasing temperature per minute) instead of relaying on the sensor (update the virtual temperature when the pump runs ofc)
- [x] the time to ready should consider that virtual temperature instead, and have a setting for how much the temp increases when the heater is on
- [ ] remove things from the web ui, the scheduled actions for example (does anyone uses those?)
- [x] can the current "live" consumption be exposed vias mqtt too? for the energy panel in home assistant
- [x] thermostat "off" should actually turn off the pump, or maybe have another button for pump

Some questions:
- [x] can the screen be completelly off?
- [ ] is the real display control a little more laggy sometimes? is it because the esp is locked in some operations?

**Comment by chunkysteveo** [comment]
> * can the current "live" consumption be exposed vias mqtt too? for the energy panel in home assistant

The Spa energy is already exposed in the MQTT and can be tracked in HA Energy Dashboard.

**Comment by eried** [comment]
> or do you mean the actual real time wattage/power

yes, since the accumulated one is less useful to have, or maybe I am wrong? having the live will make it possible to plot it easily against your house meter readings

**Comment by eried** [comment]
OK, so it should be added as individual device?
![image](https://user-images.githubusercontent.com/1091420/167118776-7e0b22f5-0eb0-4a41-a216-3ed7ad47e4aa.png)

Either way since the mqtt is reporting buttons and other states I thought it would be good to add the "live consumption" to the possible discussion. I would actually think that dropping the whole WebUI could be beneficial to the project, just have the mqtt settings in the wifimanager portal

**Comment by visualapproach** [comment]
> Hey! me again, as I said before, thanks for the firmware, it is fantastic to use the spa with home assistant! specially with the scheduler component. I have some few questions and suggestions. I havent understood fully the code but I want to try to implement improvements (and as I said, eventually try to make things run in a esp32):
> 
> * [ ]  brightness set/get should be exposed via mqtt (i.e. depending on the hour, change how annoying is the screen)

Yes I agree.
> * [ ]  temperature should be exposed in 2 channels (one for F and C), unit change can mess the graphs

hmm, good idea. Have to think it through
> * [ ]  the system should implement a virtual temperature, with a linear decay (i.e. setting for decreasing temperature per minute) instead of relaying on the sensor (update the virtual temperature when the pump runs ofc)
> * [ ]  the time to ready should consider that virtual temperature instead, and have a setting for how much the temp increases when the heater is on

I considered that, but it's kind of impossible to get it right anyway. For instance, the temperature rise per hour is not linear, but a curve. It takes more time from 38 to 39 degrees than from 20 to 21. And there is a lot of variables at play, like outside temperature, insulation, mains voltage etc. Now, it could be a good option for when the pump is off as you say. Let me think about it.
> * [ ]  remove things from the web ui, the scheduled actions for example (does anyone uses those?)

No, not everyone has a smart home. I don't see the point in removing functionality unless it causes bad things which I don't think this does. Just don't use it if you don't want to. Or am I not getting something here?
> * [ ]  can the current "live" consumption be exposed vias mqtt too? for the energy panel in home assistant

Yes it can but it doesn't. It's not needed for the energy panel but maybe for something else.
> * [ ]  thermostat "off" should actually turn off the pump, or maybe have another button for pump

Having the pump in the office not connected to any water, I haven't tested the HA climate control fully yet. But it would be a great option. Could be done in HA. I did that last summer to increase the pump lifetime.
> 
> Some questions:
> 
> * [ ]  can the screen be completelly off?

Yes but it would require special handling in the code. There is an ON bit somewhere.
> * [ ]  is the real display control a little more laggy sometimes? is it because the esp is locked in some operations?

I'd rather get rid of the physical display than the web ui ;-) Who uses it anyway? Jokes aside, there is a slight delay since we process the buttons before sending to the CIO but it should be about 50 ms. Slightly more when saving stuff to files, or serving web pages. And also, if there is buttons in the button queue (to do scheduled stuff) it will ignore your fingers :-)

**Comment by eried** [comment]
I tested the temperature thing and it is very lineal, every user should

> Yes I agree.

Cool! I tried yesterday but there is a lot to digest having HA and this as new stuff, so I didn't managed to find the brightness. I will try to hack something simpler first



> hmm, good idea. Have to think it through

Maybe 2 additional channels even, that dont break up anything for legacy stuff, I guess is not a big overload



> I considered that, but it's kind of impossible to get it right anyway

True but it is very lineal. It would require settings because the size, cover and floor isolation will change stuff. And every time the pump runs it will get corrected. But now, you can have 28C while the water inside is 36C if the pump has not ran 4 hrs



> Or am I not getting something here?

Actually you are right, I mean it was just to remove the time, without scheduler you actually dont need datetime, nor other files so the whole system gets simplified. But maybe someone uses the webui, you need to inject some evil user tracking 😵

**Comment by Xamude** [comment]
>  temperature should be exposed in 2 channels (one for F and C), unit change can mess the graphs
>>hmm, good idea. Have to think it through

is it possible to add a feature that change F/C only in the WebIf and block the F/C Button on the Display to the Pump?
So it would be possible  to use the F/C Button on the Display to trigger Events over MQTT.
I think no one use this button after the first start :D

**Comment by visualapproach** [comment]
Blocking the buttons is already implemented by changing the array of enabled buttons. Making the web ui local is possible but not implemented

**Comment by eried** [comment]
> I think no one use this button after the first start :D

That button could show the filter age in days 😹 and reset it if is held.

**Comment by Xamude** [comment]
> Blocking the buttons is already implemented by changing the array of enabled buttons. Making the web ui local is possible but not implemented

I see it in an discussion post.
Can you tell me where i have to change it? 
Sorry im not good at coding 🙈

**Comment by visualapproach** [comment]
> > Blocking the buttons is already implemented by changing the array of enabled buttons. Making the web ui local is possible but not implemented
> 
> I see it in an discussion post. Can you tell me where i have to change it? Sorry im not good at coding 🙈

Code/6-wire-version/lib/BWC/BWC_8266_globals.h line 71

**Comment by Xamude** [comment]
> > > Blocking the buttons is already implemented by changing the array of enabled buttons. Making the web ui local is possible but not implemented
> > 
> > 
> > I see it in an discussion post. Can you tell me where i have to change it? Sorry im not good at coding 🙈
> 
> Code/6-wire-version/lib/BWC/BWC_8266_globals.h line 71

ah now i know i did´t see it, i have a 4 Wire Maldives (Model:54173) 
Nothing testet yet, waiting for the board to arrive.

Is the feature also implemented in 4 Wire ? 
do not see it in a quick overview

**Comment by visualapproach** [comment]
> > > > Blocking the buttons is already implemented by changing the array of enabled buttons. Making the web ui local is possible but not implemented
> 
> > > 
> 
> > > 
> 
> > > I see it in an discussion post. Can you tell me where i have to change it? Sorry im not good at coding 🙈
> 
> > 
> 
> > Code/6-wire-version/lib/BWC/BWC_8266_globals.h line 71
> 
> 
> 
> ah now i know i did´t see it, i have a 4 Wire Maldives (Model:54173) 
> 
> Nothing testet yet, waiting for the board to arrive.
> 
> 
> 
> Is the feature also implemented in 4 Wire ? 
> 
> do not see it in a quick overview   

No there is no way to do that unfortunately.

**Comment by eried** [comment]
![Screenshot_2022-05-17-10-17-34-636_io homeassistant companion android](https://user-images.githubusercontent.com/1091420/168764732-de2af122-7384-4090-84e2-3d3b607f2f47.jpg)

Here is how the temp looks, no matter how the weather is, I think the weather (wind) affect mostly the pump water when the pump is not working. What a virtual temperature can do is to use ratio_per_hour for the cooling (in my example, the water is almost always 33-35 during those 10 mins intervals of heating in the night)

**Comment by visualapproach** [comment]
Thanks, Yes in a small interval the curve is linear, but compare the slope around 35 with the slope around 25 and it's different. It's not impossible to do what you ask but for the moment there is other stuff I'm working on which I consider more important. But it's on the todo-list. Some of your bullets above is checked in dev version. Like display off. And partly brightness over mqtt. You can set it but I'm not sure you (Ha) get it yet.

**Comment by Jay-Ti** [comment]
> Here is how the temp looks, no matter how the weather is, I think the weather (wind) affect mostly the pump water when the pump is not working. What a virtual temperature can do is to use ratio_per_hour for the cooling (in my example, the water is almost always 33-35 during those 10 mins intervals of heating in the night)

Getting the Curve for a predictive Heating is by far easier than getting a predictive cooling curve. 
For predictive heating, you basically just need to heat when it's cold once and heat when it's warm once, and you can extrapolate a curve that is "good enough".(I feel like the examples given in the Spa Handbook is not representative of reality, but don't have enough data myself).

For cooling, you need to access weather information to find the lowest possible temperature/ median Temperature. Or one would just say anything below 25 Degrees Celsius is unimportant, and then you can use a linear curve, which is good enough.
