### ISSUE TITLE
Random flashing display - Lazyspa Helsinki 2021

### ISSUE THREAD

**Issue by 9khil** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#263]
I just fitted the pcb to my 2021 (S100101) unit using miami2021 model. can control using portal and home assistant, but display and button lights on the pump are  flashing randomly.

tried three 510ohm resistors without any luck. 

Video and debug log:

Video: https://youtube.com/shorts/WvYKLvA7Ow8?feature=share

4-5 seconds of debug log, no interaction with spa through web or directly on the unit:

```
{"CONTENT":"STATES","TIME":1652072230,"LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":1,"RED":0,"FLT":1,"TGT":36,"TMP":36,"CH1":32,"CH2":51,"CH3":54,"HJT":0,"BRT":7}
debug.html:45 {"CONTENT":"TIMES","TIME":1652072230,"CLTIME":1652017886,"FTIME":1652017884,"UPTIME":45826,"PUMPTIME":45770,"HEATINGTIME":12495,"AIRTIME":8,"JETTIME":12595,"COST":8.529820442,"FINT":30,"CLINT":14,"KWH":8.529820442,"TTTT":-7731,"MINCLK":8}
debug.html:45 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"143f","HASJETS":false,"RSSI":-78,"IP":"192.168.1.152","SSID":"Kulturhuset","FW":"2022-04-11"}
debug.html:45 {"CONTENT":"STATES","TIME":1652072232,"LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":1,"RED":0,"FLT":1,"TGT":36,"TMP":36,"CH1":32,"CH2":51,"CH3":54,"HJT":0,"BRT":7}
debug.html:45 {"CONTENT":"TIMES","TIME":1652072232,"CLTIME":1652017886,"FTIME":1652017884,"UPTIME":45827,"PUMPTIME":45771,"HEATINGTIME":12495,"AIRTIME":8,"JETTIME":12595,"COST":8.529831886,"FINT":30,"CLINT":14,"KWH":8.529831886,"TTTT":-7733,"MINCLK":7}
debug.html:45 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"bdef","HASJETS":false,"RSSI":-78,"IP":"192.168.1.152","SSID":"Kulturhuset","FW":"2022-04-11"}
debug.html:45 {"CONTENT":"STATES","TIME":1652072234,"LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":1,"RED":0,"FLT":1,"TGT":36,"TMP":36,"CH1":32,"CH2":51,"CH3":54,"HJT":0,"BRT":7}
debug.html:45 {"CONTENT":"TIMES","TIME":1652072234,"CLTIME":1652017886,"FTIME":1652017884,"UPTIME":45829,"PUMPTIME":45773,"HEATINGTIME":12495,"AIRTIME":8,"JETTIME":12595,"COST":8.529854774,"FINT":30,"CLINT":14,"KWH":8.529854774,"TTTT":-7735,"MINCLK":7}
debug.html:45 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"fcff","HASJETS":false,"RSSI":-78,"IP":"192.168.1.152","SSID":"Kulturhuset","FW":"2022-04-11"}
debug.html:45 {"CONTENT":"STATES","TIME":1652072236,"LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":1,"RED":0,"FLT":1,"TGT":36,"TMP":36,"CH1":32,"CH2":51,"CH3":54,"HJT":0,"BRT":7}
debug.html:45 {"CONTENT":"TIMES","TIME":1652072236,"CLTIME":1652017886,"FTIME":1652017884,"UPTIME":45831,"PUMPTIME":45775,"HEATINGTIME":12495,"AIRTIME":8,"JETTIME":12595,"COST":8.529878616,"FINT":30,"CLINT":14,"KWH":8.529878616,"TTTT":-7737,"MINCLK":6}
debug.html:45 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"17a5","HASJETS":false,"RSSI":-78,"IP":"192.168.1.152","SSID":"Kulturhuset","FW":"2022-04-11"}
debug.html:45 {"CONTENT":"STATES","TIME":1652072238,"LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":1,"RED":0,"FLT":1,"TGT":36,"TMP":36,"CH1":32,"CH2":51,"CH3":54,"HJT":0,"BRT":7}
debug.html:45 {"CONTENT":"TIMES","TIME":1652072238,"CLTIME":1652017886,"FTIME":1652017884,"UPTIME":45833,"PUMPTIME":45777,"HEATINGTIME":12495,"AIRTIME":8,"JETTIME":12595,"COST":8.529901505,"FINT":30,"CLINT":14,"KWH":8.529901505,"TTTT":-7739,"MINCLK":6}
debug.html:45 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"3fa4","HASJETS":false,"RSSI":-79,"IP":"192.168.1.152","SSID":"Kulturhuset","FW":"2022-04-11"}
debug.html:45 {"CONTENT":"STATES","TIME":1652072240,"LCK":1,"PWR":1,"UNT":1,"AIR":0,"GRN":1,"RED":0,"FLT":1,"TGT":36,"TMP":36,"CH1":32,"CH2":51,"CH3":54,"HJT":0,"BRT":7}
debug.html:45 {"CONTENT":"TIMES","TIME":1652072240,"CLTIME":1652017886,"FTIME":1652017884,"UPTIME":45835,"PUMPTIME":45779,"HEATINGTIME":12495,"AIRTIME":8,"JETTIME":12595,"COST":8.529925346,"FINT":30,"CLINT":14,"KWH":8.529925346,"TTTT":-7741,"MINCLK":6}
debug.html:45 {"CONTENT":"OTHER","MQTT":0,"PressedButton":"861b","HASJETS":false,"RSSI":-78,"IP":"192.168.1.152","SSID":"Kulturhuset","FW":"2022-04-11"}
```

Board:

![F9C6474C-8898-4303-849C-2D22B66BFE8D](https://user-images.githubusercontent.com/2194733/167318159-2a5497da-73e3-45f6-90a8-fe57879e578c.jpeg)

**Comment by eried** [comment]
I would suggest trying shorter cables and eventually migrating to the version with this 4CH level shifters -> https://s.click.aliexpress.com/e/_9wDImz

**Comment by visualapproach** [comment]
Hi,
What @eried said if the resistors don't do the trick. See [#253 ](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/discussions/253#discussioncomment-2717605) for info where to put them.

**Comment by 9khil** [comment]
> Hi, What @eried said if the resistors don't do the trick. See [#253 ](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/discussions/253#discussioncomment-2717605) for info where to put them.

waaaaaait a minute! I were pretty sure they would sit between LLC and DISP. I was wrong then. Will try to move them over and shorten cables. Thanks!

**Comment by emblitz123** [comment]
Hello,
I suspect there is an error in #253.
was written:
Headers H2:
1----------CIO
2----------CIO
3 resistor CIO
4 resistor CIO
5 resistor CIO
6----------CIO

But H2 is the display!

I have drawn the resistors in the plan.
Is that correct now?
![2022-05-10 11 09 13](https://user-images.githubusercontent.com/105225521/167594581-24e447fe-be65-480c-860f-e6a108489b1a.jpg)

emblitz

**Comment by eried** [comment]
Since the 8CH chip trying to do some automatic detection of the direction (if is in or out) and the resistors help in a experimental way you could use resistors in H2 or H1, or both. It is just part of the experiment.

**Comment by visualapproach** [comment]
#253 text corrected now, thanks.

**Comment by emblitz123** [comment]
Hello,
I would like to give feedback on my troubleshooting.
I shortened the wires between LLC and Disp and soldered 3x 680Ohm resistors between LLC and Disp.
The display works now and everything is fine :-).
I am very happy.
Thank you for this great project!!!
You can now add the Santorini whirlpool to the list.
It works.

Best regards
emblitz

**Comment by visualapproach** [comment]
Thank you @emblitz123 for the feedback! It matters to me and the community to see what solved the issue. Good job!
