### ISSUE TITLE
Hydrojets displayed with "no hydrojet model"

### ISSUE THREAD

**Issue by DandeMC** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#272]
Hello,

I don't understand why the hydrojets are shown in the menu. I selected in model.h "#define PRE2021			//the older one, no hydrojets" and I have the Palm Springs from 2020, but the menu shows the hydrojets.

Is this a bug or a settings misstake from me?

<img width="316" alt="image" src="https://user-images.githubusercontent.com/62901195/168001626-35c911f4-6c62-476f-ac7e-f96a072f529b.png">

**Comment by visualapproach** [comment]
#270

**Comment by DandeMC** [comment]
Oh perfect, thanks. Is there any way to update without lose my settings?

**Comment by visualapproach** [comment]
Yes. Uploading the new code does not erase the files. Uploading a new file image though, does. But you can upload every file in the data/ directory through the "upload.html" page from the web interface.

**Comment by DandeMC** [comment]
ok and the upload system nows where it must storage the file and overrides it?

**Comment by visualapproach** [comment]
Uploading files through web page is like saving a file to hard drive. Uploading the file system again is like formatting the harddrive and adding all files.
