### ISSUE TITLE
scheduled pump off doesn't work

### ISSUE THREAD

**Issue by DandeMC** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#281]
Hello,

I don't know if this is a mistake. I have 2 planned settings active. 8pm pump on, 10pm pump off. it is working. but if I use the pump myself, e.g. turn on at 6pm, it will not turn off automatically at 10pm. is that intentional or a bug?

**Comment by DandeMC** [comment]
Firmware version: 2022-04-11

I think its always and I turned it on via web page.

**Comment by DandeMC** [comment]
I was wrong. I turned it on via mqtt, not web page.

**Comment by DandeMC** [comment]
![image](https://user-images.githubusercontent.com/62901195/170097626-31de3e83-2757-4863-9812-47e82f6c3c95.jpeg)

**Comment by visualapproach** [comment]
thx, seems okay. Can you try again tonight to verify it wasn't just the time server that was wrong or something?

**Comment by DandeMC** [comment]
yes I will test it and write you tomorrow.

**Comment by DandeMC** [comment]
It's the same big. I turned it manually on at 7:58pm and it doesn't turned off on 10pm.

**Comment by visualapproach** [comment]
Assuming you have a home automation system since you use MQTT. Can it be the HAS that triggers the pump on again? You can use MQTT Explorer to log all commands sent to the ESP.

**Comment by DandeMC** [comment]
No it can't. I log the energy use from the pool too and I can see that it stays on when I turned it on manually. Yesterday it worked fine with the schedule on and off without manually turned on. 

![image](https://user-images.githubusercontent.com/62901195/170419993-92b43ca1-2f75-4922-82ea-da50c7c6a404.jpeg)

**Comment by visualapproach** [comment]
I didn't ask whether it was on or off. You already stated that. I asked if something else turned it on again. What's sending mqtt commands and can you check that it's not sending a contradictory command at 22:00?

**Comment by DandeMC** [comment]
I checked this already. but chance would also be small.
