### ISSUE TITLE
Wrong remote commands to a pump?

### ISSUE THREAD

**Issue by slipah** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#288]
![20220530_113305](https://user-images.githubusercontent.com/33259664/170972827-319bf8c0-c434-4b43-843c-b2b0c1b1ee84.jpg)
Hello!

I have a 2021 pump with model number S100101 

I installed the Wifi remote and I have some problems. 
The WIFI works correctly in AP mode and the local network is connected as well. The status shows what the real status of the device is (status of functions, temperature etc.)
When I press something on the pump controller, it tracks it correctly on the web interface.

So everyting is ok until this ponint,
BUT:
The problem is that if I change something on the web interface, the pump does something else. E.g. I change the unit from Fahrenheit to Celsius and the heating comes on. If I turn the heater on, the air compressor starts. So the remote control is not working properly. What can I do wrong?

**Comment by visualapproach** [comment]
What model did you define and have you tried another model?

**Comment by visualapproach** [comment]
You need to follow the build instructions to compile and upload new firmware. It will probably be possible to upload over the air, but bring a micro USB cable in case it doesn't.

**Comment by slipah** [comment]
Thanks for the tips. 
I went home to get my computer and set up a new build with MIAMI2021-model. The OTA update went without errors (after modifying platformio.ini) and everything was fine.

Thank you for your great project!

**Comment by visualapproach** [comment]
Well done!
