### ISSUE TITLE
Palm Spring AirJet - S100101 Not work Display and Web interface

### ISSUE THREAD

**Issue by lucableve** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#298]
Hi, I connected as per instructions and soldered the esp and the level shifter but nothing works.
As soon as I switch on the power, a jingle song starts from the display and shows a date and nothing more on the display as well as the buttons no longer work
From the serial web interface I don't see anything pass, not even the temperature.

Thanks

![WhatsApp Image 2022-06-15 at 16 14 57](https://user-images.githubusercontent.com/28319157/173849784-650426f8-baa5-4efc-b0a7-50b6f3d012f7.jpeg)

![WhatsApp Image 2022-06-15 at 16 15 34](https://user-images.githubusercontent.com/28319157/173849798-31d2d05a-f6b7-4112-870d-b3a3802efcd7.jpeg)

https://user-images.githubusercontent.com/28319157/173850228-7f93758d-8c44-422e-9a78-c629b16e72f8.mp4

**Comment by visualapproach** [comment]
Hi! From the web interface go to inspect console in the browser. Look for buttoncodes and see what it says when idle and when pressing some buttons.

**Comment by visualapproach** [comment]
Okay, you're supposed to choose one of the existing models. Try the miami2021.

**Comment by lucableve** [comment]
Nothing to do, I've tried them all, I think I'm at the point that it's the TXS0108E

**Comment by lucableve** [comment]
I solved it, took a new board and re-soldered everything by changing the nodemcu and level shifter as well. I noticed that the cables were also the critical part as I was using bad quality idc.
Now it works, so the model you indicated is correct. I thank you
