### ISSUE TITLE
Resistors

### ISSUE THREAD

**Issue by staylo** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#30]
Thanks to all who've contributed to this project!

On the current schematic, there are resistors R1-R7 with the description:

> -Optionally 7 x 500 to 820 Ohm resistors (lower than 500 would not protect against over current which may or may not occur if both sides drives the line in opposite directions. That is not suppose to happen but just in case. So, if you only have say 430 Ohms resistors you may as well skip them. Higher than 820 Ohms can make it not work.)

I think these may be superfluous. You can see an example schematic and operation for a bidirectional level converter on:

https://www.letscontrolit.com/wiki/index.php/Level_Converter

Examining the scenario where each device is driving the line in opposing directions:

The gate of each MOSFET in the level converter is connected to LV (3.3V). The ESP8266's pin is connected to the source, the spa's pin is connected to the drain.

Scenario 1: If the ESP pin is HIGH, the source is 3.3V. Gate and source voltages match - the MOSFET's source and drain are isolated  - no risk of overcurrent, regardless of whether the spa pin (drain) is HIGH or LOW.

Scenario 2: If the spa pin is HIGH (5V), we know the MOSFET's diode will be reverse biased because the source can only be 3.3V or less. No current flows from drain to source, so no risk of overcurrent, regardless of whether the ESP pin (source) is HIGH or LOW.

I'm not an expert on MOSFETs, so my understanding may be flawed - hopefully someone can chip in on this one.

**Comment by visualapproach** [comment]
Hello @staylo and thank you for commenting! You are probably right. Even if the MOSFET fries (some LLCs is reported to be flaky) and shorts out there is still a chance that the resistors on the pump side will save your day. I'm not entirely sure though if they are connected in series or as a pull up/down resistor. I don't personally have resistors mounted on my device but I don't want to say to people that they don't need any protection. It is a very small risc but I think it is up to every person to decide by themself whether to take it or not. Good of you to investigate the matter anyway 👍
