### ISSUE TITLE
4 wire web command schedule and ui fixes for palm springs hydrojet 54144

### ISSUE THREAD

**Issue by cobaltfish** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#304]
I noticed that on the web ui, bubbles / air jets show on a hydrojet only:
![image](https://user-images.githubusercontent.com/104502877/174993270-d735124f-496e-4e25-8ca5-aeb4e01df337.png)
I also noticed that while it can be done by uploading commands in the text file, the UI doesn't support setting God Mode on the config page, which I use to schedule the heating for off peak electricity:
![image](https://user-images.githubusercontent.com/104502877/174993571-d606de4f-d01d-4f7f-85df-4b8e11a2c0fd.png)

I've made a fork with some fixes for these:
![image](https://user-images.githubusercontent.com/104502877/175007588-193ff653-6ef3-4198-9ac0-702f45fd4feb.png)

![image](https://user-images.githubusercontent.com/104502877/175010709-d638a781-433e-4de1-8ce5-8b1b9030b7ba.png)

(I've also experimented with the async libs for the webserver, and have been running for about a week without any E13 errors, which is a new best for me!) 

I updated Code/4-wire-version/data/WebSocket.js to use 
   msgobj.HASAIR as logic for the air title, button, totals like used for jets
I also added IDs + divs to Code/4-wire-version/data/index.html so that the WebSocket.js would be able to do the getElementById in the same way
This was a new item required in Code/4-wire-version/src/main.cpp 
  doc["HASAIR"] = HASAIR;
and is set in Code/4-wire-version/lib/BWC4W/BWC_8266_4w_globals.h for a new type NO54144
I've given it a bit mask for the heating to be 2 stage, as I'd noted from the serial logs that when heating was turned on using the buttons it did so

For the changes on the config page, that was just in the Code/4-wire-version/data/config.html, to add additional items to the command list and drop down menu

https://github.com/cobaltfish/WiFi-remote-for-Bestway-Lay-Z-SPA/tree/feature/4w-palm-springs-54144

**Comment by visualapproach** [comment]
Cool! I'll check it out. Thx

**Comment by visualapproach** [comment]
Really nice, thanks for sharing. I pulled it into development branch and reset some defaults in model.h. Thank you, I really hope this will solve the communication problems for some people with the async library.
