### ISSUE TITLE
Start behavior is not saved

### ISSUE THREAD

**Issue by e-i-k-e** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#306]
Hello,

I have the problem with the current version that the start behavior is not saved. Default is "Last saved states" but I would like to have it "off".
After I have selected and saved the setting and then go to Settings again, or even if I restart the ESP, "Last saved states" is always displayed here.

Firmware version: 2022-05-24
Model: PRE2021

![image](https://user-images.githubusercontent.com/83473829/175398195-4a7e808b-780c-4ec6-b604-807052ec19d2.png)

**Comment by visualapproach** [comment]
Hi. Save off and then check the page layzspa/settings.txt
It should end with 'restore: false'.
Save last state and check for 'restore: true' in the layzspa/settings.txt file.
Does it do that?

**Comment by e-i-k-e** [comment]
> Hi. Speichern Sie ab und überprüfen Sie dann die Seite layzspa/settings.txt. Sie sollte mit 'restore: false' enden. Speichern Sie den letzten Zustand und suchen Sie in der Datei „layzspa/settings.txt“ nach „restore: true“. Tut es das?

Excuse me. But how can I call up the files?
![image](https://user-images.githubusercontent.com/83473829/175515131-56a42090-a6d2-47a7-8eeb-5cc00c5841e4.png)

**Comment by visualapproach** [comment]
Enter the url in the address field in your browser:
"layzspa.local/settings.txt" or 
"192.168.3.156/settings.txt"

**Comment by e-i-k-e** [comment]
> Enter the url in the address field in your browser: "layzspa.local/settings.txt" or "192.168.3.156/settings.txt"

![image](https://user-images.githubusercontent.com/83473829/175540521-f782c70e-26b6-4b47-bd97-ee1c01084388.png)

`{"CLTIME":1655999700,"FTIME":1655999702,"UPTIME":310551,"PUMPTIME":79532,"HEATINGTIME":25983,"AIRTIME":0,"JETTIME":0,"TIMEZONE":0,"PRICE":0.270000011,"FINT":30,"CLINT":14,"AUDIO":false,"SAVETIME":"2022-06-24 11:49:56","RESTORE":true}`


![image](https://user-images.githubusercontent.com/83473829/175540594-ff3d2c1a-7154-4dc2-b9d7-25fa137af1a0.png)

`{"CLTIME":1655999700,"FTIME":1655999702,"UPTIME":314654,"PUMPTIME":83541,"HEATINGTIME":26002,"AIRTIME":0,"JETTIME":0,"TIMEZONE":0,"PRICE":0.270000011,"FINT":30,"CLINT":14,"AUDIO":false,"SAVETIME":"2022-06-24 12:58:20","RESTORE":true}`

**Comment by visualapproach** [comment]
Okay so it does not save properly. Either wait until I can check it out or just upload the newest dev branch. Remember to upload the new data/ files also (the html etc pages). I don't know if latest code solves it but it works for me.

**Comment by e-i-k-e** [comment]
> Okay, es wird nicht richtig gespeichert. Entweder warten, bis ich es auschecken kann, oder einfach den neuesten Dev-Zweig hochladen. Denken Sie daran, auch die neuen Daten/Dateien hochzuladen (die HTML-Seiten usw.). Ich weiß nicht, ob der neueste Code es löst, aber es funktioniert für mich.


OK. I would like to fix this. Because a WLAN separation is enough and it starts with the previous settings. I experienced that the heating was then on unintentionally.

Can I upload and replace the files in this way via the web interface via "file upload"?
![image](https://user-images.githubusercontent.com/83473829/175543703-51946479-b7c2-4169-8c8e-49e155745298.png)

**Comment by visualapproach** [comment]
Yes you can. It's a good way to save your logs like uptime etc.

**Comment by e-i-k-e** [comment]
> Ja, du kannst. Es ist eine gute Möglichkeit, Ihre Protokolle wie Betriebszeit usw. zu speichern.

hmm.. still have the problem.
Can you estimate what a new version you are releasing?

**Comment by visualapproach** [comment]
I'll fix it within a day I think

**Comment by visualapproach** [comment]
Fixed. you need to upload "config.html" and it should work :-)

**Comment by e-i-k-e** [comment]
> Fixed. you need to upload "config.html" and it should work :-)

Thanks! It worked! :)

![image](https://user-images.githubusercontent.com/83473829/175811801-34bfba9e-350d-4132-92e5-b7e86880a7e3.png)
