### ISSUE TITLE
How does a firmware update work ?

### ISSUE THREAD

**Issue by emblitz123** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#316]
Hello,
I use the firmware version 2022-04-11.
![image](https://user-images.githubusercontent.com/105225521/176888366-d3cee833-1242-4a51-99e3-320469124e18.png)
Where can I see whether there is a more up-to-date firmware and how can I make an update?
On Github the firmware is called differently (3.xx).

My circuit board is often not accessible.
In IoBroker, "Dead" is then displayed via MQTT.
If I pull the 230V mains plug and plug it in, everything is fine again for a few hours until the circuit board hangs up again.

I would like to try to do an update to fix the bugs. 
In the menu of the web interface there is an item "File Uploader". Can I update it?
![image](https://user-images.githubusercontent.com/105225521/176888269-09c27a1c-5ab8-4d3e-a5aa-e2c93422d460.png)

Best regards
emblitz

**Comment by visualapproach** [comment]
Hi

There is different branches on github. Presently MASTER and DEVELOPMENT. All new updates goes into development branch first. Then after a while I merge it to master.
To check code date, go to Code/x-wire/config.h and look for FW_VERSION=xxxxxx

Updating is exactly the same as first install, except you can upload over the air. See build instructions. LittleFS files can be uploaded as first time or one by one from the upload page.

Unfortunately I don't know a way to sync github version tags with the code date.

**Comment by emblitz123** [comment]
OK thank you.
I thought the update would be possible via the website.
What did you add the File Upload menu item for?

Best regards
emblitz

**Comment by visualapproach** [comment]
To upload files to the file system without wiping the whole drive. Nice to save the stats and settings
