### ISSUE TITLE
Cost data not updating 

### ISSUE THREAD

**Issue by garrydwilms** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#32]
Hi, 

Does this section need a saveappdata() ??
My webpage doesn't update the cost? Does anybody else's?

void WS_Timer() {
  appdata.cost = getHeatingTime() * 1900 + getFilterTime() * 40 + getAirTime() * 800 + appdata.uptime * 2; //wattSeconds
  appdata.cost /= 3600000.0; //kWh
  appdata.cost *= myConfig.price; //money
  sendMessage(1);
}

**Comment by visualapproach** [comment]
![image](https://user-images.githubusercontent.com/22987250/95680153-bfe0ff80-0bd7-11eb-86cf-8de0e87ceab5.png)

Updates too well...

**Comment by garrydwilms** [comment]
Yeah. This is now working fine. Don't know what was up initially.
