### ISSUE TITLE
Upload failed since PlatformIO last update

### ISSUE THREAD

**Issue by Metarko** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#323]
Hello and at first many Thanks to visualapproach for the very great project. 
I will send you more then one coffee ;)

Does anybody else have problems with uploading since yesterday ( new update of platfomIO). ?
I´m not an expert but it seems as visual studio have problems to communicate with the ESP.

Anybody else how have such a problem or an solution?

**Comment by visualapproach** [comment]
add this to platformio.ini, and next time please post screenshots so we can see what's wrong.
`upload_port = COM4`
replace COM4 with whatever number or mac versions of the COM port you got.

**Comment by Metarko** [comment]
Thank you for your quick response. I have tried it bevore i have written you. Heres the Error Message while uploding:
[](url
![Unbenannt](https://user-images.githubusercontent.com/108877781/178104900-897512b5-6b18-4b66-8696-6d882625bc0b.JPG)
)

**Comment by visualapproach** [comment]
Yeah, you need to "clean all" (clean the cache on the PC) in the pio menu. And pio no longer recognizes ESP with ch340 UART. Maybe they will change it in future versions. So you need the upload_port = xxx until further

**Comment by Metarko** [comment]
Thank you very much , now it´s working again. Sorry for this nope question :) .
