### ISSUE TITLE
Helsinki 100101 Problems

### ISSUE THREAD

**Issue by xGDNAx** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#324]
Hello, I have a Helsinki Spa with the model 100101, I ordered the PCB version 2 on the internet, I set the model Miami2021 and PCB v2.
so now to my problems
1. I get the IP in the display and hear the melody when plugging in but nothing more.
2. I can't set anything in the web interface and I don't see any temp.

What have I tried
1. the TXS0108E
![20220707_201824_HDR](https://user-images.githubusercontent.com/59249186/177845170-7ea52cca-2e29-4378-ac43-c0eb03760ad9.jpg)

2. the bidirectional logic level converter
![20220707_201849_HDR](https://user-images.githubusercontent.com/59249186/177845192-ad7532f1-ce35-4f2e-9010-a1d786433900.jpg)

![20220707_202618_HDR](https://user-images.githubusercontent.com/59249186/177845144-d1c39f78-3b14-44f2-b401-1ef7b48ed8d5.jpg)

1. 530 ohms
2. 680 ohms

please ignore the cable colors, I repinned it that RED is 5v and black is GND.

what am I doing wrong?

At least that's what I could find here in terms of solutions

**Comment by xGDNAx** [comment]
Thanks, i install the second wire, and ist work, dam im stupid

**Comment by visualapproach** [comment]
No you're not, you were just tempted to follow the pcb silk screen :)
Good work

**Comment by xGDNAx** [comment]
is it right that 
1. I can no longer switch off the pump. 
2. the key lock does not work

**Comment by visualapproach** [comment]
1. Yes, and you couldn't do it before either. It just dimmed the display to make you feel good.
2. It works. After a couple of minutes idling it will lock as before. But when you use the web ui the esp presses power-up+unlock for you so you don't have to.

**Comment by visualapproach** [comment]
Just ask in a new discussion topic if you need specific help. Nobody here including me seem to know anything  about FEHM but there is some mqtt gurus.

**Comment by Ch1p1** [comment]
Hi,

I had the same issue with a Helsinki S100101 new square pump: display control working, but i got no communication with the pump with the TXS0108E module. I tried it without it, on 5V risking the ESP, and i was able to read the temperature from the pump but i was unable to control it either from the buttons or from the webui. Then i got a new LS-BIDI-4 shifter which i put only on the CIO side, and voila everything works as a charm. Thank you for your work with this project, coffee on its way ;)

**Comment by visualapproach** [comment]
Ah, nice 😃 
Thank you for that and for sharing what helped you solve your issue!
