### ISSUE TITLE
6-Wire Palm Springs #54129 Melody but no Control via GUI

### ISSUE THREAD

**Issue by air101** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#325]
Dear Supports,

what a nice project! I've built it for a 6-Wire Palm Springs #54129. After connecting it, I can hear the Melody and see the Date in the Display. I can connect to the Wifi but cant control anything. The temperature isn't shown either in GUI.

With the Display it is just showing 2 Red dots on the unit and cant press anything. 

I've tried PRE2021 in model.h. Should I try something different?

Thank you and Best Regards

**Comment by visualapproach** [comment]
Hi there, your connection to the CIO (pump) is not working. Check connections

**Comment by air101** [comment]
checked with multimeter, seems ok. Maybe the cables are too long?

**Comment by xGDNAx** [comment]
[https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/324#issue-1297911919](url) look

**Comment by xGDNAx** [comment]
Hey do you have a picture of your circuit board?
I had soldered the resistors but that wouldn't have been necessary.

I chose MIAMA2021 as the model, which pump number do you have?

maybe you have the same problem as me

**Comment by air101** [comment]
Not sure which pump number I have. Where can I find that out? I tried MIAMI2021 and PRE2021. Same outcome, Display shows IP and Date with both and the audio.
![IMG_2893](https://user-images.githubusercontent.com/9119009/178057740-c22848ac-694e-4c7a-ba72-c1be35a9f738.jpg)
![IMG_2895](https://user-images.githubusercontent.com/9119009/178057789-b8009db7-4033-461e-8ac0-6895fa7ce8ae.jpg)

**Comment by xGDNAx** [comment]
check the cable the pin assignment seems strange to me according to the picture.

The number can be found on a sticker on the side.

**Comment by air101** [comment]
Colours dont match, as I didnt have the appropriate ones but should be ok.

**Comment by air101** [comment]
Picture of the sticke
![IMG_2901](https://user-images.githubusercontent.com/9119009/178106147-e51ce761-600d-49e5-af4d-740ea80eca02.jpg)
r

**Comment by xGDNAx** [comment]
You habe the egg?

**Comment by air101** [comment]
Yes. installed short wires, still no go.
![IMG_2902](https://user-images.githubusercontent.com/9119009/178108483-3b4608f9-5c86-4856-8a94-b4cd09cf0078.jpg)

**Comment by air101** [comment]
One more Q: Do I leave the
bwc.begin(); //no params = default pins 
or should I set it to 
bwc.begin(D1, D2, D3, D4, D5, D6, D7);
?

**Comment by visualapproach** [comment]
No params

**Comment by air101** [comment]
Unfortunately it still doesnt work.

**Comment by xGDNAx** [comment]
maybe the shifter is defective or the wrong one.

**Comment by air101** [comment]
I tried 2 of those https://www.amazon.de/gp/product/B07HB2S2VC

**Comment by xGDNAx** [comment]
DollaTek 5Pcs 8 Kanal I2C IIC Logic Level Modul Konverter Bidirektionale für Arduino https://amzn.eu/d/10kN9SH

**Comment by air101** [comment]
ok thanks, I'll check those out and try again

**Comment by RatAttack83** [comment]
Hello, same i have the same problems with my Miami 2022(1) 6 wire square.
I've tried everything... Resistors in dsp connector, 10k connector, extra short wires, with 8ch level converter and also without level converter... 
Startup sound comes and IP is shown but than nothing else.
No controls via webgui and the buttons doesn't work, too...
I've no ideas to go on. I routed the board myself and atched it. (Ports are correct) 
I will trie to monitor the esp today, but i dont have much time because of my work and a newborn at home...
Sorry for my bad English, I'm German without much Training last years 😂
Thanks alot and forgot to say...its a very cool project!

**Comment by air101** [comment]
> DollaTek 5Pcs 8 Kanal I2C IIC Logic Level Modul Konverter Bidirektionale für Arduino https://amzn.eu/d/10kN9SH This work for me

Ok it arrived today, still no go. Sound + IP but nothing more. I'm going to remove the pump mainboard and examine it at my desk, unless anyone else has any ideas?

**Comment by RatAttack83** [comment]
Mine works fine at the moment. I've connected the esp directly with 560ohm resistors at the display ports. Without any level converter. 
But still no function. Now i connected the usb cable to monitor the esp. than it works fine. 🤷‍♂️ 
After disconnecting usb it goes on... So i leaved it for the moment... Tomorrow I will solder the R1 1k resistor, because i think the voltage wasn't stable enough... 
Perhaps you can give it a try ☺️

**Comment by air101** [comment]
Tried it today with a USB Powerbank. Still no go.

**Comment by menime8** [comment]
I tried it with powerbank, won't work. I hook up my PC, not the best Idea, the ESP goes down. Shoots the program away. I think the 2 5 Volt levels and no galvanic isolation.  I need to try it with my laptop.

Many germans here 🤣 ich auch

**Comment by RatAttack83** [comment]
Wahrscheinlich alle deutsche bis auf den Projektschöpfer nur denken alle sie müssen versuchen Englisch zu schreiben 😂

Very interesting idea with the missing galvanic isolation! My spa works fine since the last try, but don't want to plug it out.... 😂 But i have to construct a case and solder the three resistors 🙄 
Now it is working via MQTT in nodered in my smarthome 👌
![21C7D2DD-8EC4-4A4A-9B15-DBAFEB131551](https://user-images.githubusercontent.com/109126910/178966939-63e42200-5d04-4f97-8f57-5c953b79b18e.jpeg)

**Comment by SigmaPic** [comment]
> 10k an R1

I don't understand how the 10k can stabilize the voltage.
Please, can you explain ?

@air101 Can you measure the voltage you have on Vin with a multimeter without the USB powerbank ? 
You can also measure the original voltage without your PCB in the middle (directly on the connector of the CIO).

By this way, we will see if the 5V drops too low.

**Comment by xGDNAx** [comment]
> > 10k ein R1
> 
> Ich verstehe nicht, wie die 10k die Spannung stabilisieren können. Bitte, können Sie das erklären?
>
aren't they for that?
or what is R1 for

**Comment by RatAttack83** [comment]
R1 is at the 3V output and the voltage level shifter. So this won't change anything... I will try next days an measure the voltage... Perhaps a small elko could help at Vin if the voltage breaks down.

**Comment by SigmaPic** [comment]
From my understanding R1 is here to maintain the OE (output enable) to 0 during startup phase.
But it's only usefull for TXS0108E, not for mosfet shifter.

Measuring the voltgae without the powerbank may help to understabd what happens.

@air101 If you remove the powerbank, does it continue to work or it stops working ?

**Comment by air101** [comment]
Ok, big surprise: I made/created some JST-SM connectors to tryout and it seems that the one with the short wires (which i created as last tryout) sometimes didn't have proper connection within the 5V line from CIO. But nevertheless the NodeMCU was the main problem, I just switched them again to be sure and NodeMCU V3 from AzDelivery is not working. The one I ordered above is working properly with the power from the CIO. So thank you everyone for the debugging!

**Comment by menime8** [comment]
> Ok, big surprise: I made/created some JST-SM connectors to tryout and it seems that the one with the short wires (which i created as last tryout) sometimes didn't have proper connection within the 5V line from CIO. But nevertheless the NodeMCU was the main problem, I just switched them again to be sure and NodeMCU V3 from AzDelivery is not working. The one I ordered above is working properly with the power from the CIO. So thank you everyone for the debugging!

Sounds i'm in the right way to Switch my node, too.

**Comment by SigmaPic** [comment]
> Sounds i'm in the right way to Switch my node, too.

@air101 use the smae node that yours. Isn't it ?

**Comment by visualapproach** [comment]
> Ok, big surprise: I made/created some JST-SM connectors to tryout and it seems that the one with the short wires (which i created as last tryout) sometimes didn't have proper connection within the 5V line from CIO. But nevertheless the NodeMCU was the main problem, I just switched them again to be sure and NodeMCU V3 from AzDelivery is not working. The one I ordered above is working properly with the power from the CIO. So thank you everyone for the debugging!
> 
> @visualapproach enjoy the coffee :)

Oh thank you very much! It takes time to read all your suggestions and problems, and try to fix them, so a coffee is perfect!
Really strange that some NodeMCU's don't work. Wonder if its not working on this particular project or if it's a bad unit batch? Glad you found out though. Have a nice swim now ;-)

**Comment by menime8** [comment]
> > Sounds i'm in the right way to Switch my node, too.
> 
> @menime8 air101 use the smae node that yours. Isn't it ?

Yes, He uses the V3.2 first time. Can see the resistors on D3 and D4?

@air101 where did you buy your new board? Have you a picture? I'm from germany, too. Thanks

**Comment by air101** [comment]
> > > Sounds i'm in the right way to Switch my node, too.
> > 
> > 
> > @menime8 air101 use the smae node that yours. Isn't it ?
> 
> Yes, He uses the V3.2 first time. Can see the resistors on D3 and D4?
> 
> @air101 where did you buy your new board? Have you a picture? I'm from germany, too. Thanks

I bought it here: https://www.amazon.de/gp/product/B07PGH1L8S/ref=ppx_yo_dt_b_asin_title_o02_s00

**Comment by xGDNAx** [comment]
AZDelivery NodeMCU Lolin V3... https://www.amazon.de/dp/B06Y1ZPNMS?ref=ppx_pop_mob_ap_share
Its work for me
