### ISSUE TITLE
Temperature goes crazy when i change via web interface (ok with main pannel) on my s100101 pump

### ISSUE THREAD

**Issue by williams407** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#326]
Hello, I correctly flashed my nodemcu with "MIAMI2021" model, everything work correctly, i can't change what i need in the main pannel , in the web interface eveerything work well, but when i tried to change the temperature its goes crazy, displaying and change random temp every second. I'm using PCBV1 with no resistance

thanks

https://user-images.githubusercontent.com/20027979/178123061-194a84c1-09d1-47ee-b162-064b3fa776d2.mp4

**Comment by visualapproach** [comment]
Maybe try WITH resistors to the DSP?
