### ISSUE TITLE
Disp not turning on and nothing happening

### ISSUE THREAD

**Issue by Naesstrom** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#33]
I finally got my levelshifter today and mounted everything, flashing went fine once I updated all the libraries 🗡️ 
![image](https://user-images.githubusercontent.com/6575206/95899730-3bd27780-0d91-11eb-9618-438062ad396a.png)

Problem is that when I connected it to the unit the display doesn't turn on, the ESP works and I can connect to it but pressing power etc. doesn't turn anything on either?
Disp goes to disp and CIO to the controller so everything seems to be right, if the connections was turned around ie. not 1-1, 2-2 etc. I guess it shouldn't even power on.
![image](https://user-images.githubusercontent.com/6575206/95900081-ac799400-0d91-11eb-899c-2bda15a3a8eb.png)

**Comment by visualapproach** [comment]
Have you checked that the pin outs in the sketch matches the pin outs on the pcb?

**Comment by Naesstrom** [comment]
I'll check, the pcb is based straight off from your schematic tough
![image](https://user-images.githubusercontent.com/6575206/95981849-9dd9be00-0e1f-11eb-985c-4c00a8b6fcbe.png)

**Comment by visualapproach** [comment]
Ok, should not be the problem then I hope. But check as good as you can that there is no shorts between tracks and that there is connectivity where it suppose to. Then I would try the hw-tester program. And if you are sure the connections is correct you could bypass the resistors and see if it makes any difference.

**Comment by Naesstrom** [comment]
Yeah something must have been wrong with the PCB, couldn't get a measure between to points and after adding a extra cable it seems to be working!
