### ISSUE TITLE
6wire Square Pump Model S100104

### ISSUE THREAD

**Issue by there707** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#331]
I've done exactly what others have done for square model S100102 but I cannot get buttons or GUI to work. I do get current temperature, temperature SP, brightness slider and the ESP reset button but that's it. 
- PCB_V1
- Removed TXS1008Eand jumpered A1, A2... to B1, B2... 
- added 10K resistor
- added and removed 680ohm resisters on display connector

Is my S1000104 that different?

**Comment by menime8** [comment]
Your display plays the funky sound at startup? Then you see the IP adress and actual date?

Set PCBV1 in program? Select Miami2021 in model.h?

**Comment by there707** [comment]
Yes on both questions.

**Comment by visualapproach** [comment]
> Yes on both questions.

There are 4 questions...

**Comment by menime8** [comment]
You have the same problem like me. At the moment i can´t figure out what is wrong.
Which ESP you have? ESP8266MOD?

**Comment by there707** [comment]
> > Yes on both questions.
> 
> There are 4 questions...

Sorry, yes on both lines of questions

**Comment by there707** [comment]
> You have the same problem like me. At the moment i can´t figure out what is wrong. Which ESP you have? ESP8266MOD?

I'm not familiar with ESP8266MOD, but I refer to my as a NodeMCU
![16577392529751730971481828584308](https://user-images.githubusercontent.com/73621249/178812301-cdebb16b-8948-493c-b947-777de818afe7.jpg)

**Comment by menime8** [comment]
What Version of CIO board you have? You find it bottom right corner.

![IMG_20220713_125309](https://user-images.githubusercontent.com/109034011/178964786-1f16ffae-ad29-4028-837b-d909674fe481.jpg)

**Comment by air101** [comment]
Try a different NodeMCU, see my problem here: #325

**Comment by there707** [comment]
![image](https://user-images.githubusercontent.com/73621249/179024885-b555bc41-8c1c-4142-b4e5-5f7be8a0bf15.png)
 
Now going to look at https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/325

**Comment by visualapproach** [comment]
#330

**Comment by there707** [comment]
> #330

Just got back to this, thanks @visualapproach this worked. PCB_V2B, red LCC, no resistors or caps and wiring per @Sigmapic
