### ISSUE TITLE
Home Assistant and MQTT

### ISSUE THREAD

**Issue by SchallertDK** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#342]
Hi,
I cant get my MQTT Broker to automatic find the Spa module.
Everything's seems to work. The spa modul is connected to MQTT:
![image](https://user-images.githubusercontent.com/103250760/179965788-da6e6e05-0642-432f-b54b-af4e74883488.png)

And the Home Assistant receive data from the spa module:
![image](https://user-images.githubusercontent.com/103250760/179966076-a3a0e315-18b8-4d1a-a348-a37329de11dc.png)

But the broker wont find it? And i cant get the lovelace as showed in your "Build-instructions-Bestway-WiFi-remote.pdf":
![image](https://user-images.githubusercontent.com/103250760/179966181-11e36646-8346-49ff-b3da-9689446ab41b.png)

![image](https://user-images.githubusercontent.com/103250760/179966601-56432886-13b0-40a7-adbe-7562a9e1aede.png)

What am i missing? 2 peoples has tried to help me, but we cant find the "error"?

**Comment by chunkysteveo** [comment]
are you on a 4-wire pump? Auto discovery isn't implemented yet on the 4-wire firmware...

**Comment by SchallertDK** [comment]
Yes i have.
How do i so do? :)

**Comment by chunkysteveo** [comment]
You have to manually add in the sensors at the moment - using the code and help in the repo https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/tree/master/Code/Home%20assistant%20config

**Comment by SchallertDK** [comment]
Thank you,
I will try to set it up. But i'm not an expert at this HA yet :)

**Comment by chunkysteveo** [comment]
Ohh i may test! My efforts worked, but the climate wouldn't import for me.

Will try the new dev branch......

**Comment by visualapproach** [comment]
> Ohh i may test! My efforts worked, but the climate wouldn't import for me.
> 
> 
> 
> Will try the new dev branch......

I had some trouble too. Turned out the message was too long for the ESP to handle so don't use long base names.

**Comment by chunkysteveo** [comment]
Ahhh - i was getting there.... cutting down the packaged worked. Good to know I was on the right track!

**Comment by visualapproach** [comment]
Alright, will handle it when !AFK

**Comment by chunkysteveo** [comment]
Auto discovery worked really well - but the God Mode switch didn't import into HA?

**Comment by SchallertDK** [comment]
My HA went in "Safe Mode" after trying adding new "text"

I made a file named "layzspa.yaml" into the folder "package" and pasted everything from the layzspa.yaml file at github + removed the # at the 2 areas where it only was for the 4-wired pump.

In the configuration.yaml i added:
![image](https://user-images.githubusercontent.com/103250760/180147304-6e01e854-b80a-410b-b837-dbe473c10446.png)

In the automations.yaml i added what was in the "automations.yaml" file at github

About the two helpers i need to make, i cant find any helpers who can take the infos from the github file?
![image](https://user-images.githubusercontent.com/103250760/180148219-d7384e86-701d-4521-9ba3-8b6e92332693.png)

![image](https://user-images.githubusercontent.com/103250760/180148275-59744b03-4ddc-49b6-bfbc-104538debff7.png)

I to get out of "safe mode" at the HA i had to delete 
"homeassistant:
  packages: !include_dir_named packages" from the configuration.yaml

So i'm back to start again and dont know what i have done wrong

**Comment by chunkysteveo** [comment]
If you can download the "Development" branch of this project - HA Autodiscover is now in place and does work for me - adds in all the required sensors (apart from god mode switch?). Maybe try the development branch - treat it like a new project - so you will need to set your model number etc and upload again. But then at least HA will/should work.

Alternatively you can just add in the sensors and switches and climate in the configuration.yaml file in their appropriate places.

I've not used packages in HA, so can't advise. But the helpers - one is a Number helper, and the other is a "Toggle" helper.

**Comment by SchallertDK** [comment]
I had now downloaded the development zip file, opened like a new project, change the parameters so it is matching my pump and ip. Build image file, uploade to the spa module. everything with "succes".
But i stil dont se any activity at the MQTT in HA.
The Spa module is connected with MQTT an no fails there.
About this GOD MODE you write about, where do i manually enable that? I cant find it in the PlatformIO file?

**Comment by chunkysteveo** [comment]
Hmm, not sure if it's not working for you? If you go to Integrations, MQTT it should be there as a new device with entities?

The god mode switch is the "Take Control" switch which allows us to control the 4-wire pumps. It was/is called god mode in the code in parts(!).

**Comment by SchallertDK** [comment]
Ok, the Take Control bottom is at the Spa "website" - So i think it is ok?
The MQTT is still not reacting for any new device?
![image](https://user-images.githubusercontent.com/103250760/180164333-9c81e422-c7f7-44e8-b8c2-a4e3f80b14e8.png)

I have restartet the HA and the Spa ESP 3 times, with no respons.

When i'm typing # at the configuration in the MQTT it shows the communication to the spa module:
![image](https://user-images.githubusercontent.com/103250760/180164731-7cd19ed5-4f95-462f-ad08-fcb791b04e81.png)

**Comment by chunkysteveo** [comment]
Is discovery enabled in Mosquito? If you click on re-configure MQTT and check it is? and the topic is homeassistant/status ?
![image](https://user-images.githubusercontent.com/14663002/180166210-023d62b0-5871-4482-8ffc-f426b4f5f60a.png)

**Comment by SchallertDK** [comment]
Yes it is:
![image](https://user-images.githubusercontent.com/103250760/180166623-d0403e5a-815f-45fc-bb92-722fce53f4b6.png)

**Comment by chunkysteveo** [comment]
hmm, i'm not 100% sure what the issue is, sorry?

You can still try to add the switches and sensors manually into HA using configuration.yaml

**Comment by chunkysteveo** [comment]
Try adding the below in `configuration.yaml `where you have `switch:` (you can't have more than one `switch:` declaration, so look for it and add below it, or copy and paste all of the below if there is no `switch:`)
```
switch:
  - platform: mqtt
    name: "Hot Tub Bubbles"
    icon: "mdi:chart-bubble"
    state_topic: "layzspa/message"
    command_topic: "layzspa/command"
    value_template: "{{ value_json.AIR }}"
    payload_on: '{"CMD":2,"VALUE":1,"XTIME":0,"INTERVAL":0}'
    payload_off: '{"CMD":2,"VALUE":0,"XTIME":0,"INTERVAL":0}'
    state_on: 1
    state_off: 0
    availability_topic: "layzspa/Status"
    payload_available: "Alive"
    payload_not_available: "Dead"      
```

**Comment by SchallertDK** [comment]
This text i have to replace in the configuration.yaml, where the "switch" for air bubbles is right? In yoour switch it is named hot tub bubbles

**Comment by chunkysteveo** [comment]
Yeah, mine is called Hot Tub Bubbles, you can call it what you like.

**Comment by SchallertDK** [comment]
Right now my HA is down, and i cant reach it. I tried to make those 2 helpers, and then it went down.

Next question is: the 2 areas with "#" , i have to delete the # at both areas right?

When i try to make that "layzspa.yaml" file in the "package" folder, then i have to add this in the configuration.yaml, and remove the "#", right? :
#homeassistant:
#  packages: !include_dir_named packages

But when i do this, the HA says it is wrong and, when i delete it, the HA is happy again.
Right now i have it all in the configuration.yaml - But it is right?

**Comment by chunkysteveo** [comment]
I'm not sure on using the packages way - mine was all just added to the main configuration.yaml file in one go. Editing yaml is tricky to get the indents and format right.

**Comment by SchallertDK** [comment]
Okay, then i will do the same.
What about this: ? Did you add this in the configuration.yaml in the bottom after all the other stuff?
![image](https://user-images.githubusercontent.com/103250760/180201423-132f208e-47bb-4c1c-a316-50458242be6f.png)

**Comment by chunkysteveo** [comment]
No, I have them added individually - my HA is a large setup that's been worked on for years now. I would recommend reading up or watching some tutorials on how to add custom switches and sensors to yaml.

**Comment by SchallertDK** [comment]
Thank you for your help today, i will watch som tutorials :)

**Comment by visualapproach** [comment]
I fixed a minor thing in HA config for the 4w now. Best result is when you do it in this order:
1 - Update ESP
2 - delete the old device from HA:
![image](https://user-images.githubusercontent.com/22987250/180244890-7785f88f-5fe7-46b1-9134-77ac9f2655f5.png)
3 - restart ESP
4 - look at the device in HA again. Refresh page with F5 if it's not populated yet.

**Comment by visualapproach** [comment]
And for now, use max 14 chars in base topic.

**Comment by SchallertDK** [comment]
I couldn't remove the old device as you shows in the screendump, because i never got the chance to find it.
I have uploaded the last version to the ESP
I have manually removed all text regarding the spa in the configuration.yaml
Restartet the ESP and refreshing (F5) the HA multiply times, but nothing is popping up?

What are the "max 14 chars in base topic"?

**Comment by visualapproach** [comment]
![image](https://user-images.githubusercontent.com/22987250/180377440-d9e9f929-4778-4c39-a9b9-885c1b873ae8.jpeg)

**Comment by SchallertDK** [comment]
is the Client ID and Base Topic: layzspa2 - in the instructions is the name "layzspa"
I have try setting the Telemetry Interval from 600 to 5, but no changes

**Comment by visualapproach** [comment]
I don't understand what you're asking. Base topic is whatever you type in the box. And you should not type more than 14 characters for now.
Changing the telemetry interval will, well, change the interval between mqtt messages

**Comment by SchallertDK** [comment]
My spa module says it is connected with MQTT
My HA gets data from the spa module
But i cant make lovelace or get the lovelace as shown in the instructions pages.
When i manually import node-red flow, and set up af lovelace with that, there is no communication between lovelace and spa module. But it shows in node-red that it is connected and running:
![image](https://user-images.githubusercontent.com/103250760/180391682-65e8c79b-8b47-4e4e-a7cb-958f7229f695.png)

**Comment by visualapproach** [comment]
You don't need node red to get a dashboard. Disable that flow, I think it just messes things up unless you have a good reason to use it. Then restart HA then restart ESP. Go to devices in the configure page.

**Comment by SchallertDK** [comment]
Still no sign of new device in the MQTT :(
![image](https://user-images.githubusercontent.com/103250760/180395002-c883efff-a6c8-41e3-91b0-e4672f3ed28b.png)

**Comment by visualapproach** [comment]
Judging from your picture you are looking at the wrong place. Click on DEVICES in the top menu

**Comment by SchallertDK** [comment]
There is nothing called layzspa, nothing at al even with the word "spa" (?)

**Comment by visualapproach** [comment]
You need v3.4.0 of the firmware

**Comment by SchallertDK** [comment]
Now you lost me again :)
Firmware to the esp (spa module?)

**Comment by SchallertDK** [comment]
But the firmware at the spa module says:
![image](https://user-images.githubusercontent.com/103250760/180397748-d6deb37d-c48e-4ab7-9b54-dd926effac70.png)

**Comment by chunkysteveo** [comment]
It will be very similar, if not the same as a dev branch. I am just testing the new release now.

**Comment by SchallertDK** [comment]
Is there any where else i can check the it is the rigt version? I tried to search in the Visual Studio Code for "firmware" but couldn't find any "version" number

**Comment by visualapproach** [comment]
> But the firmware at the spa module says:
> 
> ![image](https://user-images.githubusercontent.com/103250760/180397748-d6deb37d-c48e-4ab7-9b54-dd926effac70.png)
> 
> 

Meaning you didn't upload it properly because then it would say 2022-07-21

**Comment by chunkysteveo** [comment]
The latest release is the latest, which includes HA Auto discovery. I have just downloaded it, set it up on my pump and it's connection to MQTT, HA, and pulled in as a device with all sensors. The firmware/code works, but there is an issue with your setup somewhere?

Have you set the model number and PCB version in model.h file. Then upload and set MQTT etc. IT should then work with autodisovery...?

**Comment by SchallertDK** [comment]
I thought i did everything after the book. But maybe my PCB is wrong?
I bought the one descripted in the instruction
![image](https://user-images.githubusercontent.com/103250760/180400600-809acc6f-85ca-4168-a60e-29a088122de7.png)

The pump model number is right. #54123

**Comment by SchallertDK** [comment]
![image](https://user-images.githubusercontent.com/103250760/180401083-96223663-fc96-4734-8b88-67073d42c58e.png)

**Comment by SchallertDK** [comment]
Ohhh... I can see it maybe is the wrong PCB i have chosen. I dont have round corners at mine :/

**Comment by chunkysteveo** [comment]
#define PCB_V1, comment out #define PCB_V2

**Comment by SchallertDK** [comment]
I really thought we had it now - But still no device to found

My setup now:
![image](https://user-images.githubusercontent.com/103250760/180403017-b8face35-3f2e-4b93-9097-2bb02785cd6a.png)

Spa "display":
![image](https://user-images.githubusercontent.com/103250760/180403223-a89adb03-1e1d-409e-b90b-c2d94a35bd3d.png)

**Comment by chunkysteveo** [comment]
anything in your Mos logs?? - /hassio/addon/core_mosquitto/logs

**Comment by SchallertDK** [comment]
What about the purple text in the bottom at the coding's?
Should it be undefined with "//" in front?
![image](https://user-images.githubusercontent.com/103250760/180403643-eec4fbef-73d7-42ea-8463-ed73dbf46563.png)

**Comment by SchallertDK** [comment]
How/where do i define that model number?

**Comment by chunkysteveo** [comment]
have you uploaded a new file system too? I see you have no AIR/Bubbles in the GUI, is that right??

Ignore the text you have circled, it won't trigger.

**Comment by chunkysteveo** [comment]
Build filesystem image, and then Upload filesystem image?

**Comment by SchallertDK** [comment]
a new file system?
I downloaded the code - opened with visual studio code - change the pump model and the PC - set up the ip adress - build file system image (with succes) - upload Filesystem image (with succes)

At the spa module i set up again the MQTT and restart the ESP.

After that i restart the HA

**Comment by SchallertDK** [comment]
Build filesystem image:
 *  Executing task: C:\Users\admin\.platformio\penv\Scripts\platformio.exe run --target buildfs --environment nodemcuv2 

Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/nodemcuv2.html
PLATFORM: Espressif 8266 (3.2.0) > NodeMCU 1.0 (ESP-12E Module)
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2)
 - tool-esptool @ 1.413.0 (4.13)
 - tool-esptoolpy @ 1.30000.201119 (3.0.0)
 - tool-mklittlefs @ 1.203.210628 (2.3)
 - tool-mkspiffs @ 1.200.0 (2.0)
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 43 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ArduinoJson @ 6.19.4
|-- ESPDateTime @ 1.0.4
|-- WebSockets @ 2.3.7
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESPAsyncTCP @ 1.2.2
|   |-- Ethernet @ 2.0.0
|   |   |-- SPI @ 1.0
|   |-- SPI @ 1.0
|-- PubSubClient @ 2.8.0
|-- WiFiManager @ 0.16.0
|   |-- DNSServer @ 1.1.1
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266WebServer @ 1.0
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- EspSoftwareSerial @ 6.16.1
|-- ESPAsyncTCP @ 1.2.2
|-- ArduinoOTA @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266mDNS @ 1.2
|   |   |-- ESP8266WiFi @ 1.0
|-- BWC4W
|   |-- ArduinoJson @ 6.19.4
|   |-- ESPDateTime @ 1.0.4
|   |-- LittleFS @ 0.1.0
|   |-- EspSoftwareSerial @ 6.16.1
|   |-- Ticker @ 1.0
|-- DNSServer @ 1.1.1
|   |-- ESP8266WiFi @ 1.0
|-- ESP8266WebServer @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- ESP8266WiFi @ 1.0
|-- LittleFS @ 0.1.0
|-- Ticker @ 1.0
Building in release mode
Building file system image from 'data' directory to .pio\build\nodemcuv2\littlefs.bin
/config.html
/debug.html
/favicon.png
/function.js
/index.html
/main.css
/manifest.json
/menu.png
/mqtt.html
/remove.html
/success.html
/upload.html
/visualapproach.png
/WebSocket.js
/wifi.html
================================================================================= [SUCCESS] Took 4.15 seconds ================================================================================= *  Terminal will be reused by tasks, press any key to close it.

**Comment by chunkysteveo** [comment]
have you uploaded the new image? Clicked the "Upload" button in Platform.io? Right arrow in the small blue bar at the bottom?

**Comment by SchallertDK** [comment]
No :/
I thought i was uploading by the "upload filesystem image"
But damn. Now it works
Thank you so much

**Comment by chunkysteveo** [comment]
RTFM - as some would say!! lol

So it's now pulling into HA as a device and entities are present for you to add as sensors in the lovelace UI?

(Building and uploading the filesystem is only updating the HTML website part of the device. The actual running code is uploaded separately using the Build/Upload command in Platform.io).

**Comment by SchallertDK** [comment]
Yes, everything seems to communicate :)
Is it possible to make the pump planning in HA, just like you can do in the "spa config" at the browser?

**Comment by chunkysteveo** [comment]
Awesome news!!

It could be possible with some automations - I suspect your knowledge in Nodered may be better for scheduling things? I know in HA Automations there are date and time triggers, so you could set things up - it would be quite complex I suspect?! See if anyone has done any "Climate/Thermostat Scheduling" and use that as inspiration to set the Spa climate...?

**Comment by SchallertDK** [comment]
Thank you for everything
I will see som youtube videos to get som inspiration
