### ISSUE TITLE
error: 'HASAIR' was not declared in this scope

### ISSUE THREAD

**Issue by olskar** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#344]
When trying to compile latest relase I get this error; 
```
error: 'HASAIR' was not declared in this scope
```
This is with NO54213 defined in models.h

I guess this is a recent change cause I have been able to compile release from end of may fine :)

**Comment by chunkysteveo** [comment]
Master or Dev branch?

**Comment by olskar** [comment]
That did the trick :) Saw you had another pullrequest about HASAIR, perhaps this could be added to

**Comment by olskar** [comment]
I see, my model is true :)

**Comment by olskar** [comment]
Solved in 3.4.0 :)
