### ISSUE TITLE
Web GUI not working!

### ISSUE THREAD

**Issue by Hampchamp** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#350]
Hey 

Ive done everthing the guide said and uploaded the code on a nodemcu. It boots up as a Access point and i type in wifi. Then it connect to wifi but Web Gui seems like it didnt install. I also tried it in my SPA and it worked. Just wont get UI working. 

Serial monitoring says this then i connect to it via IP in Goolge chrome : 
HTTP > request: /
HTTP > file not found: /index.html
HTTP > request: /favicon.ico
HTTP > file not found: /favicon.ico

My experience with coding and vs stuidio is kinda low. Done a few arduino project before skills are limited.

**Comment by SigmaPic** [comment]
Tout missed that 

![Screenshot_20220720-121327.png](https://user-images.githubusercontent.com/2431226/180489162-796a5dd0-33cc-4bb1-a073-b66465d96c86.png)

**Comment by Hampchamp** [comment]
I've read that but brian didn't work I guess 😅 thanks,
It's 100% the my error
