### ISSUE TITLE
Miami Pump 54123 PCBv1 with 6 wire 

### ISSUE THREAD

**Issue by dennixone** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#356]
Hi Guys i have pump 54123 compiled with PCB v1 and NO54123 in Model.h and 6 wire version.

Pump Turn on but Display Buttons dont work.
ESP is connected to WiFi but i cant Turn on over the Webinterface maybe my pump Miami 54123 is not supported?

H1 is Male
H2 is Female

Can anyone Help? I am from Germany 

Thanks

![IMG-20220806-WA0003.jpg](https://user-images.githubusercontent.com/79036984/183262723-014576d0-78d9-4a73-84fb-f9313fe62203.jpg)
![IMG-20220806-WA0005.jpg](https://user-images.githubusercontent.com/79036984/183262725-78b552c8-1314-4127-9396-7c3432c260ef.jpg)

![Screenshot_20220806-210535_WhatsApp.png](https://user-images.githubusercontent.com/79036984/183262823-e1357891-7a59-4b93-ac8c-dc571843e7d6.png)

![IMG-20220806-WA0004.jpg](https://user-images.githubusercontent.com/79036984/183262892-3ccd3d2b-a8ff-4686-b7d9-f9bdad0f0b25.jpg)

**Comment by visualapproach** [comment]
Hi there! Can't help you with your nationality, but NO54123 is not an option in the 6-wire version. You need to choose PRE2021 :)

**Comment by dennixone** [comment]
Thanks you i will try later ✌️👍

**Comment by dennixone** [comment]
Amazing it works very nice i modified index.html to disable airjet :)

![Screenshot_20220807-131747_Firefox.png](https://user-images.githubusercontent.com/79036984/183288033-5abc13fe-a418-403a-8872-d7aec675d4e4.png)
