### ISSUE TITLE
New graphics

### ISSUE THREAD

**Issue by prose-rgb** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#38]
I may be overreacting (not a lawyer) but these look very similar to the graphics used by Bestway on the pump and in documentation. I fear you'd be leaving yourself vulnerable to takedown requests sometime in the future by having these in the repo and it might even warrant a force push to an older commit to remove them :(

**Comment by visualapproach** [comment]
@prose-rgb hmm, maybe you are right. I wouldn’t want that. I’ll remove them again. Sorry Jack

**Comment by visualapproach** [comment]
Thanks for the heads up @prose-rgb
