### ISSUE TITLE
MQTT reporting zero energy values at restart

### ISSUE THREAD

**Issue by strutings** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#390]
Is there any way to fix zero reported energy values when ESP is restarted?

**Comment by visualapproach** [comment]
Elaborate. Version, model, reported to what...?

**Comment by strutings** [comment]
Miami 2021 running firmware version 2022-05-24. Reporting to HomeAssistant.

**Comment by visualapproach** [comment]
Try latest dev version. If you still have problems you're welcome to describe the issue in more detail.

**Comment by strutings** [comment]
Is it possible to update firmware without loosing setting and historic values? Is it possible to do OTA updates by uploading the whole zip-file?
