### ISSUE TITLE
Massage sequence

### ISSUE THREAD

**Issue by eried** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#393]
Hi, I was thinking on a feature that might be useful for the bubbles in the airjet models, since I never use this feature because is noisy and too chaotic BUT what if you could program a sequence of pulses and pauses... For example 1s on, 2 off , etc or even more relaxed just to aireate the water, 1s on, 20 off

It sounds gimmicky but the noise level vs the bubbles is quite comfortable if you try doing it manually.

**Comment by visualapproach** [comment]
Hi. In principle you can already do it by adding commands with interval.
Air ON @time x, interval 20s
Air OFF, @time x+1, interval 20s
Maybe not the most practical thing from the web gui but you could make a script in homeassistant if that's an option.
