### ISSUE TITLE
Nothing works with weak wifi signal

### ISSUE THREAD

**Issue by hubaksis** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#395]
Firstly, thank you for the wonderful hack!
Remote control really helps me to save on controlling the SPA remotely and keeping it running during the cheap electricity times.

Now, the question. I moved the unit to another location. Had to turn it off for a couple of hours. When I turned the unit back on - I can hear the melody, sometimes I can see the IP address, sometimes the screen is just blank. The unit is not responding to any buttons. Sometimes I can see the display is changing from 36 to 20 and then stops. 

I run a continuous ping and figured out that the connection is really unstable. My unit is basically 3 meters from the router, however, RSSI is -75 - -80. 
I think I need to add a repeater closer to the unit. 
In the meantime, do you think that the unit should respond to the manual control if it failed to connect to WiFi or lost the connection?

Thanks again!

**Comment by visualapproach** [comment]
You are welcome @hubaksis, check if the Wi-Fi portal has started by looking for its SSID. The device is supposed to work without Wi-Fi but if you configured the portal to be automatic then it will break the comms. If that's the case you can turn it off in the config file
