### ISSUE TITLE
Virtual Temp in Fahrenheit is wrong

### ISSUE THREAD

**Issue by RetroVape** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#396]
Looks like the virtual temp for Fahrenheit is being converted incorrectly?

![image](https://user-images.githubusercontent.com/116229216/197921171-1debf27b-c7ee-48f3-9797-bd9b46e17b55.png)
![image](https://user-images.githubusercontent.com/116229216/197921211-2d0d2ef7-a08b-4ac8-86ee-0ee839561127.png)

**Comment by visualapproach** [comment]
Does it show the wrong value when flipping back to F again? My device does not do that when I test. What FW version do you have?

**Comment by visualapproach** [comment]
You can try uploading `WebSocket.js` file from the data/ folder. Just download it from the dev branch and upload it via the web GUI file uploader menu.

**Comment by RetroVape** [comment]
Same result after uploading the latest WebSocket.js

bottom of the web page says firmware version 10-8-22.

**Comment by visualapproach** [comment]
Can you expand the STATES message and post here?
![image](https://user-images.githubusercontent.com/22987250/198119971-30acfb86-2213-44d4-8c93-441043cfdb02.png)

**Comment by RetroVape** [comment]
![layzspa](https://user-images.githubusercontent.com/116229216/198155806-24e80518-b49d-4c81-a116-947bdb5fa87d.png)

**Comment by visualapproach** [comment]
I wonder if it is related to a unit-press on the real display maybe. Don't know but I'll look at it in a few days when I get the time.

**Comment by RetroVape** [comment]
Going off you last comment, I did change that from the control panel when I first setup. 

Switching back and forth in app and control panel didn’t do anything. However, I put it into C and then restarted the esp, and that did it. I am now reading correct.

**Comment by visualapproach** [comment]
Okay that's good. Hard to know what went wrong. I set mine to F and restarted and it still works.

**Comment by RetroVape** [comment]
haha whiplash, just checked it, back to 217.

**Comment by RetroVape** [comment]
DO we need to run it with the pump on but heater off for a while to get a base line?

**Comment by RetroVape** [comment]
Wondering if it jumps up like that when it goes through a heating cycle, I will turn off the heater to let it cool and watch it after I turn it back on.

**Comment by RetroVape** [comment]
Well that was fast, no, it just jumps back up after a while.

**Comment by visualapproach** [comment]
Can you upload the latest dev version so we have same base plz

**Comment by visualapproach** [comment]
> DO we need to run it with the pump on but heater off for a while to get a base line?

To calibrate rate of cooling, yes, and you need to let it cool by at least 2 degrees, and not at ambient. But it shouldn't cause this error.

**Comment by RetroVape** [comment]
Ok I will do the dev branch

**Comment by RetroVape** [comment]
I installed the dev branch, it was fine until I reconnected the mqtt connection!

**Comment by RetroVape** [comment]
this is the only automation I have, otherwise it’s just vanilla mosquito broker.

alias: "Update Layzspa ambient temperature "
description: ""
trigger:
  - platform: state
    entity_id: sensor.openweathermap_temperature
condition: []
action:
  - service: mqtt.publish
    data:
      topic: layzspa/command
      payload_template: >-
        {"CMD":14,"VALUE":{{ states("sensor.openweathermap_temperature")|round
        }},"XTIME":0,"INTERVAL":0}
mode: single

**Comment by RetroVape** [comment]
Installed the dev branch, seems to still be doing it.

**Comment by RetroVape** [comment]
Just does it after a little time. After 5 minutes it switched without changing the ambient.

I didn’t even realize the significance of the number, but it is doing the Celsius to Fahrenheit conversion again…

**Comment by visualapproach** [comment]
Can you post your `settings.txt`? (menu/directory - click on settings.txt)

**Comment by visualapproach** [comment]
Never mind, I managed to reproduce the fault. Only thing left is to find out wth is wrong... Wait a moment please

**Comment by visualapproach** [comment]
Fix uploaded to dev.

**Comment by RetroVape** [comment]
Dude thank you! I really appreciate it, this is a great project!

I will be able to test it tomorrow.

**Comment by RetroVape** [comment]
I am back up and running and looks to be working. 

Took me awhile, I think I killed my esp in the process. Every time I would reset the esp it would get stuck with an exception I think on boot, at least that is what the serial monitor said. On whim I uploaded to a new esp and everything seems to work.

I really appreciate the quick fix!

**Comment by RetroVape** [comment]
No on to automating the pump while not heating. That is what I plan to do with this feature, was that the intent?

**Comment by visualapproach** [comment]
I also got boot resets after an OTA upload. When using USB it worked with the same exact code. I think VSC compiles wrongly sometimes (there is a thread here about that somewhere) or maybe there is a bug in the ESP or something.
The intention was to get an idea of the real temperature when pump is off, and to get finer resolution if possible. I was thinking you could get a more accurate temp keeping also, instead of +/- one degree, it can potentially be +/- 0.1 or so.

**Comment by RetroVape** [comment]
Thanks!
