### ISSUE TITLE
MQTT discussion

### ISSUE THREAD

**Issue by visualapproach** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#4]

**Comment by visualapproach** [comment]
@faboaic what is the best format to send data to broker?
topic - "pool", payload - "JSON data with all parameters"
or 
topic - "pool/heater", payload - "on"
repeat for every parameter.

**Comment by faboaic** [comment]
I think the second one...

See how Tasmota is doing it:
https://tasmota.github.io/docs/Commands/

Pretty clever... Empty payload means query the status or value...
And with payload it is used to set / execute the command.

**Comment by visualapproach** [comment]
Yeah, I'm gonna send you a test-kit by email. I preferred to keep it similar to the websocket stuff, to reuse some code.

**Comment by faboaic** [comment]
Sounds good  👍

I tried to make some little changes to control the pool  via websockets.
It seems to work somehow but I need to send the command twice.... Strange.

So if every necessary functionality has a dedicated function in the code we could call that function within websockets (like I tried with F1, F2 and F3 ).
Same with MQTT, web request, etc.

![IMG_20200823_210029](https://user-images.githubusercontent.com/42912090/90986619-8b13dd00-e584-11ea-8351-d518853e80ef.jpg)
![IMG_20200823_210047](https://user-images.githubusercontent.com/42912090/90986621-8c450a00-e584-11ea-9d88-c3e819f098d6.jpg)
![IMG_20200823_205938](https://user-images.githubusercontent.com/42912090/90986622-8cdda080-e584-11ea-9c7b-4ca5bf0294c4.jpg)

**Comment by visualapproach** [comment]
No you should set virtualBTN to HTR and virtual_cmd to 1 to force it on. The turnheateron () function is non blocking and has to run several times until the device is unlocked.

**Comment by visualapproach** [comment]
You didn't reply fast enough by email @faboaic  ;-) Maybe wrong adress. I changed my mind and made a new branch and uploaded my embarrasing attempt on mqtt as a parallel version. You have to edit the broker in a_globals. Hope for the best!

**Comment by faboaic** [comment]
Thanks so much.
Will give it a try tomorrow evening.
Holiday is over, now  :-(

**Comment by 877dev** [comment]
Hi all,

Has any progress been made on MQTT integration? I see reference to a MQTT version but can’t see the code.  

I will maybe look at it myself if not :)

**Comment by faboaic** [comment]
> Hi all,
> 
> Has any progress been made on MQTT integration? I see reference to a MQTT version but can’t see the code.
> 
> I will maybe look at it myself if not :)

Check the branch.
Maybe you looked inside the master?

**Comment by faboaic** [comment]
I am so sorry that I still had not found the time to compile and install the mqtt-test version.

**Comment by 877dev** [comment]
> Check the branch.
> Maybe you looked inside the master?

Yup :) 
Same I have been busy, I will give it a try this week!

**Comment by 877dev** [comment]
> @faboaic what is the best format to send data to broker?
> topic - "pool", payload - "JSON data with all parameters"
> or
> topic - "pool/heater", payload - "on"
> repeat for every parameter.

Personally I prefer a JSON message, it's all send in one and easy to parse to get the required topic: 
![image](https://user-images.githubusercontent.com/46575282/92401187-15337800-f125-11ea-8448-b1e5f8c31346.png)

**Comment by visualapproach** [comment]
> > @faboaic what is the best format to send data to broker?
> > topic - "pool", payload - "JSON data with all parameters"
> > or
> > topic - "pool/heater", payload - "on"
> > repeat for every parameter.
> 
> Personally I prefer a JSON message, it's all send in one and easy to parse to get the required topic:
> ![image](https://user-images.githubusercontent.com/46575282/92401187-15337800-f125-11ea-8448-b1e5f8c31346.png)

Hi, maybe you should hold on just a little while to save you from doing too much work. My next version is under testing now and I use JSON more which might make mqtt conversion easier. If it behaves (doubt it) I might be able to post it tonight.

**Comment by 877dev** [comment]
Cool, no problems I am enjoying look at the code anyway. I know it will be superseded but maybe I will understand more then! :)

**Comment by 877dev** [comment]
This is my standard template I use for all my projects, and adapt as needed....

https://github.com/877dev/MQTT_example_template

Probably this is not much use, but as you said you are not familiar with mqtt it might help. Maybe you might notice an improvement if nothing else :)

**Comment by 877dev** [comment]
> Hi, maybe you should hold on just a little while to save you from doing too much work. My next version is under testing now and I use JSON more which might make mqtt conversion easier. If it behaves (doubt it) I might be able to post it tonight.

So I have been setting up influxdb and grafana over the last few days, after adding it to my [IOTstack ](https://github.com/SensorsIot/IOTstack)setup.

Definately json object messages are the way to go in my opinion, it's so easy to split payloads, but much harder to combine them all in node red.

Now I am going to look at how Arduino pubsub would be used to send a json payload, and finally will get around to trying to add it to the 1.27 version.

I've held off for now as my family will be upset if the hot tub glitches out and doesn't heat for some reason! :)

**Comment by 877dev** [comment]
Ok I have added MQTT to the 1.27p1 code, currently it just publishes all json data to MQTT broker.
I will look at adding callback next.

But...I don't know how to submit the code for you to look at :)
How about this: https://www.dropbox.com/s/hc4fao9xpr71efg/ESP12E_Bestway_controller_v1.27p1_mqtt.rar?dl=0

**Comment by visualapproach** [comment]
I’ll have a look at it 👍

**Comment by 877dev** [comment]
I made some small changes, seems the mqtt library got updated with new features and set buffer size is now a function.
https://www.dropbox.com/s/k1eeb61iqrw3fyx/ESP12E_Bestway_controller_v1.27p1_mqtt_v002_public.rar?dl=0

For mqtt callback, there could be a "mqttCallback" function similar to "webSocketEvent" which goes through the cases. 

Or could we have :
Either "webSocketEvent" or "mqttCallback" function receives the message.
Gets passed to a third function which compares the message and update variables.
Then "sendWSmessage" could be renamed to "sendMessage" for example, as it just regularly updates websocket and mqtt.

Whatever you think it best of course :)

**Comment by 877dev** [comment]
Here's my attempt at full control with mqtt, including a test flow for node red. 
https://www.dropbox.com/s/hsn5vcygwdw4wyy/ESP12E_Bestway_controller_v1.27p1_mqtt_v003_public.rar?dl=0

`[{"id":"6561cda5.524294","type":"mqtt in","z":"be5275e8.e06c78","name":"","topic":"BW-1.27p1_MQTT/message","qos":"1","datatype":"json","broker":"","x":250,"y":120,"wires":[["7d61d966.e6b038"]]},{"id":"7d61d966.e6b038","type":"debug","z":"be5275e8.e06c78","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":540,"y":120,"wires":[]},{"id":"5f5aa4ec.eebdcc","type":"mqtt out","z":"be5275e8.e06c78","name":"","topic":"BW-1.27p1_MQTT/command","qos":"1","retain":"","broker":"","x":530,"y":220,"wires":[]},{"id":"3bb3478b.302cb8","type":"inject","z":"be5275e8.e06c78","name":"0xA heater","topic":"","payload":"\"0xA\"","payloadType":"bin","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":210,"y":220,"wires":[["5f5aa4ec.eebdcc"]]},{"id":"bfe22e0c.eeef2","type":"inject","z":"be5275e8.e06c78","name":"0xC air","topic":"","payload":"\"0xC\"","payloadType":"bin","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":270,"wires":[["5f5aa4ec.eebdcc"]]}]`

**Comment by visualapproach** [comment]
The Switch/Case statements in WSevents and MQTTevent can definitely be refactored to a new 
void executeCommand(int command){}

**Comment by visualapproach** [comment]
> PS - finally once we are happy it's working, could there be a define statement to enable the mqtt code, so it could be merged into the main branch at some point?

I hope so, or better - selectable from AP portal

**Comment by 877dev** [comment]
Morning, I've been testing this for a few days and it seems stable, it works with both websockets and mqtt and is very responsive. Also included a sample flow with all the commands.

https://github.com/877dev/WiFi-remote-for-Bestway-Lay-Z-SPA

**Comment by visualapproach** [comment]
Morning, I've been busy a couple of days now, and haven't been able to do much of this, but I'll check it out. Just need more free time :-)
I just tested your "...mqtt_v003_public" version and it is slow when loading pages. Maybe it works better when there exists an MQTT broker and it doesn't try to reconnect all the time?

**Comment by 877dev** [comment]
No worries, I have a lot of free time for some reason, it's not normally the case :)
I think it would be because you have no broker, as it runs fine for me.

OK, I feel you are interested in mqtt and want to get started! :-) To dip your toes try this software I use, and use a public MQTT broker:

1) Download MQTT explorer: http://mqtt-explorer.com/
2) Setup like this and connect:
![image](https://user-images.githubusercontent.com/46575282/93663289-bfcd6400-fa5e-11ea-84fb-610e46683743.png)
3) In your Arduino code, set the base topic to something unique you can search for.
4) Use as per below:
![image](https://user-images.githubusercontent.com/46575282/93663466-24d58980-fa60-11ea-8767-928de371d786.png)

**Comment by visualapproach** [comment]
Cool! I will dip my toe, but if its too cold I will jump back to the sauna ;-)
I think I figured out the unresponsiveness now. I'll upload an update. It seems to work. I'll explain later, got to go now...

**Comment by 877dev** [comment]
Great, catch you later!

**Comment by visualapproach** [comment]
The problem was that mqtt.connect() takes some time. Say a second - I don't know the timeouts and stuff. Which, when repeated every loop,  blocks the main loop from executing wifi stuff fast enough. It needs to loop fairly quickly. So when I put that mqtt checking in the minute timer everything loaded fast. 
So, I'm thinking, if possible have one version with optional web interfaces by #defines as you seem to like ;-). I'll work on it another day if I don't get any good pull reuests before that ;-). I don't think I wanna scrap the mqtt web interface if it works (which I think it does). I imagine it would be nice to change for instance the IP or password to the broker from my phone instead of recompiling and uploading.
One small release note on the latest version: I had to add "mqtt" in the JSON message for the web interface to update properly. I forgot that in the earlier test versions. Maybe that affect your node red voodoo...
Cheers!

**Comment by visualapproach** [comment]
> Note this is public, so in theory someone internet wierdo could turn on your bubbles :)

Lol, yes that would be weird, but I guess it's a risk one has to take in order to learn.

**Comment by visualapproach** [comment]
Hey - some weirdo (me :fearful:) restarted my ESP from the MQTT explorer

**Comment by 877dev** [comment]
Hey again, your message from 2 days ago did not pop up in my mail for some reason, strange.

I take it you got it working with the test broker then, cool. For me though, I just uploaded BW_1.28 and it does not connect to the broker, or the web interface I'm afraid.

I'm looking now to see if there's anything I notice..

**Comment by visualapproach** [comment]
Because you cannot run mqtt.connect() every loop because it stalls the rest, like wifi handling. So only check every minute.

**Comment by visualapproach** [comment]
@877dev  Did you enter your credentials in user_parameters.h?

**Comment by 877dev** [comment]
I know what you are saying, but I'm pretty sure mqtt.connect() has to be in the main loop. 
I think it's responsible for checking callback messages, publishing other connection data. So that would grind to a halt.

In my [test version](https://github.com/877dev/WiFi-remote-for-Bestway-Lay-Z-SPA/tree/master/ESP12E_Bestway_controller_v1.27p2_mqtt_v002) it is in the loop, and is working perfectly with both MQTT and the web interface.

I can only think the MQTT web interface is causing the issue.
Plus I still think there is no need for that, as changing mqtt brokers is as unlikely as moving home (most people have tens if not hundreds of devices connected to the broker).

Could you try my code and see what you think maybe?

**Comment by 877dev** [comment]
Uploaded public broker version for you to try, you might want to change the base topic to something unique.

**Comment by visualapproach** [comment]
I disagree with you sir, but thats okay. Let me state what I think. I don't mean to be rude or claiming to know what you are thinking of, but here goes:
It only stalls when it doesn't find a broker.  
` if (!MQTTclient.connected())   {  MQTT_Connect(); }`
This means, (probably kicking in open doors here) that if there is NO connection then execute MQTT_Connect().
Doing so slows down the loop too much. 
The reason it works in your loop is because it finds the broker and does NOT execute MQTT_Connect().
The  MQTTclient.loop() however is probably what you mean by checking callback and stuff, and that has to be executed as often as possible.

Now I am running v1.28 and it works perfectly good on my end and I can see it on MQTT explorer....

**Comment by 877dev** [comment]
Oops yes you are correct! I am a little distracted at the moment and did not realise what I was typing.  Yes I meant client.loop(). Kicking in open doors, lol!

I see now what you are intending with `checkMqttConnection`.

But still the 1.28 code did not work for me, maybe I will try after I have eaten 🍔

**Comment by visualapproach** [comment]
Haha, I know the feeling. I'm running against mqtt.eclipse.org as you showed me. I still have to test against a local IP adress to be sure, but my fresh install on the RPi is taking forever to update something... I might try a windows mqtt server if available and easy to understand.

**Comment by 877dev** [comment]
If you are installing on a Pi, I cannot recommend this enough:
https://github.com/SensorsIot/IOTstack
It's so easy to install mosquitto broker, node red etc.. Maybe you could join the dark side :-)

**Comment by visualapproach** [comment]
My guess to why it doesn't work for you:

You defined all features to be compiled (good)
Then you entered your credentials in the code.
Then the program loaded an earlier version of saved mqtt settings from LittleFS.

If that's the case, just reenter the settings via mqtt webpage and it might work.

**Comment by 877dev** [comment]
Maybe, I might try uploading and erasing all data, set up from fresh.

I can't upload LittleFS OTA with pasword enabled, are you able to?
![image](https://user-images.githubusercontent.com/46575282/93792256-328c3a00-fc2d-11ea-9867-e4a20b4fec14.png)

**Comment by visualapproach** [comment]
No but you can upload an empty mqtt.txt file via IP/upload.html

**Comment by 877dev** [comment]
> Also, the topic and client ID is changed to the version name ("BW_1.28"), not only to make your life more painful but for me to be able to change version name in ONE place only.

Yes I noticed that  😢 😄 

Web page not loading at all, and no mqtt. I don't understand why the files can persist, when they are being overwritten?

Maybe it's time to flash and erase all.

**Comment by visualapproach** [comment]
Flash mem on the 8266 is divided into several partitions. When uploading the sketch it never touches the file system.
I updated the firmware on my wifi router today and it decided to give all units new IP numbers. You can read the pump display just to be sure...

**Comment by 877dev** [comment]
I was not clear, I do understand that part. But I'm not sure why the web interface is not loading, and wonder if it's something in LittleFS partition. But I just overwritten all that...

**Comment by 877dev** [comment]
Erm ok this is all I can get:
![image](https://user-images.githubusercontent.com/46575282/93798498-b1857080-fc35-11ea-8caf-fb371098d48b.png)

**Comment by visualapproach** [comment]
It works if you upload another sketch? Tried on another ESP?

**Comment by visualapproach** [comment]
I finally got mosquitto installed on the old Pi and it is working with the SPA. Hope you sort it out.

**Comment by 877dev** [comment]
I'll try tomorrow on my test rig, not having much luck on my main. Strange as the older code flashes fine.

**Comment by 877dev** [comment]
Ok I have it connecting to mqtt broker, only when I comment out `#define USE_MQTT_WEBINTERFACE` or more.

For some reason I just cannot OTA upload the 1.28 LittleFS data to my[ Wemos D1 mini Pro](https://docs.wemos.cc/en/latest/d1/d1_mini_pro.html). It just hangs, and never shows the uploading dots....

The reason for using the D1 mini 'Pro' is the external antenna for the Wifi. I assume others with the normal D1 mini would have the same issue.

It's probably something I am doing wrong, but for now I can't figure out the LittleFS problem..

**Comment by visualapproach** [comment]
@877dev Hi again, how is it going?
I bought a brand new RPi4B, installed Docker and IoTstack, and now I have Node red up and running. It works fine with all features running on ESP. Including web configurable MQTT settings. My goal is to be able to log on to some sort of control page from anywhere via the RPi, but i feel that's gonna take some time. Every step I take is uncharted territory for me.

![node red](https://user-images.githubusercontent.com/22987250/94278733-7c399500-ff4b-11ea-9127-eadb04fb9bf9.png)

**Comment by visualapproach** [comment]
hmm I saw your alias in the docs for IOTstack :smiley:

**Comment by 877dev** [comment]
@visualapproach hey how's it going? Glad to see you've joined the club, it will be nice to have another person to chat to :)
Good you've got it all working, I'm taking a break for a few days to work on the IOTstack Blynk integration, also uncharted territory! 

Why do you want a control page when you already have the web page? I used Blynk for my front end, there's a set of nodes by Gablau, I can share some flows if that appeals.

PS if you set the mqtt nodes to parsed json and the debug nodes to complete msg it comes out a bit neater :-)

**Comment by visualapproach** [comment]
@877dev 
> Why do you want a control page when you already have the web page?

Primary answer I guess is “because why not”. I’m happy with the web page interface but I’m not fond of opening up ports 80/81 through my firewall to be able to use it beyond the reach of my WiFi. There is no real need for me to check the pool from everywhere but it would be nice. (Actually I can but it requires me to remote control one of my home computers)

> I used Blynk for my front end, there's a set of nodes by Gablau, I can share some flows if that appeals.

That wouldn’t hurt, thanks.

**Comment by 877dev** [comment]
@visualapproach thats why I use Blynk cloud version, and forward the MQTT to that in node red. No need to port forward, although I have been working the last few days on the local Blynk server.  

Moving the tub soon so I will flash your latest via usb cable and see if that works.

**Comment by Naesstrom** [comment]
Anyone tried combining this mqtt flow with [Home-assistant](https://www.home-assistant.io/)? Still waiting for my last parts for the controller so can't try it myself!

**Comment by faboaic** [comment]
Have version BWC_v1.28 up and running with MQTT.
Seems to work reliably.

One thing I am missing is MQTT commands that I could send with functions like:
Turn off heater
Turn on heater 
( regardless if locked or unlocked... Or heater already running or not, powered on or off.... Don't care. Send command and afterwards Spa is on and heater is heating. )

This would really help with photovoltaics overproduction pushing into the spa  :-) 

It might be helpful to have a collection of functions that we could set (by pulling on an external GPIO, by MQTT command, by websocket, by http request, by some kind of rule, by whatever).

**Comment by visualapproach** [comment]
> Have version BWC_v1.28 up and running with MQTT.
> Seems to work reliably.
> 
> One thing I am missing is MQTT commands that I could send with functions like:
> Turn off heater
> Turn on heater
> ( regardless if locked or unlocked... Or heater already running or not, powered on or off.... Don't care. Send command and afterwards Spa is on and heater is heating. )
> 
> This would really help with photovoltaics overproduction pushing into the spa :-)
> 
> It might be helpful to have a collection of functions that we could set (by pulling on an external GPIO, by MQTT command, by websocket, by http request, by some kind of rule, by whatever).

Could you elaborate on the last paragraph please?

**Comment by faboaic** [comment]
> Could you elaborate on the last paragraph please?

Like I tried in August:
https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/issues/4#issuecomment-678812168

E.g. have a function that I can call which turns on the heater. 
In my comment from August the "turnOnHeater ()" function.

Then we could have a list of commands for MQTT that we can trigger.
pool/garden/command/
Payload: heater=on or off

Or have control over the spa my calling website:
http://192.168.1.123/commands/heater/on

My problem was that I did not know what to call to get the desired result ( heater on, no matter if powered off, locked, etc)

**Comment by 877dev** [comment]
Why not just send them like this: 
![image](https://user-images.githubusercontent.com/46575282/94919930-3762b080-04ad-11eb-96af-76a999359d20.png)

**Comment by faboaic** [comment]
Does that function 0xA do what I need?

Looks more like a toggle?

    case 0xA:
      //heater
      virtualBTN = HTR;
      heater_cmd = !(heater_red_sts | heater_green_sts);
      break;

But could I add a function heater on ?

    case 0xF1:
      //heater on
      virtualBTN = HTR;
      heater_cmd = 1;
      break;

?

**Comment by visualapproach** [comment]
Exaktly, but it wont unlock or power on automatically. Though I already have functions for that I just have to look. Stby

**Comment by 877dev** [comment]
I would see what @visualapproach says as there is more than likely further reaching implications. I think there is some safety check logic involved in turning the heater off.

I guess a custom could be made...

Trigger node example as an option:
![image](https://user-images.githubusercontent.com/46575282/94920744-c6bc9380-04ae-11eb-8716-d9fa63fab83f.png)

**Comment by faboaic** [comment]
> Trigger node example as an option:

That was exactly what I did with the websockets  :)

From end user point of view (end even more from a remote user or automatic robot like house automation controller) I am only interested in the final result.
No matter what the conditions have been.

I just tell it the desired result ( heater on) and it makes sure that it reaches that target from whatever state that it currently is in ( powered off, locked, or even already heating ).

This is one of the downsides of the original implementation on the Spa....
I want to enable heater on the pump.
I press the heater button... Does not work.... It is locked (hard to see with sun shining on the display)... Need to unlock.... Etc.
(Ok... That's what a lock function is for. But I just want to enable the heater!!!  ;) )

**Comment by visualapproach** [comment]
Programmatically it would be easier to replace the CIO instead of simulating buttons, but then you would have to make all safety features and stuff from the beginning. Anyhow, I uploaded a test to branch "justatest" called v1.29. Command 0x20 to turn ON heater, even if locked or powered off. 0x21 is OFF command. Haven't tested it myself yet. To do what faboaic asks for, for every button you would need to add flags and functions for every button. Or do a complete makeover of the program which I'm not too fond, considering the time it takes.

**Comment by Naesstrom** [comment]
Quick questions about the new mqtt format. Json message is:
`#{"CONTENT": "STATES", "LCK": 0, "PWR": 1, "UNT": 1, "AIR": 0, "GRN": 1, "RED": 0, "FLT": 1, "TGT": 37, "TMP": 38, "CH1": 32, "CH2": 32, "CH3": 32}`
Figured out most of them but what is UNT, CH1, CH2 and CH3

In sending the commands all but AIR uses 0/1 as command but that uses true/false is that correct?

**Comment by visualapproach** [comment]
0/1 is the same as false/true. Temp is taking other values obviously. Ch1 is the first character on the display.

**Comment by Naesstrom** [comment]
Ah so either works when sending the commands, good to know! Doing a page on my home-assistant installation to control and view it! 😄 
![image](https://user-images.githubusercontent.com/6575206/97091418-191b4b00-163c-11eb-9483-70015b9678b8.png)

**Comment by visualapproach** [comment]
May I ask what program you use to make those pretty graphs and buttons in?

**Comment by Naesstrom** [comment]
home-assistant.io running on a raspberry. It has a integrated mqtt broker so I'm sending the data there!

**Comment by bertieuk** [comment]
Having my first go at MQTT, flashed the latest BW2.0 with MQTT, configured to my broker. All working :-)

But, I'm using OpenHAB and trying to add the Spa Control. Have the broker and Spa Control added as 'Things' and both Online, but can't work out how to add values from Spa. Adding a channel it looks like I need topic/value but the spa values are all in a single BW_2.0.0/message string?

**Comment by visualapproach** [comment]
Hi, yes it's a JSON string. I don't know anything about openHAB but check if it can handle JSON.

**Comment by Bankaifan** [comment]
Finally got my MQTT working too. 
Now i am stuck - I want to update my homekit-Information via the mqtt-homebridge plugin.

I have to send this "payload" to update: 
topic: homebridge/from/set
payload: {"name": "pool", "service_name": "heater", "service_type":"Switch", "characteristic": "On", "value": true}

Means... when the payload from BW (should be msg.payload.grn?!) is 1, then characteristic should be on ... 
Any idea from the NodeRed users here?

**Comment by visualapproach** [comment]
![nodered_bankaifan](https://user-images.githubusercontent.com/22987250/100766978-879cb700-33f9-11eb-9413-32eb46c40646.png)

**Comment by Bankaifan** [comment]
That was it, now I see all states in my HomeKit. 
Now there is only one thing left for me - how should the commands send back to the BW, to change a state. 
The old example with the Hex-Values by @877dev dont seem to work (anymore)

**Comment by 877dev** [comment]
Hi, 

I'm in the process of converting my flows across. but visualapproach has included some sample flows in the code download, under node red.

**Comment by visualapproach** [comment]
![nodered_cmd](https://user-images.githubusercontent.com/22987250/101152063-d1b4b100-3622-11eb-8fbe-e016358f6788.png)

XTIME should be the unix timestamp in seconds when the command should be executed. Put 0 for instant action.
The topic is set in the next node as you can see from its name.

**Comment by sjeffrey101** [comment]
@Naesstrom looks like you have made some good progress with home assistant.  Are you able to share your configuration for this?

**Comment by creativtransfer** [comment]
Are there any plans to move the hardcoded MQTT configuration to the WifiManager anytime soon?

**Comment by visualapproach** [comment]
> Are there any plans to move the hardcoded MQTT configuration to the WifiManager anytime soon?

I did that early on but people thought it was unnecessary.

**Comment by creativtransfer** [comment]
Not at all! Would you be so kind and add the mqtt webinterface support to the v2 branch, please.

**Comment by visualapproach** [comment]
> Not at all! Would you be so kind and add the mqtt webinterface support to the v2 branch, please.

I put it on my todo list, but not on top row ;-)

**Comment by creativtransfer** [comment]
Thank you very much!

**Comment by visualapproach** [comment]
@creativtransfer Hi, MQTT is configurable the old way AND via web interface now. If you update code AND upload LittleFS files, there is a link on the index.html to MQTT.html page.

**Comment by creativtransfer** [comment]
Wow, haven't expected it that fast. Thank you very much!

**Comment by peterblumer** [comment]
Hi guys. I’m sorry this isn’t really regarding the topic but I am going mad and it looks like you all understand technical issues more than myself. I have a lay a spa hot tub and it’s connected to my router but is not accessing the internet. It is showing as a device connected device on the router admin but the official app isn’t recognising that it’s connected. I have tried several times and also tried the Bestway app too. It works when I connect to an older router but not on my new one. Do u know if I need to change anything in the router admin settings to allow my pump to connect to the internet? Thanks so much for any help..

**Comment by dwoosnam** [comment]
I'm curious if anybody else has seen some incompatibility with the MQTT config and the latest version of the Mosquitto MQTT Home Assistant add-on?

When I have upgraded to version 6.0.0 or 6.0.1 (Mosquitto 1.6.12) it "breaks" the hot tub MQTT connectivity.

The logs were showing:
`Socket error on client <unknown>, disconnecting`

The changelog for the new version stats the support of "anonymous logons" being removed.

Instead of the add-on configuration showing this:
`logins: []`

I changed it to show this:
```
logins:
  - username: MyMQTTUserName
    password: MySuperSecretPassword
```

and that seemed allow my hot tub to connect to the updated MQTT broker.

I should probably look at trying to obscure the already obscured password as it is now shown there in plain text.

Hope it helps if anyone had the same issue.

**Comment by neildotwilliams** [comment]
> I'm curious if anybody else has seen some incompatibility with the MQTT config and the latest version of the Mosquitto MQTT Home Assistant add-on?
> 
> 
> 
> When I have upgraded to version 6.0.0 or 6.0.1 (Mosquitto 1.6.12) it "breaks" the hot tub MQTT connectivity.
> 
> 
> 
> The logs were showing:
> 
> `Socket error on client <unknown>, disconnecting`
> 
> 
> 
> The changelog for the new version stats the support of "anonymous logons" being removed.
> 
> 
> 
> Instead of the add-on configuration showing this:
> 
> `logins: []`
> 
> 
> 
> I changed it to show this:
> 
> ```
> 
> logins:
> 
>   - username: MyMQTTUserName
> 
>     password: MySuperSecretPassword
> 
> ```
> 
> 
> 
> and that seemed allow my hot tub to connect to the updated MQTT broker.
> 
> 
> 
> I should probably look at trying to obscure the already obscured password as it is now shown there in plain text.
> 
> 
> 
> Hope it helps if anyone had the same issue.
> 
> 
> 
> 

I'm only here to say this helped me 😀

**Comment by strutings** [comment]
I know, but it will still not be sent via mqtt as far as i can see.

**Comment by visualapproach** [comment]
Yes it is sent in topic 'message' content=times Key is 'cost' IIRC in v2.1.4

**Comment by visualapproach** [comment]
Sorry, it's in topic "times"

**Comment by strutings** [comment]
Found it, thanks! Find the reported values a bit strange. I've reset totals and it seems like it starts at 210 when price per kWh is set to 1. 

`Estimated cost: | 210.12`

**Comment by visualapproach** [comment]
Should be fixed now. Dev branch
