### ISSUE TITLE
target temperature at "238" then "20" after ESP restarts

### ISSUE THREAD

**Issue by torei** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#415]
steps to reproduce:
- in "SPA Config" disable the restore of states on startup
- back "Home" and disable all buttons but "Unit" (set this to celsius)
- set target temperature to 38°
- if you want to validate that the state restore is disabled, enable the pump (this should be disabled after startup)
- "ESP Restart"

result:
"Unit" is restored. that is fine - at least in my opinion.
somehow it seems that the startup sets the temperature to +200 = 238 in my case.
after a while it goes down to the minimum value, 20.
issue does not occur on "restore states on startup" enabled.

expected result:
the target temperatur should be restored, like it is usual behaviour in the original firmware (i think)

before restart:
![grafik](https://user-images.githubusercontent.com/6784876/207433639-e81a8549-2967-4927-8dbd-0143770d4160.png)

after startup:
![grafik](https://user-images.githubusercontent.com/6784876/207434363-e1dd6939-daa3-4aae-9e70-ce287ebd5a6e.png)

**Comment by visualapproach** [comment]
@torei I'm looking in to it. I don't get the "238" but it drops to 20 which is not expected/wanted.

**Comment by visualapproach** [comment]
update: I know where the 238 comes from. At startup the pump unit is always F and the ESP is converting 0 F to -18 C. -18 is the same as 238 depending on the variable type is signed or not. Working on...

**Comment by visualapproach** [comment]
This issue, and also the reboot issue should be fixed now. Hope it's working for you too.

**Comment by torei** [comment]
cool, thanks.
will try tomorrow

**Comment by visualapproach** [comment]
I found another strange issue I need to solve. It sets target = actual temp and the physical buttons don't respond for a long time... I will inform when fixed

**Comment by visualapproach** [comment]
Fixed! The pump started in power-off mode sometimes.

**Comment by torei** [comment]
it seems like it is writing the cmdq.txt in every loop.
i guess that somehow the `_saveCmdqNeeded` is not properly set to false when it comes to `_saveCommandQueue()`

**Comment by visualapproach** [comment]
Okay, I'll check

**Comment by torei** [comment]
i think its set by `BWC::_handleCommandQ(void)`

**Comment by visualapproach** [comment]
How do you know that it is saving cmdq.txt? The code looks fine with setting the save flag to false, and it's only called when adding or executing a command. Did you download the code today? I made some changes yesterday after our conversation.

**Comment by visualapproach** [comment]
If you're running it on the bench it will add Gettarget command every 5 seconds or so until it gets a reading. Which won't happen.

**Comment by torei** [comment]
oh okay, i will try to test it on the pump then.
no esp reset on hammering commands works :]

**Comment by visualapproach** [comment]
Great 👍🏼

**Comment by torei** [comment]
how do you debug with a pump attached?
is it possible OTA?

**Comment by visualapproach** [comment]
Depends. You can send info over websockets. Or use a wireless serial but then you'd need to setup that library. Or you can connect a usb but keeping the 5V from CIO and USB separate.

**Comment by torei** [comment]
okay, i cannot test that `_saveCommandQueue()f` for now.
but restart of ESP works fine, looks good :]
thanks for the fix

btw, "Ambient Temperature" and "Brightness" are not restored yet but i bet you have that on your screen.

**Comment by visualapproach** [comment]
> btw, "Ambient Temperature" and "Brightness" are not restored yet but i bet you have that on your screen.

done. Thanks for your help!
