### ISSUE TITLE
Reset Totals: Hydrojets

### ISSUE THREAD

**Issue by AttiMM** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#426]
Hi @visualapproach,
Resetting Totals doesn't reset Hydrojets totals (v3.5.1)
![image](https://user-images.githubusercontent.com/10764890/210212348-4be046a3-62f4-4520-b3db-63714315cbe7.png)

**Comment by visualapproach** [comment]
Got it! Happy new year!
