### ISSUE TITLE
Ready in: Never

### ISSUE THREAD

**Issue by AttiMM** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#429]
Hi @visualapproach ,
It seems to me that Ready in (hours) is not working. 
I started to heating up from 20°C to 39°C. After a lot of hours the current temperature was 35°C but "Ready in:" showed "Never". And so it continued until it reached the target temp.
I always set up Ambient Temp according to the real temp.
Firmware: 2022-12-20 Model: MALDIVES2021 RSSI: -70

See some screenshots.
![image](https://user-images.githubusercontent.com/10764890/211850479-150edb3c-e3a7-4a6f-b8a4-4df8e5784c97.png)
![image](https://user-images.githubusercontent.com/10764890/211850523-70198199-d984-4016-a697-eff7250c6d04.png)
![image](https://user-images.githubusercontent.com/10764890/211850608-28cb47cc-2bb1-4789-9c47-133aab1ecf2c.png)

**Comment by visualapproach** [comment]
It's possible that it's because it's not calibrated yet. To calibrate: let the pump on while cooling a couple of degrees. Keep heater off and don't change anything.

**Comment by AttiMM** [comment]
Hm... I didn't know about the calibration method - I'll try it!

**Comment by visualapproach** [comment]
Also FYI see my discussion post on wip v4
