### ISSUE TITLE
mqtt watchdog

### ISSUE THREAD

**Issue by eried** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#440]
I am having a lot of unstability lately (one of the latest releases). I am not sure if something changed but I was thinking if having a watchdog if mqtt connection is disconnected and reset it. For some reason even the web ui is not accessible too.

I am using 3.5.1, before I was using a very old one. 

Any other advice? the buttons work ok, so I think is just some network issue

**Comment by visualapproach** [comment]
see #439
