### ISSUE TITLE
Best practice for firmware upgrade

### ISSUE THREAD

**Issue by DandeMC** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#442]
Hi,

I asked a while ago, but maybe something has changed since then. What is the best way to upgrade an existing installation to the latest version? I read the following point in the function overview: OTA: Update firmware "over the air". How is the OTA possible? A step-by-step guide would be really great =)

**Comment by visualapproach** [comment]
V4.1 has a new “firmware update” page
