### ISSUE TITLE
3.5.1 4w Godmode not Working

### ISSUE THREAD

**Issue by Jay-Ti** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#452]
On 3.5.1 4w-Version model 54123 activating God mode over the Webpage is not working, the state change is not saved and also not being shown in debug.html, the slider just gets reset.
3.5.0 is working fine.
The whole command send logic is only in index.html, and Websocket,js, right? 
Because I can't discern any changes in those files which could explain this.

**Comment by visualapproach** [comment]
Looking through the diff - there is nothing changed in the 4 wire versions that should affect this. I think the development version4 is stable enough to test if you want.
