### ISSUE TITLE
display not working or showing dim temp but no buttons work

### ISSUE THREAD

**Issue by starsx2016** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#481]
**Hardware (please complete the following information):**
 - Pump model 54123 Miami eggshape pre2021
 -  6 wires
 - PCB type v2
 - Level shifter type red one

**Software (please complete the following information):**
 - Version latest 4.1.1

hi,
since a update to newest version of firmware , display don't work anymore or show very dim the temp and no buttons work but web interface work perfectly. when I plug the cio directly to dsp without the esp it work like it should.

I don't know if it's a power/current issue (may be not enough current to make the display work properly)
do you thing a cap between vcc and gnd could help?

thanks

Matt

**Comment by visualapproach** [comment]
I am working on general stability improvements. Let's see if your problems remain after next update. Not sure when I will upload it. In a couple of days maybe

**Comment by visualapproach** [comment]
Uploaded new code (still named 4.1.1 but with some fixes)

**Comment by starsx2016** [comment]
hi!
still no luck after updating to your bug fix version
![10EC8BCB-D168-4490-9CEB-94FE9785851A](https://user-images.githubusercontent.com/18287109/228641571-d9f3e285-360b-485d-afff-3668429baac8.jpeg)
![4BCEAA75-3123-41A7-A9D8-59D45EB5010E](https://user-images.githubusercontent.com/18287109/228641577-53322f79-0a58-4503-9e7a-77043a7e502f.jpeg)
![76D69C2C-00EB-497F-8943-EC1E084AC28B](https://user-images.githubusercontent.com/18287109/228641580-7f237546-f1d2-4351-9672-f838ec56be26.jpeg)

**Comment by visualapproach** [comment]
Why does it say PRE2021 when you have a 54123?

**Comment by starsx2016** [comment]
it’s 54124 miami (2019-2020) 6-wires

**Comment by starsx2016** [comment]
![8978D2B8-2419-40E0-AD5F-57AC22005422](https://user-images.githubusercontent.com/18287109/228646975-8816f275-2279-4663-a552-5ab02f744a74.jpeg)

**Comment by starsx2016** [comment]
i will give it a try

**Comment by starsx2016** [comment]
I try again the version I had last year and still the same issues, so I check if my pin def. match yours but I notice that my pinout goes like this:

       cio.                             DSP
yours | mine.          YOURS | MINE
5v.     |   5v                5V.     |.    5V
gnd   |   GND.          GND.   |.   GND
D1     |  D7.                D6.     |.   D5
D2    |  D2.                D4.     |.   D4
D5    |  D1.                D3.     |.    D3
NC   |  NC.                D7.     |.    D6

so I can control everything from the web without problem in this config pinout, but display no, but still weird as last year it was working fine on 5.2 with the same pinout.....
where in the code I can change pin assignation?


thanks


Matt

**Comment by visualapproach** [comment]
You set the pinout on the hardware config page, not in the code.

**Comment by starsx2016** [comment]
yeah, I did that but still no luck with 4.1.1 . I made some change to my custom pub (thicker track and shorter) so I'll see when I'll get them in a week...

thanks for now!

**Comment by starsx2016** [comment]
Hi!
problems fixed! with my new pub with thicker tracks and a new llc (red one), everything work fine on latest version on my old pump and on my new square pump (S100104)2021 Tahiti .

thanks for all the good works you done with this!

Matt
