### ISSUE TITLE
Calibrated not checked but virtual temp and time to ready working

### ISSUE THREAD

**Issue by Mr-Groch** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#498]
Hi, I've upgraded from old 3.x version (from 2nd half of 2022) to newest last week. I'v noticed that in web ui "Calibrated" checkbox appeard, that can't be checked manually and it is always unchecked. My virtual temp and time to ready is working quite well. I'm also using HA automation to update ambient temp value. Pump is on 12h daily, in past 5 days I haven't been using lay-z-spa (heater, air bubbles), and Calibration still unchecked...

**Comment by visualapproach** [comment]
Hi. I'll look for potential bugs. Here's some info about the calibration:
Checkmark is designed to show if the automatic calibration is done. You may only uncheck it, to do a new calibration.
Water pump needs to run for 5 minutes or more before calibration starts.
During calibration you may not have/switch on heat, bubbles or jets.
Measured temperature must drop at least one degree.
Water temp must not be same or close to ambient temperature.
Default value before calibration should be in the right ballpark, but intention is to make it as precise as possible with the calibration. Nice to hear you confirming that.

If all of the above is true for you, please tell me.

**Comment by Mr-Groch** [comment]
>Water pump needs to run for 5 minutes or more before calibration starts.

It is working 12h daily (Automation in HA is switching it ON at 8AM and OFF at 8PM) for about 2 weeks now

>During calibration you may not have/switch on heat, bubbles or jets.

I hasn't switched any of it since about 5 days

>Measured temperature must drop at least one degree.
>Water temp must not be same or close to ambient temperature.

This is happening almost every day from about 5PM to 8PM, this is example where temperature dropped 2 degrees when pump was on, and ambient temp was more than 5 degrees lower:

![image](https://user-images.githubusercontent.com/20594810/235160451-dd50b8f0-433e-4dbc-a57e-133a08d2e80b.png)

**Comment by visualapproach** [comment]
Just to be picky: was the heater OFF all the time during temp decrease, or did some automation or maybe a glitch flick it? (Check history for the climate control by pressing the three dots menu)

**Comment by visualapproach** [comment]
I was more interesed in the logbook below the graphs. You don't have to post, just check if heater was turned on during above period.

**Comment by Mr-Groch** [comment]
And longer period, with all my recorder hostory (7 days)

![image](https://user-images.githubusercontent.com/20594810/235165375-f9ad6c9e-432d-4eb4-b89e-72a5a5e78967.png)

**Comment by visualapproach** [comment]
Ah, great, seems like it should work. I'm looking into it

**Comment by visualapproach** [comment]
There was a recent bugfix regarding this from @cobaltfish. Please update to v4.1.2

**Comment by Mr-Groch** [comment]
Yes, that was the case. I've udated to newest release and "calibrated" checkbox became checked an hour later. Thanks!
