### ISSUE TITLE
HW config save

### ISSUE THREAD

**Issue by Sampy3** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#500]
model: S100101
6 wires
Version: 4.1.2

I have a D1 Mini ESP8266, and I think there is a problem with the board's Wi-Fi. When browsing homepage or  othersites, they rarely fully load and there are ping losses. When setting up MQTT, there are no issues and it works normally in Home Assistant. The problem arises when I try to edit the hardware configuration, as I am unable to save it. Is there any option to edit and upload the HW config?

**Comment by visualapproach** [comment]
Preferably the webpages problem should be fixed, but you can make a textfile in notepad or similar.
It should contain a string like this
`{"cio":"0","dsp":"0","pcb":"v1","pins":["7","2","1","5","4","3","6"]}`

Replace cio and dsp numbers accordning to this list, counting from zero
    PRE2021,
    MIAMI2021,
    MALDIVES2021,
    M54149E,
    M54173,
    M54154,
    M54144,
    M54138,
    M54123
Edit pins. You can open the data/hwconfig.html page on your pc/mac an fill in the buttons to see what numbers to use.
Save the file as hwcfg.json and upload that file to the esp by visiting the menu/upload page.

I tested on a D1 mini and the webpages works fine for me.
