### ISSUE TITLE
[BUG]update firmware OTA 2022-08-14 to 4.1 KO

### ISSUE THREAD

**Issue by mulroux95** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#505]
Hi, I have a Maldives 6 wire pump with a V1 pcb and firmware 2022-08-14.  I wanted to switch to the new firmware 4.1 in OTA.  the flashing took place correctly.  however after restarting, the pump remains off but the ESP is still reachable but with the old GUI.  and no action is possible.  I cannot configure the hardware.  I was able to flash the esp in OTA to go back to 2022-08-14 and everything works again but I no longer dare to try new things to upgrade to 4.1.
Thanks you

**Comment by visualapproach** [comment]
Hi @mulroux95 Did you forget to upload the file system maybe? After that is done you can configure everything via the web ui. Like setting the pump model etc. But if you feel uncomfortable upgrading, there is nothing wrong staying on v3.5 :-)
