### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mulroux95** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#506]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hardware (please complete the following information):**
 - Pump model, for example 54123
 - 4 or 6 wires
 - PCB type
 - Level shifter type,

**Software (please complete the following information):**
 - Version

**Additional context**

**Comment by visualapproach** [comment]
Good to know the template works!
