### ISSUE TITLE
PCB_V2 is not working with square S100101

### ISSUE THREAD

**Issue by HercegAndras** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#521]
Hi! 
Wanted to **thank you** for this project, looks very promising!

However it looks not working for me: after connecting the PCB, the square display remained in a kind of turned off state, and the web GUI also shows that the pump and other metrics are missing, switch buttons are not working.

**Spec**:
-pump: Bahamas (square controller, purchased in 2022, JUN, in EU. code: S100101)
-SW version: V4.1.3, just flashed the ESP y-day.
-PCB_V2, TXS0108E, 6 pin JST with resistors (PCB was ordered months ago, so that time the V2 was the latest layout)

**What I did already:**
-Flashed the ESP as it described in the docu via VSCode.
-Setup wifi on webGUI
-PCB option set to V2
-HW config: tried all of the 4 different 6 wire options.
-multiple restarts
-after disconnecting the PCB the square pump works again well, as before.

The result in the first 3 options is the following:
WebUI available but not functional (see screenshot) and the pump controller interface looks like it is in a powered off state, no display/lights. If I press one of the buttons, it plays a short tone. (btw never heard it before)
in the 4th option: not even tone while pressing the physical buttons on the controller.

Any idea how to get it work?
Many thanks!

![20230526_155623](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9865421/085bc890-afdd-4dc0-8e75-aeca55fdd749)
![20230521_113915](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9865421/8c1be8af-5822-4dd6-a651-8ff1bd8e8f2a)
![20230527_100349](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9865421/5d7cafe1-8d9d-4156-8981-432fc76c342c)
![20230527_100435](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9865421/5fd9a5ca-be29-4244-913a-446ac8cb1865)
![20230527_100330](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9865421/82fc740c-a6c3-4ec1-9851-46e323b9c3b2)
![Screenshot_20230527_100319_Chrome](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9865421/0b1ddd73-9f0b-4ce5-b8c1-9f36a056b220)

**Comment by visualapproach** [comment]
Hi @HercegAndras 
Pretty assembled board. The RC filters are supposed to be used with the wires in the B-ports. I don't know exactly how they affect  the signal when connected like this. There is several ways you can try, but I recommend that you first make the hardware test. If it passes you can try moving to the B-ports. Or removing the filters and use A-ports.
You could also connect the data wires (blue red green in picture) directly to the esp pins, and not use the LLC. You have free holes beside the nodemcu.
If you move the wires I suggest that you select PCB_v2B and use that pinout. Doesn't matter that you have earlier pcb if you follow the pinout on the hardware config page.

**Comment by HercegAndras** [comment]
Many thanks for your quick reply and support ideas!
Actually my brother-in-law did the assembly and soldering, he has better equipment and day to day practice:)
Will do the HW test and move the wires to the B section, then post the updates here. Thanks!

**Comment by HercegAndras** [comment]
Finally, it is working!
So the solution is: re-soldering the wires from A ports to B ports, AND using the PCB_V2B pinout!
MANY Thanks!

**Comment by visualapproach** [comment]
Cool, thanks for sharing!
