### ISSUE TITLE
[FEATURE RQ] Expose if ready target is set

### ISSUE THREAD

**Issue by Skeletorjus** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#526]
**Describe the solution you'd like**

I'd love to have a boolean value exposed via MQTT that states if a target time for when the spa should be ready (SETREADY) is active or not. 
I use a script in Home Assistant to send the value of an input_datetime, and I can't seem to find a way to verify that the target time has been set.
The boolean could be used to indicate in the HA UI that a time to ready has been set or even as an interlock to prevent other automations from controlling the heater.

For the curious, here's how to send an input_datetime to the spa:
```
service: mqtt.publish
data:
  topic: layzspa/command
  payload_template: >-
    {CMD:20,VALUE:1,XTIME:{{
    state_attr('input_datetime.layzspa_ready_time','timestamp') | int
    }},INTERVAL:0}
```

**Comment by visualapproach** [comment]
I see what you mean. Will think about it and add it to my todo list. Thanks for the suggestion
