### ISSUE TITLE
Wrong values on reboot through MQTT

### ISSUE THREAD

**Issue by Tops68** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#528]
**Hardware (please complete the following information):**
 - Pump model: 2021
 - 6 wires
 - PCB type: custom (direct wiring)
 - Level shifter type: /

**Software (please complete the following information):**
 - Version 2023-05-19-1021

**Your message**
Hi,
On reboot, I've found that the ESP sends brefly defaults values (not the latest) through MQTT.
This is very anoying because these wrong values make my domotic badly react.
Examples:
layzspa_message_FLT	0
layzspa_message_GRN	0
layzspa_message_RED	0
layzspa_message_AIR	0
layzspa_message_TMPC	-4
layzspa_message_TGTC	-18
layzspa_message_AMBC	20
layzspa_message_BRT	7
Could you improve this behavior?

**Comment by visualapproach** [comment]
There is a 60 seconds delay before first mqtt message is sent after restart. This should be plenty of time for default values to be updated with real values. I fixed a bug that made that delay significantly shorter, but I didn't see your issue before the bug fix. You may try the latest beta to see if it makes any difference.

**Comment by Tops68** [comment]
Don't you think this happens when ESP re-register with mqtt broker?
I'm going to upload the beta firmware for testing...

**Comment by Tops68** [comment]
Issue solved with beta fw... and... great project, very usefull, thank you!

**Comment by Tops68** [comment]
Hi,
Every one hour approximatively, I see in my logs that ESP sends data to MQTT even there is no changes.
Am I wright?

**Comment by visualapproach** [comment]
Depends on how you configed 👍 
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/22987250/46a945a6-d239-4dd2-812f-1f054283f651)

**Comment by Tops68** [comment]
Strange... I've putted 600.

**Comment by visualapproach** [comment]
So it sends every 10 minutes. Possibly HA side is filtering if same message is coming. You can use mqtt explorer (separate windows program) to investigate.

**Comment by Tops68** [comment]
Ok, I'm going to investigate.
Conversely, does "0" mean spontaneous sending is disabled?
