### ISSUE TITLE
[BUG] SETFULLPOWER not working

### ISSUE THREAD

**Issue by Xamude** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#529]
**Describe the bug**
Heater always  heats at full Power (2000W) , seems SETFULLPOWER is not working to set it to 1000W. 

**To Reproduce**
Send over MQTT:
 {"CMD": 18,"VALUE": 0,"XTIME":0,"INTERVAL":0}
{"CMD": 3,"VALUE": 1,"XTIME":0,"INTERVAL":0}
Powermeter says ~ 2050 W Consumption 

no change when i first send CMD:3 and then CMD: 18, always ~2050

**Expected behavior**
Heat with 1000W 

**Screenshots**

**Hardware (please complete the following information):**
 - Pump model, for example 54123: 54173 Maldives (2018)
 - 4 or 6 wires : 4
 - PCB type: V1
 - Level shifter type: The Red one 

**Software (please complete the following information):**
 - Version: Firmware: 2023-05-08-1052

**Additional context**

**EDIT:**
Just do some tests and maybe the Problem is something different:
- Godmode ON: 
   Heater + Filter = ~2100W
   Heater + Filter + Bubbles =  ~2800W

- Godmode OFF:
  Heater + Filter = ~2100W
  Heater + Filter + Bubbles =  ~1800W

so maybe there is a issue how the ESP handles the control of the Pump.

And a different Question:
Turn God ON -> Turn on Pump -> God Off the Pump stops or does what is set before at the Display 
i meant that was different last Year with the old FW ?

**Comment by visualapproach** [comment]
I am working on it. Thanks for a good report

**Comment by visualapproach** [comment]
Please try latest beta version. I think it's fixed now.

**Comment by Xamude** [comment]
Did a short test , Heater running on 1000W :) 
But now i get instant E 13 after ESP Boot. Did 5 resets but instand E 13 :(

**Comment by visualapproach** [comment]
Ok, and it you downgrade to master it works without E13? (You can update to master from web ui)

**Comment by Xamude** [comment]
No :(
{"CONTENT":"OTHER","MQTT":0,"HASJETS":true,"HASGOD":true,"MODEL":"NO54173","RSSI":-76,"IP":"192.168.170.43","SSID":"meins","FW":"2023-05-19-1021","loopfq":2}

loopfq: 2 ? with FW 2023-05-08-1052 it was around 500 

can i flash back to 2023-05-08-1052 do check ob this version run´s again ?

**Comment by visualapproach** [comment]
Oh I thought you came from latest version. I think you only need to resave hardware config

**Comment by Xamude** [comment]
> I think you only need to resave hardware config
Upgraded back to Beta and i think the resave did the Trick 
Heater running at 1000W now.
I´ll give feedback in a few day´s due the E13.

Thanks for the quick fix 👍

**Comment by Snotmann** [comment]
@Xamude how did you get the heater running at 1000 watt ? Did you feed the ESP with mqtt data only ?
