### ISSUE TITLE
[OTHER]Update to latest version from firmware: 2022-12-20

### ISSUE THREAD

**Issue by msggsm** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#530]
Hello,
I have a question about updating my device:
I bought a used Hawaii Hydrojet Pro (new gray square pump) with the ESP8266 PCB_V2B already installed and working.
In the menu i can see that it is Firmware: 2022-12-20 with Model set to: MALDIVES2021,
In the menu I can find the File Uploader, and I found here in FAQs and issues that I would have to upload new firmware AND files.
As I did not set up the device I don't have the files.
Can I somehow backup/download them from the running device or how could I upgrade to the latest version?
Thanks in advance,
Mark

**Comment by visualapproach** [comment]
Hi, the procedure is described in [bwc-manual.pdf](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/blob/master/bwc-manual.pdf)
After you have updated to v4.x you can do the update from the web ui.
