### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JoHo82** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#532]
**Describe the bug**
Ambient Temperature seems to have an issue with Celsius and fahrenheit.

**To Reproduce**
1. set system to Celsius
2. Set AMBC to 10° via MQTT
3. Wifi Remote shows "-12°
4. switch from celsius to fahrenheit 
5. Wifi Remote shows "10°
6. switch back to celsius
7. Wifi Remote shows "-12°
8. See error

**Expected behavior**
when i send the temperature via MQTT, it should be shown in the correct format

**Screenshots**

![grafik](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/50059576/80f0ce5b-550f-4f95-b3c3-ed746c095825)

![grafik](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/50059576/e2913bd2-5976-4a93-bbf4-d838df94af24)

![grafik](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/50059576/9bc79e6c-74e3-4de4-a8fd-63af0c0a721a)

**Hardware (please complete the following information):**
 - Pump model, for example S100101
 - 6 wires
 - PCB type: V2B
 - Level shifter type: TXS0108E

**Software (please complete the following information):**
Current: 2023-05-19-1021
Master: 2023-05-19-1021
Beta: 2023-06-03-0938

**Additional context**

**Comment by visualapproach** [comment]
Hi, please check that you send CMD: 15. If you made the mqtt setup a long time ago it was 14 which is now AMBF.
