### ISSUE TITLE
[BUG] New version small detail

### ISSUE THREAD

**Issue by eried** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#551]
Hei! New version works awesome on my Tahiti 2021 6 wires. I noticed that the sounds (i.e. up and down) do the same sound even if the buttons are locked and nothing is happening. I mean if the intention of the sound is to give some feedback, they should produce no sound or a "locked" sound in this case :)

Btw: What is the notification setting in SPA config?

**Comment by visualapproach** [comment]
Hi there! I can agree with your point.
Notification makes a sound before pump etc starts and stops. More info in the manual.
