### ISSUE TITLE
issue with version 1.28

### ISSUE THREAD

**Issue by starsx2016** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#56]
Hi, I made a pcb with an wemos d1 mini , when I plug my spa (miami 6pins) I got the melody but nothing on the display, I've check voltage on the HV side of the LLC and every line of the CIO and DSP I got 4.96v to 4.99v but the control don't light up and on the web interface no button working. before someone ask I try version 2 as well no luck no chime , no display and web interface not controling anything. I have no idea what's wrong here...  if it can help I'll try to upload pictures.

thanks

**Comment by starsx2016** [comment]
![IMG_5881](https://user-images.githubusercontent.com/18287109/111067804-3aba8900-849c-11eb-9b4b-b8afc52a35cb.jpg)
![IMG_5882](https://user-images.githubusercontent.com/18287109/111067806-3b531f80-849c-11eb-934a-0a459faf4132.jpg)
![IMG_5883](https://user-images.githubusercontent.com/18287109/111067808-3bebb600-849c-11eb-95df-9ad954c7c2ac.jpg)

**Comment by visualapproach** [comment]
Hi there!
First thing I noticed was a lot of cold soldering. Use flux to get better joints. There might be open circuits even if it looks like there is contact.
Next, I see you have a similar LLC as someone else was having problems with in this "forum". Switching polarity on the OE did the trick but I can't remember if it was supposed to be tied to gnd or vcc. But it's in here somewhere if you look around. Maybe closed issues.

**Comment by starsx2016** [comment]
So I swap the wemos d1 mini for an nodemcu clone and I got something on the screen 'have a nice spa' follow by the IP address , then after few second everything goes dim and touch button not work or either on the web interface , so I think my CIO is not able to send command to the esp via the LLC I have so I'll wait for the same as you to be deliver and will see.

thanks for you help and your good work with this project :)

**Comment by visualapproach** [comment]
Thank you and good luck!

**Comment by starsx2016** [comment]
With a new LLC it's working like a treat! :)

**Comment by visualapproach** [comment]
Super! Great work and thx for sharing!
