### ISSUE TITLE
[OTHER] Connection to the s200102 pump (Hawaii Hydrojet Pro)

### ISSUE THREAD

**Issue by DJDeel** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#560]
Hardware 
 - Pump model **s200102**
 - 6 wires
 - PCB type: d1_mini

Hello, I'm not sure how exactly I should connect the wires to d1_mini and what pinouts should be set.

On the website https://antanaitis.lt/ I found information about this setting: Pinout is CIO: 4/3/2 and DSP 7/6/5/0 but it applies to the **S100101** pump. What should be in **S200102**? Same?

I read here about various problems with controlling this pump after connecting. Maybe they are due to improper connections?

![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/138795271/a8e9cafe-6052-4f54-b840-6339cdcce059)

**Comment by DJDeel** [comment]
@visualapproach ?

**Comment by visualapproach** [comment]
In latest versions you don't edit the code. Just set the pinout in the web UI. Suggest you use a level shifter also.
