### ISSUE TITLE
[FEATURE RQ] Update MQTT when filter/chlorine counters are reset

### ISSUE THREAD

**Issue by MattFryer** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#563]
**Is your feature request related to a problem? Please describe.**
I have the module connected to Home Assistant via MQTT and everything is working perfectly with one minor issue. When I press the button in HA to reset either the filter or chlorine counters, HA doesn't display the reset until the next MQTT telemetry push from the module. The module's web interface shows the reset immediately.

**Describe the solution you'd like**
The module should update the MQTT telemetry on reset of either counter. 

**Describe alternatives you've considered**
Now aware of any

**Additional context**
N/A

**Comment by visualapproach** [comment]
Got it thank you

**Comment by visualapproach** [comment]
Fixed (in beta)

**Comment by MattFryer** [comment]
Tested and appears to be working perfectly. Many thanks!
