### ISSUE TITLE
MQTT very slow (only layzspa, rest ok)

### ISSUE THREAD

**Issue by NitramH** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#574]
Dear all,

I have trouble with MQTT. All the rest was checked, I change the electronics to exclude it, no change.

It seems that it takes seconds until a request is processed (like pump on).
With this, a temperature control is impossible and creates a lot of rubbish actions -> not useable any more.

When turning MQTT off at layzspa, control over HTTP is completely ok.

Any idea where to search and how to log? I use Homeassistant on Proxmox VM and did not had problems before.

Thanks for help, I love the project and would be a pitty to kick it out from HA.

Martin

**Comment by NitramH** [comment]
It seems having a look into the HA log, that the spa controller is flooding messages to HA server,
dozen messages within milliseconds

**Comment by visualapproach** [comment]
You can check what messages are sent with MQTTExplorer on a PC. I suspect that something is toggling very rapidly and the ESP feels obligated to report it. It wouldn't generate dozens of messages per millisecond but rather tens of messages per second. You can also check browser/inspect/console if it sends more than one batch of messages per 2 seconds. And what's different between them.

**Comment by visualapproach** [comment]
My guess is that the ESP tries to connect to mqtt broker and fails. What's the mqtt status on the UI page?

**Comment by NitramH** [comment]
The broker is fine since I have 85 entities and all are working.
I will check with mqtt explorer.

**Comment by visualapproach** [comment]
I didn't suggest the broker was bad.

**Comment by NitramH** [comment]
Ah, sorry, misunderstood.

Status is: MQTT connected
Meanwhile i found  doubled MQTT entities in HA. Maybe from old installation which I migrated. But I do not understand why it worked for weeks with no further change.

**Comment by visualapproach** [comment]
No problem. Is the Wi-Fi good?

**Comment by NitramH** [comment]
RSSI -60, is good
MQTT Explorer, every 1s a message arrives.

It seems to be something inside my HA environement. There I found old MQTT entities which seems to point to the same topic two times. But I do not know how to delete, HA refuses it

**Comment by NitramH** [comment]
mqtt:
  sensor:
    - name: Spa Button
      unique_id: sensor.spa_button
      state_topic: "layzspa/button"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    # Number of times MQTT has reconnected
    - name: Spa Connect Count
      unique_id: sensor.spa_connect_count
      state_topic: "layzspa/MQTT_Connect_Count"

    # Spa temperature
    - name: Spa Temperature
      unique_id: sensor.spa_temperature
      state_topic: "layzspa/message"
      unit_of_measurement: "°C"
      value_template: "{{ value_json.TMP }}"
      expire_after: 700
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    # Spa target temperature
    - name: Spa Target Temperature
      unique_id: sensor.spa_target_temperature
      unit_of_measurement: "°C"
      state_topic: "layzspa/message"
      value_template: "{{ value_json.TGT }}"
      expire_after: 700

    # Estimated time until target temperature is reached. Needs two+ temperature changes to make calculation
    - name: Spa Time to Target
      unique_id: sensor.spa_time_to_target
      icon: mdi:clock
      unit_of_measurement: "hours"
      state_topic: "layzspa/times"
      value_template: "{{ (value_json.TTTT / 3600 | float) | round(2) }}"
      expire_after: 700

    # Estimated spa energy usage
    - name: Spa Energy
      unique_id: sensor.spa_energy
      device_class: energy
      state_class: total_increasing
      unit_of_measurement: kWh
      icon: mdi:flash
      state_topic: "layzspa/times"
      value_template: "{{ value_json.KWH }}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      expire_after: 700

    # Time when Chlorine last was added to water
    - name: Spa Cl Added
      unique_id: sensor.spa_cl_added
      unit_of_measurement: days
      icon: hass:hand-coin-outline
      state_topic: "layzspa/times"
      value_template: "{{ ( ( (now().timestamp()|int) - value_json.CLTIME|int)/3600/24) | round(2) }}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      expire_after: 700

    # Time when filter last was changed
    - name: Spa Filter Changed
      unique_id: sensor.spa_filter_changed
      unit_of_measurement: days
      icon: hass:air-filter
      state_topic: "layzspa/times"
      value_template: "{{ ( ( (now().timestamp()|int) - value_json.FTIME|int)/3600/24) | round(2) }}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      expire_after: 700

  # Status of keypad lock
  binary_sensor:
    - name: Spa Lock
      unique_id: binary_sensor.spa_lock
      state_topic: "layzspa/message"
      value_template: |- #"{{ value_json.LCK }}"
        {% if value_json.LCK == 1 %}
          ON
        {% else %}
          OFF
        {% endif %}
      expire_after: 700
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      device_class: lock

    # Status of heater (heating/not heating)
    - name: Spa Heater Element
      unique_id: binary_sensor.spa_heater_element
      state_topic: "layzspa/message"
      value_template: |- #"{{ value_json.RED }}"
        {% if value_json.RED == 1 %}
          ON
        {% else %}
          OFF
        {% endif %}
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      expire_after: 700
      device_class: heat

    # On when temperature has reached a certain threshold
    - name: Spa Ready
      unique_id: binary_sensor.spa_ready
      state_topic: "layzspa/message"
      value_template: |- #"{{ value_json.RED }}"
        {% if value_json.TMP > 30 %}
          {% if value_json.TMP >= value_json.TGT-1 %}
            ON
          {% else %}
            OFF
          {% endif %}
        {% else %}
          OFF
        {% endif %}
      icon: mdi:hot-tub
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      expire_after: 700

    # Spa connection
    - name: Spa Status
      unique_id: binary_sensor.spa_status
      device_class: connectivity
      state_topic: "layzspa/Status"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"
      payload_on: "Alive"
      payload_off: "Dead"

  ## Switches ##

  switch:
    #   Switch for heater
    - name: Spa Heat Regulation
      unique_id: switch.spa_heat_regulation
      command_topic: "layzspa/command"
      state_topic: "layzspa/message"
      value_template: |-
        {% if value_json.RED == 1 %}
          1
        {% elif value_json.GRN == 1 %}
          1
        {% else %}
          0
        {% endif %}
      icon: mdi:radiator
      state_on: 1
      state_off: 0
      payload_on: "{CMD:3,VALUE:true,XTIME:0,INTERVAL:0}"
      payload_off: "{CMD:3,VALUE:false,XTIME:0,INTERVAL:0}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    #   Switch for bubbles
    - name: Spa Airbubbles
      unique_id: switch.spa_airbubbles
      command_topic: "layzspa/command"
      state_topic: "layzspa/message"
      value_template: "{{ value_json.AIR }}"
      icon: mdi:chart-bubble
      payload_on: "{CMD:2,VALUE:true,XTIME:0,INTERVAL:0}"
      payload_off: "{CMD:2,VALUE:false,XTIME:0,INTERVAL:0}"
      state_on: 1
      state_off: 0
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    #   Switch for pump
    - name: Spa Pump
      unique_id: switch.spa_pump
      command_topic: "layzspa/command"
      state_topic: "layzspa/message"
      value_template: "{{ value_json.FLT }}"
      icon: mdi:pump
      payload_on: "{CMD:4,VALUE:true,XTIME:0,INTERVAL:0}"
      payload_off: "{CMD:4,VALUE:false,XTIME:0,INTERVAL:0}"
      state_on: 1
      state_off: 0
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    #   Switch for changing temperature unit
    - name: Spa Temperature Unit
      unique_id: switch.spa_temperature_unit
      command_topic: "layzspa/command"
      state_topic: "layzspa/message"
      value_template: "{{ value_json.UNT }}"
      icon: mdi:temperature-celsius
      payload_on: "{CMD:1,VALUE:true,XTIME:0,INTERVAL:0}"
      payload_off: "{CMD:1,VALUE:false,XTIME:0,INTERVAL:0}"
      state_on: 1
      state_off: 0
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

  ## Buttons ##
  button:
    #   Command to reset chlorine timer
    - name: Spa Reset Cl Timer
      unique_id: button.spa_reset_cl_timer
      command_topic: "layzspa/command"
      icon: mdi:restart
      payload_press: "{CMD:9,VALUE:true,XTIME:0,INTERVAL:0}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    #   Command to reset filter timer
    - name: Spa Reset Filter Timer
      unique_id: button.spa_reset_filter_timer
      command_topic: "layzspa/command"
      icon: mdi:restart
      payload_press: "{CMD:10,VALUE:true,XTIME:0,INTERVAL:0}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

    #   Command to restart ESP
    - name: Spa Restart ESP
      unique_id: button.spa_restart_esp
      device_class: restart
      command_topic: "layzspa/command"
      icon: mdi:restart
      payload_press: "{CMD:6,VALUE:true,XTIME:0,INTERVAL:0}"
      availability_topic: "layzspa/Status"
      payload_available: "Alive"
      payload_not_available: "Dead"

  ## Climate control ##

#  climate:
#    - name: Spa
#      unique_id: climate.spa
#      max_temp: 40
#      min_temp: 20
#      precision: 1.0
#      temperature_unit: "C"
#      modes:
#        - "off"
#        - "heat"
#      mode_state_topic: "layzspa/message"
#      mode_state_template: >-
#        {% if value_json.RED == 1 %}
#          heat
#        {% elif value_json.GRN == 1 %}
#          heat
#        {% else %}
#          off
#        {% endif %}
#      action_topic: "layzspa/message"
#      action_template: >-
#        {% if value_json.RED == 1 %}
#          heating
#        {% elif value_json.GRN == 1 %}
#          idle
#        {% else %}
#          off
#        {% endif %}
#      temperature_state_topic: "layzspa/message"
#      temperature_state_template: "{{ value_json.TGT }}"
#      current_temperature_topic: "layzspa/message"
#      current_temperature_template: "{{ value_json.TMP }}"
#      temperature_command_topic: "layzspa/command"
#      temperature_command_template: '{"CMD":0,"VALUE":{{ value|int }},"XTIME":0,"INTERVAL":0}'
#      power_command_topic: "layzspa/command"
#      payload_on: '{"CMD":3,"VALUE":1,"XTIME":0,"INTERVAL":0}'
#      payload_off: '{"CMD":3,"VALUE":0,"XTIME":0,"INTERVAL":0}'
#      availability_topic: "layzspa/Status"
#      payload_available: "Alive"
#      payload_not_available: "Dead"

**Comment by NitramH** [comment]
Is this still necessary or posted by the ESP (sorry for stupid question, but just to be sure):


# Home Assistant package file for https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA
# Save in packages directory in your Home Assistant configuration directory. Create it if it doesn't already exist.
# Add the following to configuration.yaml:
#homeassistant:
#  packages: !include_dir_named packages

**Comment by visualapproach** [comment]
Remove all yaml references to layzspa. ESP takes care of it.

**Comment by NitramH** [comment]
Removed it. It works but still jittering a lot in Homeassistant. Very crazy behaviour.
I use 11.3.0, maybe need to update?

**Comment by NitramH** [comment]
Finally I set the CPU speed to 160 instead of 80. Seems to solve the Jitter.

Really don't know why it was working in the first half of the season wihtout problems :-(

**Comment by visualapproach** [comment]
> update from 3.2.0 to 4 using OTA is possible?

Yes it should be fine. After updating you can visit `layzspa.local/update_beta/` to get all the html files updated. It can be problematic sometimes to upload them OTA.
