### ISSUE TITLE
[BUG] Updated via webUI, now can't update again.

### ISSUE THREAD

**Issue by acolod** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#588]
**Describe the bug**
I clicked the "BETA: Update data file, then firmware" button on the chkupdatefw.hml page. It seemed to react the same way as usual but the FW number didn't change once the main page reloaded.  Checking for update again, it does not show anything available for Beta or Master. Everything seems to be working as expected still but would like to fix this so I can update.

**Screenshots**
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/34754076/e5890a75-505f-4dfe-86e0-f14663c1421f)

**Comment by visualapproach** [comment]
see end of this thread #584 
Thanks for your report!

**Comment by visualapproach** [comment]
Fixed, but you have to upload the old fashioned way once.
