### ISSUE TITLE
red levelshifter not to be found 

### ISSUE THREAD

**Issue by kallejoken** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#612]
**Hardware (please complete the following information):**
 - not yet available (helsinki is ordered)
 - probably 6 wires
 - PCB type V2 is ordered

i can't find the red levelshifter in germany - only the blue one can be found.
is the red one absolutely necessary?

**Comment by visualapproach** [comment]
It's a DIY project and expect to have to try both if the first don't work. I think the red one has a better track record but it's not guaranteed. I bet eBay ships to Germany and there are both colors for sale.

**Comment by vantech14** [comment]
@kallejoken did the blue shifter work for you?

**Comment by kallejoken** [comment]
> @kallejoken did the blue shifter work for you?

Yes and the Red shifter too

**Comment by kallejoken** [comment]
> @kallejoken did you need the 10k resistor? Thanks. I am making one of these up.

No Not resistor
