### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by GRINDER1975** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#618]
**Hardware (please complete the following information):**
 - Pump model S200102
 -6 wires
 - VT2B
 - RED

**Software (please complete the following information):**
 - Version most recent 

**Your message**

hi i have managed to build this project and gain control of the pump fia the web interface, but seem to have lost any ability to control the pump from the touch panel.

have checked soldering etc cannot seem to find issue

any help would be really appreciated

Marc

**Comment by visualapproach** [comment]
Are your buttons enabled in spa config?

**Comment by GRINDER1975** [comment]
yes they are.    i have run the hardware test and fail.  Been scratching my head most oif the day.  have several boards and can get none of them to work.  wonder if pcb fault.  its probably someting stupid. 
![board](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/143948698/e3cab652-e8b2-49a4-bcfc-a4dfff64bb8b)

**Comment by GRINDER1975** [comment]
wires in the middle for hardware test

**Comment by GRINDER1975** [comment]
CIO to DSP pin 3 fail!
CIO to DSP pin 4 fail!
CIO to DSP pin 5 fail!

DSP to CIO pin 3 fail!
DSP to CIO pin 4 fail!
DSP to CIO pin 5 fail!

**Comment by GRINDER1975** [comment]
this is what i am getting

**Comment by GRINDER1975** [comment]
progress of sorts.  are you able to point me to where i need to look re pin 4 fail and pin 5 0%bad?

CIO to DSP pin 3 success!
CIO to DSP pin 4 fail!
CIO to DSP pin 5 0% bad

DSP to CIO pin 3 success!
DSP to CIO pin 4 success!
DSP to CIO pin 5 success!

**Comment by visualapproach** [comment]
Either bad solders or wires, or broken LLC or Esp. Likely the latter since it's working one way. Guess it's not impossible for a bad solder to make a diode but I'd try new parts.

**Comment by GRINDER1975** [comment]
I am beginning to think this may be a faulty PCB.  i have built 5 from the same batch and none of them working.  Will order some new 2b Boards.

**Comment by GRINDER1975** [comment]
Answer to your last question - built another :)

**Comment by visualapproach** [comment]
same problem as @metaljay?

**Comment by metaljay** [comment]
> same problem as @metaljay?

Oh wow I think it could be, did you also order from JLPCB? @GRINDER1975 
I appear have 6 dead boards out of my batch. Wasn’t sure if I should contact them
