### ISSUE TITLE
 [OTHER] Connection to the s100101 pump (Hawaii Airjet 2021) 

### ISSUE THREAD

**Issue by codac** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#627]
**Hardware:**
 - Pump model: S100101
 - 6 wires
 - PCBV2B
 - Level shifter type: red,

**Software (please complete the following information):**
 - Version 4.2.1

How do I need to do a correct wiring regarding the provided photos?

As you can see on the pump side the following colors are set:
![IMG_2388](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9403626/30b4e26c-56ba-468d-ae4d-5f4c60fe5b0f)

I have wired the cables on the board, following the instructions of the manual.
Unfortunately, when I stick the connectors together, the red/black cable of the board are on the opposite side of the connector of the pump. So I guess my wiring is wrong.
![IMG_2390](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/9403626/aeb9fdfc-326e-4288-ac10-4e2ca3364505)

Any help is aprreciated.

**Comment by visualapproach** [comment]
Do not trust the colors! They are not consistent or logical. Find out which is 5V power and that it goes to the right pin. Then the other pins should be in order on your model

**Comment by codac** [comment]
Pretending, that 5V is one of the outer pins, GND ist next to 5V and NC is on the oposite side, and that the red wire of the pump is 5V, I measured the GND vs NC and had 0V. So I knew that NC as the exact oposite of 5V is not 5V. 
After that I changed to cables in that order, so that they properly fit the male and female adapter of the pump and it worked.

**Comment by Trikap82** [comment]
> Pretending, that 5V is one of the outer pins, GND ist next to 5V and NC is on the oposite side, and that the red wire of the pump is 5V, I measured the GND vs NC and had 0V. So I knew that NC as the exact oposite of 5V is not 5V. After that I changed to cables in that order, so that they properly fit the male and female adapter of the pump and it worked.

Hi Codac... I'm having trouble trying to use a PCBV2B... 

Hardware:

Pump model: S100101 (Lay-Z Spa St-Moritz, square pump) #58113
6 wires
PCBV2B
Level shifter type: **NO LEVEL SHIFTER**    <--- really requisite ?

bought it "plug and play"... well... So I need to investigate by myself.

Could you please post pictures of your final wiring ? Thx

Any help is aprreciated.

**Comment by visualapproach** [comment]
> Level shifter type: **NO LEVEL SHIFTER** <--- really requisite ?

In some lucky cases it will work without (but not on my PCBs without bridging). Since your setup doesn't work the answer is yes.
