### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by GRINDER1975** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#631]
**Hardware (please complete the following information):**
 - Pump model, for example 54123
 - 6 wires
 - v2 PCB type
 red

**Software (please complete the following information):**
 - Version

**Your message**
Hi i have got this all working now.

but i would like to add the ambient temperature sensor 

i have bought the part but it comes in a three pin package

voo, gnd, sig 

how do i solder?

**Comment by visualapproach** [comment]
Plz post what you did to get it working (in the other issue)

Haven't done that myself, but google [How to connect DS18B20 to ESP8266](https://www.google.se/search?q=How+to+connect+DS18B20+to+ESP8266&sca_esv=565694802&ei=5JUEZbirC8SNxc8Pu7G4yAc&ved=0ahUKEwi4raTBk62BAxXERvEDHbsYDnkQ4dUDCBA&uact=5&oq=How+to+connect+DS18B20+to+ESP8266&gs_lp=Egxnd3Mtd2l6LXNlcnAiIUhvdyB0byBjb25uZWN0IERTMThCMjAgdG8gRVNQODI2NjIGEAAYFhgeSJ4LUABYAHAAeAGQAQCYAVWgAVWqAQExuAEDyAEA-AEC-AEB4gMEGAAgQYgGAQ&sclient=gws-wiz-serp)
