### ISSUE TITLE
HELP e13 54138

### ISSUE THREAD

**Issue by pipppy1** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#632]
**Hardware (please complete the following

 information):**
 - Pump model, 54138
 - 4 wires
 - PCB type v2b
 - Level shifter type,txs0108e

**Software (please complete the following information):**
 - Version all

i just cannot get it to run e13 all the time
![20230916_155105](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/54774373/53a1dcc3-4cc3-4fc3-a064-0729daf4cd9c)

my settings are ![20230916_160654](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/54774373/1eb31806-b117-458f-bf5a-589afbffabae)

**Comment by visualapproach** [comment]
The wires should be in the white squares

**Comment by pipppy1** [comment]
thanks just moving them now

**Comment by pipppy1** [comment]
what should the pins be

**Comment by pipppy1** [comment]
![Uploading 20230916_163241.jpg…]()

**Comment by pipppy1** [comment]
![20230916_163241](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/54774373/9a7082ce-a055-41ad-8b12-5ea671b65a40)

**Comment by visualapproach** [comment]
As in your picture, but you need to move the wires to those pins. Now in port H1A you have them on D1 and D2, instead of D2 and D5. Same for the other port. move to D4 & D3 as the config says

**Comment by pipppy1** [comment]
all wires are moved
![20230916_164610](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/54774373/f4128bb0-72eb-4ecb-b430-57ba67124c0e)

**Comment by pipppy1** [comment]
still error 13

**Comment by pipppy1** [comment]
ok got it going
took out the D2 ect and just left it at 2 in ect in the config

**Comment by pipppy1** [comment]
bit confused though it works for a bit then goes into error 13

**Comment by georgemckee999** [comment]
Do the wires need to be in H1A and H2A? Mine are in H1B and H2B.

**Comment by visualapproach** [comment]
> @visualapproach Do the wires need to be in H1A and H2A? Mine are in H1B and H2B. 
> 
> ![Uploading IMG_6800.jpeg…]()
> 
> 

The beauty of DIY... They should be where they work. You have to find out by trying I'm afraid.

**Comment by georgemckee999** [comment]
Oh that’s a shame, I don’t know what any of them do. I brought this already wired up, I assumed it was in the right location until I saw this photo, now I’m not sure. All I get is e13

**Comment by visualapproach** [comment]
Yeah ok. There are many variants of pumps and there is no one size fits all solution, as I understand it. You have to find out which wire goes where. There is only a few combinations though. H1A or B is only to mitigate potential signal problems.
You should update to latest firmware if you haven't, and use the available tools to diagnose. Several threads here about that.
