### ISSUE TITLE
Enabled display buttons. All

### ISSUE THREAD

**Issue by pipppy1** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#633]
when i enable this can i use the panel and web interface at the same time

**Comment by pipppy1** [comment]
4 pin model

**Comment by pipppy1** [comment]
and also if it gets an error eg like e13 is it possible for it to show up in the web display

**Comment by visualapproach** [comment]
> and also if it gets an error eg like e13 is it possible for it to show up in the web display

isn't it already?

**Comment by pipppy1** [comment]
no

**Comment by pipppy1** [comment]
and one more question if possible. if i press one of the buttons on  the lazy spa does it relay back to the web server to say i pressed it

**Comment by visualapproach** [comment]
yes

**Comment by pipppy1** [comment]
but mine does not show no errors on the web display . but it will show it on the spa

**Comment by pipppy1** [comment]
btw this is a fantastic project

**Comment by visualapproach** [comment]
Thx, I think some errors are triggered internally to the display, and not sent to the pump, and therefore the ESP will not know about it. Some errors will be triggered by the pump and it has to tell the display, so we can catch the message.
