### ISSUE TITLE
Where can I buy preassembled hardware?

### ISSUE THREAD

**Issue by vantech14** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#636]
Hi,

Nice project! Im looking to control a hydro jet Hawaii. 

Where can I buy preassembled hardware for this project? Trying to find in the info but getting lost when it comes to ordering. 

Thanks.

**Comment by vantech14** [comment]
Found the correct manual and ordered all parts - thanks!

**Comment by sidequest-tomas** [comment]
Could you please post links to what you have ordered? :) 
I only have cables and an ESP8266, and it does not work without LLC from my tests.
