### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MattSpeke** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#639]
**Describe the bug**

Using Node Red to call for pump on/off to try and get a timer for on 5 mins every 30 mins. When I call for pump on it also calls for heat on. This also works for pump off switches heat off.  I can see the logic that if the heater is on the pump should be on, but turning the pump on shouldn't turn the heater on.

The control works as expected through the dashboard switches on home assistant.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/70768574/e89a7500-bfde-47f1-a021-eb5d4b47718f)

**Hardware (please complete the following information):**
 - Pump model, for example 54123
 - 4 or 6 wires
 - PCB type
 - Level shifter type,

**Software (please complete the following information):**
 - Version

**Additional context**

**Comment by visualapproach** [comment]
Not sure I would label this as a bug but that's okay. There is too little information given to help you. Long time since I did anything in node red but it seems the 'bug' is in your node red nodes. Use the debug output nodes to see what it spits out towards mqtt.
