### ISSUE TITLE
[BUG] Energy Today value not correct in Home Asistant MQTT Entity

### ISSUE THREAD

**Issue by MattSpeke** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#640]
**Describe the bug**

Energy Today Entity not correct in Home Assistant via MQTT. 

**To Reproduce**

**Expected behavior**

Energy Today should be reset every day. It looks like the value does not get reset. 

**Screenshots**

![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/70768574/70247225-1cc3-4c6d-b388-83d354583691)

![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/70768574/08e07bd2-203c-47a2-b322-852432943754)

![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/70768574/5f54c116-f441-49a8-9e5e-810ccfe8cf16)

**Hardware (please complete the following information):**
 - Pump model, for example 54123
 - 4 or 6 wires
 - PCB type
 - Level shifter type,

**Software (please complete the following information):**
 - Version

Via MQTT Mosquito Broker.

**Additional context**

**Comment by visualapproach** [comment]
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/22987250/161c8335-c2f6-4fc6-8de9-1deefb9818cc)

**Comment by MattSpeke** [comment]
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/70768574/704cced6-826e-44ee-b4c0-4ce7db8215c8)

Thanks.

**Comment by visualapproach** [comment]
You're welcome 😉
