### ISSUE TITLE
[FEATURE RQ]

### ISSUE THREAD

**Issue by lazmo88** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#647]
**Is your feature request related to a problem? Please describe.**

Nope, enhancement/custom mod idea.

**Describe the solution you'd like**

Would it be technically possible to include/integrate bubble motor speed control feature to the project, as shown here: https://youtu.be/A7npllZc0bw?si=P9eXRTRrT-IEJOan

**Describe alternatives you've considered**

Newer pump model that has adjustable airjet power.

**Additional context**
YT video: https://youtu.be/A7npllZc0bw?si=P9eXRTRrT-IEJOan

Example part used: https://a.co/d/frB7tzw (AC Motor Speed Control PWM regulator?)

**Comment by visualapproach** [comment]
Hi, Thanks for your suggestion. It's probably doable but it would require a lot more electronics hardware and I wouldn't feel comfortable advising people to mess with mains power.
