### ISSUE TITLE
Buttons don't work

### ISSUE THREAD

**Issue by matthewalampe** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#660]
S100105
6 wires
Software: 4.2.4
https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/134640012/647f65e6-adba-4c9f-b5ad-4f810bee1953

When selecting the buttons on the web interface, it turns off, and then on (see video). I've tried different browsers as well

https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/134640012/f6109119-78bc-49e2-8c33-32031e0bafd6

**Comment by metaljay** [comment]
have you configured your pump in HW settings tab? are you getting any display?
photos of the board would help too
