### ISSUE TITLE
visual studio build error 

### ISSUE THREAD

**Issue by huzsiroc** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#661]
i can't translate it with the visual studio please share the firmware file separately which i can flash to the esp module if possible thank you very much 
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/59470337/ed7de7fb-0f87-405a-a919-235720cd3cd3)

**Comment by undone37** [comment]
Hi huzsiroc,

this is a problem in plerup/EspSoftwareSerial (see https://github.com/plerup/espsoftwareserial/issues/307) and can be fixed by adding the `dok-net/ghostl` as dependency in platformio.ini:

```ini
;[...]
[env:nodemcuv2]
platform = espressif8266@^4
board = nodemcuv2
framework = arduino
lib_deps = 
	bblanchon/ArduinoJson
	; mcxiaoke/ESPDateTime
	links2004/WebSockets
	knolleary/PubSubClient
	me-no-dev/ESPAsyncTCP
	; khoih-prog/ESP_WifiManager@^1.12.1
        tzapu/WifiManager
	plerup/EspSoftwareSerial
	milesburton/DallasTemperature
        https://github.com/dok-net/ghostl ; << Fix missing circular_queue.h
board_build.filesystem = littlefs
extra_scripts = gzip_littlefs.py
;[...]
```

Hope this helps :)

**Comment by huzsiroc** [comment]
thank you very much for your help!!! So it is really solved!!! 
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/59470337/cce67a92-bde8-4b25-ab21-2dff19fcf451)

**Comment by visualapproach** [comment]
Thanks @huzsiroc , the .ini-file is updated with this and I locked ArduinoJSON to v6 since v7 gave a lot of deprecation warnings that I don't want to hassle with now.

**Comment by huzsiroc** [comment]
With great respect, thank you very much!
