### ISSUE TITLE
Software installation fails 

### ISSUE THREAD

**Issue by mr-mmc** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#679]
- Pump model  54123
 - 4 wires
 - PCB type  V2B
 - Level shifter type txs0108e

**Software (please complete the following information):**
 - Version 4.0?? Sorry newbie…
 
 Cannot connect esp

first time going through, but after minute make some error 🤷‍♂️
Second try and…
![IMG_0644](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/21967501/7e7a1645-41ad-4754-ae21-ec928e34470c)

**Comment by visualapproach** [comment]
Tried on a pc?

**Comment by mr-mmc** [comment]
> Tried on a pc? (Windows)

Yes, (win 11) devices not found, I think something gone broken 😔

**Comment by visualapproach** [comment]
Some modules require a reset while holding the flash button pressed, but may be something else. Try disconnecting everything and reboot pc. Also some modules have a counterfeit uart chip that doesn't work with the driver.

**Comment by visualapproach** [comment]
Just tried a fresh install on one of my modules and it works fine.

**Comment by simondean** [comment]
Lowering the upload speed fixed a similar issue for me on my Mac.  I changed this line in `platformio.ini` from this:

```
upload_speed = 921600
```

to this:

```
upload_speed = 460800
```

**Comment by mr-mmc** [comment]
new esp module arrived and, works fine, something broken ch340 chip.
