### ISSUE TITLE
[BUG] MQTT "energy" and "energy today" are the same

### ISSUE THREAD

**Issue by goofy79** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#681]
Hello,

i use the Lay-Z-SPA with the MQTT / HA Integration - here i have the sensor.layzspa_wifi_controller_layzspa_energy and the sensor.layzspa_wifi_controller_layzspa_today and both have the same value ? Shouldn't today be reset daily ?

![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/11212295/a6a8fca8-c735-4572-96f1-8b68337bc8a2)

BR
Goofy

**Comment by visualapproach** [comment]
You can schedule the daily meter to reset periodically.

**Comment by visualapproach** [comment]
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/22987250/8fd9b70f-34a4-439b-973a-b5ea88017d0b)
