### ISSUE TITLE
[BUG] Home Assistant shows both (C) and (F) entries as the Fahrenheit value.

### ISSUE THREAD

**Issue by PaleFlyer** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#684]
**Describe the bug**
I have entries in Home Assistant from MQTT/Mosquito for both C and F temps for everything but Ambient (I only have C for Ambient for some reason), but they both show as the Fahrenheit value.

**To Reproduce**
PCBV2B, with Filters
Maimi 2021 as the config (2022 Hot tub, but 6 wire)
Home Assistant 2024.3.1
Grab with MQTT Auto Discovery, look at device in MQTT

**Expected behavior**
Honestly, my preference would be to ditch the "double" entries totally, and just read out the configured value. IE if I set it to C in the ESP, read C, if I set it to F, read F.

**Screenshots**
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/6505180/d29549f8-0421-42d0-9728-2bd2236f455f)

**Hardware (please complete the following information):**
 - Pump Model "6 wire, 2021 (Air)"
 - 6 wires
 - PCB V2B
 - Red level shifter

**Software (please complete the following information):**
 - 4.2.5

**Additional context**

**Comment by visualapproach** [comment]
The ESP is sending both units but HA is translating temperatures to whatever unit you've set as preference.
