### ISSUE TITLE
[BUG] Hot tub non-functional if wifi is down

### ISSUE THREAD

**Issue by rozza-m** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#687]
**Describe the bug**
I know this is by design because of the way wifi-manager works but I think it's a significant weakness. If wifi cannot be found or is temporarily unavailable, the hot tub will not start and none of the buttons work. This introduces a significant (and obscure) point of failure - if the router is unplugged or the wifi password is changed, the hot tub appears to be completely dead - no lights, no sounds, can't be turned on with the power button - nothing. You can't even use the bubbles button to inflate your hot tub without wifi.

I know a captive portal is set up - but that is completely invisible and you have to know to look for it. Even with the portal running, the hot tub is non-functional until it gets proper wifi.

If it still functioned in a passthrough way when no wifi was available then this incredible project would have literally no downsides. As it is - it feels like a bit of a bummer to have to introduce a new point of failure.

**To Reproduce**
1. Have your hot tub uninflated/decommissioned
2. Unplug your router
3. Try to figure out how to inflate your hot tub

alternatively
1. Set up your hot tub
2. Have family member change the wifi password or reposition the router
3. ,Turn it off at the plug or cause RCD to trip or temporarily lose power
4. Turn it back on again
5. Hot tub appears completely broken to everyone other than the person that fitted the wifi module (who must know and remember that it appears dead if it doesn't have wifi)

**Expected behavior**
Hot tub works as a normal (non-connected) hot tub when wifi not available

**Comment by visualapproach** [comment]
Did you uncheck the WiFi Manager?
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/22987250/d724eeda-ede7-4543-b4c9-3275687dffd3)

**Comment by rozza-m** [comment]
No, what does that do? Does that make it so that if the wifi changes I have no way of configuring it?

**Comment by visualapproach** [comment]
The wi-fi manager is blocking the rest of the code from running, so by deactivating it it should still work without wi-fi. Handy if you have an unreliable router and want the tub to work. So yes, there is a possibility of locking yourself out, if you don't have a 6-wire version where you can press a special key sequence on the display to reset wi-fi. In that case you need to take the device to the USB cable again.
Now, ideally there would be a non blocking mode of the wi-fi manager, so the ESP would still be connected to your AP. Actually, there is, but it didn't work when I tried. I think it's too much for the 8266.

**Comment by rozza-m** [comment]
I guess this issue can be closed as it's by design. Perhaps it's worth considering better wording for the WiFi manager option to describe what it does?

Fwiw I find Wifi-manager to be a total pain in the (much simpler) projects I've tried - several different versions with identical documentation, incomplete documentation that is even labelled as being out of date...I wonder how the landscape of DIY esp-based DIY projects would be different if the most popular lib was a bit better.

**Comment by metaljay** [comment]
> I guess this issue can be closed as it's by design. Perhaps it's worth considering better wording for the WiFi manager option to describe what it does?
> 
> Fwiw I find Wifi-manager to be a total pain in the (much simpler) projects I've tried - several different versions with identical documentation, incomplete documentation that is even labelled as being out of date...I wonder how the landscape of DIY esp-based DIY projects would be different if the most popular lib was a bit better.

just to add, would you be open to doing a pull request to propose an alternative offering?
