### ISSUE TITLE
No response from Egg once board is added543

### ISSUE THREAD

**Issue by NickBeswick** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#698]
**Hardware (please complete the following information):**
 - Pump model 54327
 - 6 wires
 - PCB - Think V2 - picture added
 - Level shifter type, - no sure

**Software (please complete the following information):**
 - Version - not sure but latest from site

Hi All

Bought a board off Ebay and flashed it via the instructions.  I can connect to it and alter settings but when I connect it to the 54327 via the 6 wire cables I get nothing.  No lights, no sounds but it does power the board and I can connect to it via Wifi..

If sure its something simple I've missed so your help would be appreciated.

Photo attached.

Thanks Nick
![IMG_1138](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/68541371/fd6783ae-4f62-4aac-951d-273b1456a405)
![Screenshot 2024-05-01 at 15 25 25](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/68541371/03063b42-40fa-4f43-8464-c87bfcdbd3c0)
![Screenshot 2024-05-01 at 15 25 13](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/68541371/dfef9669-fb04-475a-afdd-cdd04e883406)
![Screenshot 2024-05-01 at 15 25 03](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/68541371/18afb900-91cd-40fa-98ec-f82964b6be0b)

**Comment by visualapproach** [comment]
You have a PCB_v2B and the picture says v2.
