### ISSUE TITLE
I'm unable to install

### ISSUE THREAD

**Issue by Gashrock** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#704]
hi i 'am trying to instal the code via vscode on an esp 8266 with a 6 wire version , but the thing is:
i can't find the "platform" when it come to install the file system image , under node mcuv2 

its on the page 12 of the PDF , thanks

**Comment by metaljay** [comment]
Have you installed platformIO (little alien icon on the left hand side) - top of page 12
