### ISSUE TITLE
[BUG] UI - remove brightness control when 4-wire configuration is in use

### ISSUE THREAD

**Issue by tunnus-1** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#705]
**Describe the bug**
Brightness control should be removed from the UI, whenever one of the 4-wire configurations is in use (e.g. 54154)

**To Reproduce**
N/A

**Expected behavior**
No brightness control visible with 4-wire

**Hardware (please complete the following information):**
 - Pump model 54148
 - 4 wire
 - PCB type V2
 - Level shifter: transistor based LLC

**Software (please complete the following information):**
 - Version 4.2.5

**Comment by visualapproach** [comment]
Yes that would be preferable

**Comment by visualapproach** [comment]
Done! (Dev branch)
