### ISSUE TITLE
Unable to install - No connection to ESP8266

### ISSUE THREAD

**Issue by markusschmitz81** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#714]
**Hardware (please complete the following information):**
 - Lazy Spa St. Lucia/ Rio S100101
 - 6 wires
 - BWCPCB _V2B
 - Level shifter type 1

**Software (please complete the following information):**
 - Visual Code Version: 1.89.1 (Universal) and newest PlatformIo

I am unable to connect to the ESP8266, I build the board like it is describe in the manual. After that I downloaded VSC and installed PlatformIo. 

I build the file system and then I tried to upload the file system but I am unable to get a connection to the Esp. 
I have two options cu.Bluetooth-incoming-Port and cu.BLTH, okay and auto. But nothing works.

the blue LED flashs sometimes but not more. 

Can somebody give me an advise?

Thank you 

Messages from the VSC Terminal see PDF...

[terminal upload filesystem.pdf](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/files/15447851/terminal.upload.filesystem.pdf)

**Comment by markusschmitz81** [comment]
Problem fixed: Wrong Usb cable and windows deactived the usb ports after an update

**Comment by visualapproach** [comment]
Lovely 😊 Thanks for the report
