### ISSUE TITLE
[BUG] MQTT Working but pressing button on Webinterface has no effect

### ISSUE THREAD

**Issue by j54j6** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#715]
**Describe the bug**
I am using a 6 Wire pre 2021 model. All works fine. I can connect it to HA and cotrol it with MQTT but using the webinterface has no effect. Commands will be queued (according to JS Output) but not exceuted (according to command queue)..

**To Reproduce**
1. Configure System with all stuff needed (NTP (0.de.pool.ntp.org), static IP Address, PiHole with unbound as DNS - blocked internet access)

**Expected behavior**
Webinterface should work even without internet access

**Screenshots**

**Hardware (please complete the following information):**
 - Pump model: 54123
 - 6 wires
 - PCB v2b
 - Level shifter type: TXS0108E

**Software (please complete the following information):**
 - 2024-05-09-1955

**Additional context**
If internet traffic is blocked - The webinterface does not work. 
Workaround: Enable NTP Traffic...

**Comment by visualapproach** [comment]
You can point to a local NTP if you have one. Don't know why the web UI wouldn't work but the device is supposed to know the time, or at least agree with the browser about what time it is. I guess your browser has the correct time and sends a command with a requested time (XTIME). The ESP is thinking it's 1971 and you'll have to wait 50 odd years or so to see the command beeing executed.
