### ISSUE TITLE
[BUG] can't read all of calibration pop up text

### ISSUE THREAD

**Issue by brucebuchan89** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#716]
**Describe the bug**
![Screenshot 2024-05-28 185909](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/154707542/74b51320-5b48-4fbd-b6e6-9f0dbe5e01b9)

See screenshot, positioning of the pop up text for calibration makes it difficult to read; have tried on computer and mobile browsers

**To Reproduce**
hover over question mark

**Expected behavior**
pop up should be centralised on screen

**Screenshots**
see screenshot

**Software (please complete the following information):**
 - Firmware: 2023-11-19-1330

Thanks

**Comment by visualapproach** [comment]
It's fixed in dev branch

**Comment by brucebuchan89** [comment]
thanks @visualapproach; for the time being, what is the text meant to say? thanks

**Comment by visualapproach** [comment]
![image](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/22987250/8542297e-f862-4043-8001-7ce3a801c60e)
