### ISSUE TITLE
Lost for required setup part

### ISSUE THREAD

**Issue by piltous** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#720]
**Hardware (please complete the following information):**
 - Pump: old miami, not sure about the pump model but old...
 - 4 wires
 - PCB type: I got the PCBv2 last one
 - Level shifter type: no idea at all, that’s the question in fact...

**Software (please complete the following information): not deployed yet....
 - Version

Hello,
Sorry to bother you but I'm lost in the documentation..

I ordered:
- PCB last version,
- NodeMCU v3
- misc. wires 

I don’t understand if I need LLC blue or red and 10k resistons. 

It seems counter intuitive to me in the doc and I would need some help/confirmation.

For the rest, soldering/compilation/installation it should not be an issue.

Thanks for you help and congratz for the work.
Rgds

**Comment by visualapproach** [comment]
Hi there! I'd go with the red LLC and you don't need the 10k resistor for that one. It seems more people get it to work on 4-wire models with the red one.

**Comment by piltous** [comment]
Hi,
Many thanks for the prompt answer!
I'll take this one.
Rgds
