### ISSUE TITLE
Toronto / 2024 pump compatibility?

### ISSUE THREAD

**Issue by lazmo88** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#724]
Hello 👋

Where are we standing with the compatability for 2024 models such as Toronto?

GLEDS in the newer models seems to also cause problems when there is a power cut, so you can't turn on the pump without manual intervention? Any solutions to this or can we still use ESP to switch the pump on after power outage?

**Comment by visualapproach** [comment]
No clue! Anyone else? /Visualapproach
