### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mchansy** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#725]
On the start page, the time of hydrojets is displayed incorrectly under Totals. The label and the value are displayed in the first column.

<img width="326" alt="Screenshot 2024-06-10 202318" src="https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/3874627/994d9e25-f804-4ee7-9f3a-35f5d8e4ba73">

 - Lay-Z-Spa Hawai

 - Version: 2023-10-17-2132

Solution:
index.js
document.getElementById('jetstotals').style.display = (msgobj.HASJETS ? '**table-row**' : 'none');

**Comment by visualapproach** [comment]
Thanks, fixed in dev branch now!
