### ISSUE TITLE
S100202 Pump

### ISSUE THREAD

**Issue by woodwai** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#733]
**Hardware (please complete the following information):**
 - S100202
 - 4 or 6 wires - Both
 - PCB type - V2B

**Software (please complete the following information):**
 - Firmware: 2023-11-19-1330

**Your message**

I opened up my Pump and it has 6 wires to the board, but only 4 to the display. I have the board working, and can control the pump, but I cannot get the display working. Does anyone have any ideas?

**Comment by visualapproach** [comment]
Is it a model with WiFi already built in?

**Comment by woodwai** [comment]
> Is it a model with WiFi already built in?

Yes it is.

**Comment by visualapproach** [comment]
Never got it to work with those. Someone switched the control boards to an ordinary but other than that I think the only way is to tap into their api. You can google it. I think it's in a home assistant forum.

**Comment by visualapproach** [comment]
What model did you select to make it work with the pump?

**Comment by woodwai** [comment]
> What model did you select to make it work with the pump?

6 wire, 2021 (air)

I cant get the BestWay app to work. Guess ill try switching the control boards as well then.

**Comment by visualapproach** [comment]
where do you live? (country)

**Comment by woodwai** [comment]
> where do you live? (country)

UK

**Comment by visualapproach** [comment]
Ok, I have some spare parts. Was thinking that you could have a display but I think the postage is quite expensive to UK and it's the old round version anyway, and I guess you have the square one.
If you can find a new display it would be interesting to see if you get it to work with different model setting on the display and pump. It *should* work

**Comment by woodwai** [comment]
Ah thanks - I’ve ordered another control unit and will see what happens. Most bizzare.

IW

**Comment by jrote1** [comment]
@woodwai did you ever get this to work?

**Comment by comm** [comment]
@woodwai: to confirm: all pump controls worked fine but the display doesn't?

I'd also be interested to understand if you got it resolved and how?

Thanks.

**Comment by woodwai** [comment]
Yes that was my finding with a WiFi control board model. I just purchased a non WiFi control model and it worked perfectly.
