### ISSUE TITLE
[FEATURE RQ] update over the air

### ISSUE THREAD

**Issue by ZoXx** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#736]
will it be possible again in the future to install updates directly without having to dismantle the pump and flash it via usb every time?
that was very helpful and really great

**Comment by visualapproach** [comment]
Hi, that has been possible all along. It's described in the manual. You just have to edit a couple of lines in platformio.ini. What is not possible is updating from the UI on the device web server.

**Comment by ZoXx** [comment]
Awesome! I will do it with next update. Thx!!! :)
