### ISSUE TITLE
[BUG] Display not working

### ISSUE THREAD

**Issue by fungio** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#739]
**Hardware (please complete the following information):**
- Pump model S100101
- 6 wires
- PCB - V2B - picture added
- Level shifter type, - the blue one

**Software (please complete the following information):**
- Version - the latest

![IMG_6340](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/2470117/9f59fde5-f250-4203-a67f-58f967709f6b)
![IMG_6341](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/2470117/9ee7e2cf-a460-4b3e-842f-ecf7a8dd721b)

Hi all, when I plug the PCB the display does not work, only *F light is on and no buttons are working. It makes a light bird chirp sound. As you can see in the picture I tried H1A & H1B but none worked. The ESP is powered and I can access it from wifi.

Any idea ?

**Comment by visualapproach** [comment]
Have you set the hardware config? saved and restarted?

**Comment by fungio** [comment]
I got it working. I don't know what I made to make it works but it does now. Thank you

**Comment by fungio** [comment]
I close the issue since everything is working perfectly now
