### ISSUE TITLE
Hardware configuration view [BUG]

### ISSUE THREAD

**Issue by n3xus1** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#748]
Hardware configuration view info doesn't show in screen

**To Reproduce**
1. Go to Hardware configuration
2. hover over ? for ambient temp sensor, sensor pins, power levels

**Screenshots**
![IMG_7301](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/6356263/a9dddb4e-58cc-45a0-9b76-d81da5417124)

**Hardware (please complete the following information):**
 - Pump model S100104
 - 6 wires
 - PCB type D1 Mini

**Software (please complete the following information):**
 - Version 4.4.0 beta

**Comment by n3xus1** [comment]
look like ambient temperature was fixed but the power levels still looks off
![Screenshot 2024-07-06 at 10 05 14 PM](https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA/assets/6356263/4a420f3b-ab1e-4783-ab5f-1286de8ed62c)

**Comment by visualapproach** [comment]
Should be fixed in latest dev :)
