### ISSUE TITLE
[BUG] Max heater temp on power outage

### ISSUE THREAD

**Issue by wittyaurelien** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#757]
**Describe the bug**
When there is a power outage, and the "Restore last states on startup" checkbox is checked, the SPA automatically restarts heating at 40°C, regardless of the temperature previously selected before the power outage.

**To Reproduce**
Only power outage, not on "restart ESP" 

**Hardware:**
 - Pump model : S100101 (6 wire, 2021 (air))
 - 6 wires
 - PCB type : V2B

**Software :**
 - Version : 2024-06-17-1334

**Comment by visualapproach** [comment]
Thx I'll look at it

**Comment by visualapproach** [comment]
@wittyaurelien Maybe its' fixed in development branch now. I found a bug that saved current states before restoring them, which ofc destroyed the previous setting. That bug should be fixed. Let's hope that was it.

**Comment by wittyaurelien** [comment]
After several tests of the version present in the development branch, it seems good! Thanks

**Comment by visualapproach** [comment]
Thanks for trying it out!
