### ISSUE TITLE
MQTT password not save upon restart[BUG]

### ISSUE THREAD

**Issue by n3xus1** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#770]
**Describe the bug**
when a restart of ESP is done the mqtt password is lost and upon restart mqtt is not connected. You need to reset the password and save for it to connect.

**To Reproduce**
1. set up mqtt
2. restart ESP from drop down menu
3. main page shows mqtt not connected

**Expected behavior**
I would assume that you should be able to restart the ESP and retain settings like user names and passwords

**Hardware (please complete the following information):**
- Pump model S100104
- 6 wires
- PCB type D1 Mini

**Software (please complete the following information):**
 - Version: 2024-07-19-0816

**Comment by visualapproach** [comment]
You got to give it a couple of minutes before it reconnects. It remembers between reboots

**Comment by n3xus1** [comment]
you are correct, I was just too impatient
