### ISSUE TITLE
[Help] RCD Breaker tripping

### ISSUE THREAD

**Issue by metaljay** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#771]
Slightly odd request for help, ive made up a 6 wire board, tested as normal on my pump everything works fine. Reset it and flashed latest update then shipped it to someone in the states, after a few emails back and forth he has said its tripping the RCD fuse on the plug.

He is able to plug in via USB and the board works fine including configuring it etc, but as soon as he plugs back into the pump it trips the fuse.

Any thoughts before I tell him to bin it and I'll send him another? nothing obvious from the photos especially considering I 100% tested this on my pump before I shipped it.
He has a S100105 pump and 4.4.2 firmware.

<img width="599" alt="Screenshot 2024-07-20 at 6 13 49 PM" src="https://github.com/user-attachments/assets/40ffcb90-67f8-4a72-b881-0474c3f0d0e3">
<img width="686" alt="Screenshot 2024-07-20 at 6 10 30 PM" src="https://github.com/user-attachments/assets/139026b6-75b2-4e28-a4bc-d48c71b5cba7">
<img width="681" alt="Screenshot 2024-07-20 at 6 11 29 PM" src="https://github.com/user-attachments/assets/98d97d1f-78bc-468d-910f-fe8f72698e56">

**Comment by visualapproach** [comment]
A gcf should only trip if current escapes into earth and not returning through neutral. At least I think it's the way it's supposed to work in eu. Sounds unlike that would be triggered by the device unless it touches earth

**Comment by metaljay** [comment]
Just came to update to say it now works. The board must of been touching something in the pump. Now it’s isolated it no longer shorts against metal…
