### ISSUE TITLE
Temperature range/manual heating

### ISSUE THREAD

**Issue by hosek** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#773]
**Hardware (please complete the following information):**
 - 2021 (Miami)
 - 6 wires
 - Custom
 - None

**Software (please complete the following information):**
 - Version 2024-07-07-2211

Hello, my friend (he has't got GH account so Im asking instead him) has problem with one specific case:
Heating is powered from solar system, so heating should be ideally turned on only during day, but minimal temperature can be set only to 20 degrees and if there is cold night the water in the pump unit cools down under that limit and heating is turned on, then it took about 10 minutes when flow of the water gives temperature sensor proper info that temperature inside hot tube is actually above or equal 20 and heating stops.

Do you have some advice how to solve it, please? Would be possible to allow lower temperature than 20, or add option for "manual heating only" ?

Thank you for awesome project ;)

**Comment by PaleFlyer** [comment]
Is your friend using something like Home Assistant/Ignition? If so, it's pretty easy. If it's just the ESP... no clue.

But like Visual said, Freeze Protection is "not avoidable".

And def need to just turn the heater off. Setpoint can be ignored.
