### ISSUE TITLE
Running VERY slow

### ISSUE THREAD

**Issue by allanstevens** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#780]
**Hardware (please complete the following information):**
 - Pump model #54123 Eggshape
 - 6 wires
 - PCB type V2B
 - Level shifter type, not sure what this means.

**Software (please complete the following information):**
 - Version 3.1.2

**Your message**
Hi first up, what a wonderful device.  Thank you.

It worked perfectly at first, but after a day or so, it started slowing down. For example, heating up would result in long, continuous beeps instead of the normal sound effect. A power cycle temporarily fixed the issue, but now it's happening right from startup. Do you have any ideas on how to troubleshoot this? Thank you.

**http://layzspa.local/info/**

Stack size:               236 
Free Dram Heap:           30776 
Min Dram Heap:            28352 
Max free Dram block size: 29456 

Free Iram Heap:           12104 
Max free Iram block size: 12104 

Core version:             3.1.2 
CPU fq:                   160 MHz
Cycle count:              1822539755 
Free cont stack:          1148 
Sketch size:              587296 
Free sketch space:        2555904 

**http://layzspa.local/inputs/**

Edges received on pin D1: 2415
Edges received on pin D2: 20231
Edges received on pin D5: 827
Edges received on pin D6: 1
Edges received on pin D4: 1
Edges received on pin D3: 1
Edges received on pin D7: 1
On 6-w pump the highest number is CLK, next is DATA and third is CS. On 4-wires the highest is CIO or DSP TX to ESP.

**http://layzspa.local/dir/**

[bootlog.txt](http://layzspa.local/bootlog.txt) Size: 695624 Bytes [remove](http://layzspa.local/remove/?FileToRemove=bootlog.txt)
[calib.html.gz](http://layzspa.local/calib.html) Size: 1759 Bytes [remove](http://layzspa.local/remove/?FileToRemove=calib.html.gz)
[chkupdatefw.html.gz](http://layzspa.local/chkupdatefw.html) Size: 192 Bytes [remove](http://layzspa.local/remove/?FileToRemove=chkupdatefw.html.gz)
[cmdq.json](http://layzspa.local/cmdq.json) Size: 9 Bytes [remove](http://layzspa.local/remove/?FileToRemove=cmdq.json)
[config.html.gz](http://layzspa.local/config.html) Size: 4625 Bytes [remove](http://layzspa.local/remove/?FileToRemove=config.html.gz)
[darkmode.js.gz](http://layzspa.local/darkmode.js) Size: 562 Bytes [remove](http://layzspa.local/remove/?FileToRemove=darkmode.js.gz)
[favicon.ico.gz](http://layzspa.local/favicon.ico) Size: 2525 Bytes [remove](http://layzspa.local/remove/?FileToRemove=favicon.ico.gz)
[favicon.png](http://layzspa.local/favicon.png) Size: 2425 Bytes [remove](http://layzspa.local/remove/?FileToRemove=favicon.png)
[filelist.txt](http://layzspa.local/filelist.txt) Size: 436 Bytes [remove](http://layzspa.local/remove/?FileToRemove=filelist.txt)
[function.js.gz](http://layzspa.local/function.js) Size: 614 Bytes [remove](http://layzspa.local/remove/?FileToRemove=function.js.gz)
[furelise.mel](http://layzspa.local/furelise.mel) Size: 556 Bytes [remove](http://layzspa.local/remove/?FileToRemove=furelise.mel)
[hwcfg.json](http://layzspa.local/hwcfg.json) Size: 201 Bytes [remove](http://layzspa.local/remove/?FileToRemove=hwcfg.json)
[hwconfig.html.gz](http://layzspa.local/hwconfig.html) Size: 3796 Bytes [remove](http://layzspa.local/remove/?FileToRemove=hwconfig.html.gz)
[hwtest1.jpg](http://layzspa.local/hwtest1.jpg) Size: 10533 Bytes [remove](http://layzspa.local/remove/?FileToRemove=hwtest1.jpg)
[hwtestinfo.html.gz](http://layzspa.local/hwtestinfo.html) Size: 1521 Bytes [remove](http://layzspa.local/remove/?FileToRemove=hwtestinfo.html.gz)
[index.html.gz](http://layzspa.local/index.html) Size: 6736 Bytes [remove](http://layzspa.local/remove/?FileToRemove=index.html.gz)
[index.js.gz](http://layzspa.local/index.js) Size: 3602 Bytes [remove](http://layzspa.local/remove/?FileToRemove=index.js.gz)
[links.html.gz](http://layzspa.local/links.html) Size: 208 Bytes [remove](http://layzspa.local/remove/?FileToRemove=links.html.gz)
[main.css.gz](http://layzspa.local/main.css) Size: 3088 Bytes [remove](http://layzspa.local/remove/?FileToRemove=main.css.gz)
[manifest.json](http://layzspa.local/manifest.json) Size: 444 Bytes [remove](http://layzspa.local/remove/?FileToRemove=manifest.json)
[menu.png](http://layzspa.local/menu.png) Size: 223 Bytes [remove](http://layzspa.local/remove/?FileToRemove=menu.png)
[mqtt.html.gz](http://layzspa.local/mqtt.html) Size: 2025 Bytes [remove](http://layzspa.local/remove/?FileToRemove=mqtt.html.gz)
[mqtt.json](http://layzspa.local/mqtt.json) Size: 181 Bytes [remove](http://layzspa.local/remove/?FileToRemove=mqtt.json)
[popcorn.mel](http://layzspa.local/popcorn.mel) Size: 970 Bytes [remove](http://layzspa.local/remove/?FileToRemove=popcorn.mel)
[remove.html.gz](http://layzspa.local/remove.html) Size: 1438 Bytes [remove](http://layzspa.local/remove/?FileToRemove=remove.html.gz)
[resetdaily](http://layzspa.local/resetdaily) Size: 88 Bytes [remove](http://layzspa.local/remove/?FileToRemove=resetdaily)
[settings.json](http://layzspa.local/settings.json) Size: 478 Bytes [remove](http://layzspa.local/remove/?FileToRemove=settings.json)
[states.txt](http://layzspa.local/states.txt) Size: 42 Bytes [remove](http://layzspa.local/remove/?FileToRemove=states.txt)
[success.html.gz](http://layzspa.local/success.html) Size: 1329 Bytes [remove](http://layzspa.local/remove/?FileToRemove=success.html.gz)
[upload.html.gz](http://layzspa.local/upload.html) Size: 1601 Bytes [remove](http://layzspa.local/remove/?FileToRemove=upload.html.gz)
[visualapproach.png](http://layzspa.local/visualapproach.png) Size: 2953 Bytes [remove](http://layzspa.local/remove/?FileToRemove=visualapproach.png)
[webconfig.html.gz](http://layzspa.local/webconfig.html) Size: 2125 Bytes [remove](http://layzspa.local/remove/?FileToRemove=webconfig.html.gz)
[weekender2](http://layzspa.local/weekender2) Size: 163 Bytes [remove](http://layzspa.local/remove/?FileToRemove=weekender2)
[weekender](http://layzspa.local/weekender) Size: 336 Bytes [remove](http://layzspa.local/remove/?FileToRemove=weekender)
[wifi.html.gz](http://layzspa.local/wifi.html) Size: 2453 Bytes [remove](http://layzspa.local/remove/?FileToRemove=wifi.html.gz)

**Comment by allanstevens** [comment]
It seems to have speeded up again now. 

Not sure if it's related, but I did the following things:

- Deleted bootlog.txt
- Deleted hwtest jpgs
- Turned off debug mode.  Not sure if debug mode was on, item was bought from ebay preconfigured.

Could the above have fixed the issue?  I'll post again if it starts to slow again.

Thanks.

**Comment by visualapproach** [comment]
Hi! Thanks for the kind words. The version you referred to is the core version (arduino framework or esp idf, don't remember). If you look at the bottom of your main page it says firmware: and a date/time.
The huge bootlog suggests you have had a lot of reboots. Don't know if the filesize is the direct issue but if you didn't reboot on purpose thousands of times there may be a problem with something.

**Comment by allanstevens** [comment]
Thanks for you reply,

Still working great and the bootlog didn't grow overnight 🤞🤞

Firmware: 2024-06-10-2016
Model: PRE2021
RSSI: -76

**Current bootlog**
{"BOOTINFO":"Software/System restart 2024-07-31 12:03:03"}
{"BOOTINFO":"Software/System restart 2024-07-31 12:03:03"}
{"BOOTINFO":"Software/System restart 2024-07-31 12:03:03"}
{"BOOTINFO":"Software/System restart 2024-07-31 12:03:03"}
{"BOOTINFO":"Software/System restart 2024-07-31 12:03:03"}
{"BOOTINFO":"Software/System restart 2024-07-31 12:03:03"}

**Comment by visualapproach** [comment]
Oh, I think I know why your bootlog expanded so much. Every time the NTP is reconnected it writes a new line in the file. That's a bug that is fixed in later versions. Along with other improvements. Don't fix things that ain't broken, but you may want to update to latest version.
You can click on 'releases' on github to see what's changed.

**Comment by allanstevens** [comment]
Thank you. I'll update it when I get a minute or two.
