### ISSUE TITLE
[BUG]  Deprecated option used in mqtt publish action call

### ISSUE THREAD

**Issue by acolod** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#784]
**Describe the bug**
Updated HA and integrations, now receiving this warning:

Deprecated option used in mqtt publish action call
This stops working in version 2025.2.0. Please address before upgrading.
Deprecated payload_template option used in MQTT publish action call to topic layzspa/command from payload template {"CMD":15,"VALUE":27, "XTIME":0, "INTERVAL":0}. Use the payload option instead. In automations templates are supported natively. Update the automation or script to use the payload option instead and restart Home Assistant to fix this issue.

Warning - 8/3/2024

**Expected behavior**

**Screenshots**
![2024-08-05 11_30_23-Settings – Home Assistant](https://github.com/user-attachments/assets/676e8d07-ae4b-4da1-b6ac-f6870c362b27)

**Hardware (please complete the following information):**

- S100105
- 6 Wire
- D1 Mini

**Software (please complete the following information):**
 - V4.4.5

**Comment by metaljay** [comment]
Just to add I don’t get this and I use MQTT & HA

**Comment by visualapproach** [comment]
I don't see anything about this in the docs. Thanks for reporting.

**Comment by n3xus1** [comment]
I also received this warning today after updating to the latest core version of home assistant 2024.8.0

**Comment by Skeletorjus** [comment]
Just replace `payload_template:` with `payload:` in your automations/script to remove the warning.

**Comment by PaleFlyer** [comment]
> Just replace `payload_template:` with `payload:` in your automations/script to remove the warning.

I tried that for when I push my local Tempest temperature into the ESP, and it had worse alarms.

**Comment by jamesonuk** [comment]
Thank you for saving my sanity....
I had put this down to what was being published to MQTT but obviously (and had I read the actual warning) it is what I am sending to MQTT.    It is setting the ambient temperature.

The docs on page 24 just need to be amended from `payload_template` to `payload` but not a bug in the code.
