### ISSUE TITLE
Enhancement : use previous settings (flag) when power loss

### ISSUE THREAD

**Issue by xmillies** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#82]
Add a function to restore to the last state if asked by the user after power loss.

**Comment by visualapproach** [comment]
Added but with no user interaction.

**Comment by xmillies** [comment]
Great.
Very useful function. 
I will test it this weekend

**Comment by xmillies** [comment]
The idea is not to ask use at restart for using last state or not.
But save what he wants in config. 
![Screenshot_20210624_074231](https://user-images.githubusercontent.com/1587568/123208893-2422c580-d4c0-11eb-877a-3a16fc1caad9.jpg)

**Comment by visualapproach** [comment]
Your request is fulfilled. Thanks for the suggestion!

**Comment by visualapproach** [comment]
(In development branch)
