### ISSUE TITLE
Electric power and energy calculation

### ISSUE THREAD

**Issue by faboaic** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#9]
We could calculate and show the electric power and consumed energy in kWh...
On a daily, monthly and total base.

As there is no power measurement included we know which state the spa is at every moment and show the (calculated) power.

Could be calibrated via variables or hard coded in the source code.

In my case energy is as follows: (not finally confirmed values... I need to take a closer look at it)

- On, but no filter running: 2 W
- Filter running: 38 - 41 W ( average 40 W)
- Heater: 1860 - 1950 W ( average 1900 W)
- Air: 800 - 850 
- Air + heater: ?

**Comment by visualapproach** [comment]
work in progress.

**Comment by visualapproach** [comment]
Done. Reopen if needed

**Comment by Bryla2137** [comment]
I just checked power consumption on my 6 wire Helsinki pump and values are the same as above, however bubbles + heater combined gives around 1800 W consumption, because heater is running at 50% power

**Comment by visualapproach** [comment]
Noted.
