### ISSUE TITLE
Port to ESPHome

### ISSUE THREAD

**Issue by hjkoster400d** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#93]
Did anyone tried to port this project to ESPHome (or is thinking about it)? 

I'm about to port this project to ESPHome because i use ESPHome for all of my projects to integrate with HomeAssistant. 

In addition, i would like to use the Wemos D1 mini v3 instead of the nodeMCU. Does anyone tried to use the wemos before for this project? (or has comments why, or why not to use the wemos)

**Comment by faboaic** [comment]
It has mqtt, so you can connect to HASS.
Is have wemos D1, works fine.
See somewhere here for pictures if you like
