### ISSUE TITLE
Beeps Like Original

### ISSUE THREAD

**Issue by denxhun** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#97]
Is it possible to use the beep like to original (non-smart ;) ) unit? 
I mean beeps on lock/unlock and every button press. I don't need to beep at every display change. (It could be annoying when timer is active and I'm sitting in the spa.)

**Comment by visualapproach** [comment]
Yes, but until that happens I suggest you turn audio OFF in the config page 😄

**Comment by denxhun** [comment]
This is exactly what I did as a temporary solution.😀

**Comment by visualapproach** [comment]
solved
